### ISSUE TITLE
What are valid groups for ami_groups parameter?

### ISSUE THREAD

**Issue by jm3** [mitchellh/packer#1068]
The docs are unclear on what AWS group IDs packer accepts. I tried the full IAMS ARN identifier (below), the numeric identifier by itself (555555555), and the group name by itself ("Developers"). All fail with the same error:

```
Build 'amazon-ebs' errored: Error modify AMI attributes: 
Invalid attribute item value "arn:aws:iam::555555555:group/Developers " 
for UserGroup item type. (InvalidAMIAttributeItemValue)
```

What kind of group identifier does it accept if not an IAMS group? Is it a placement group or a security group or something?

**Comment by sethvargo** [comment]
Hi @jm3 

If you would like to submit a PR to the docs, we would gladly review it.

**Comment by gldnspud** [comment]
I'm also having trouble with `ami_groups`, and also with `ami_users`. 

For each case, there always seems to be a space in the quoted item value in the error message, as demonstrated in the original comment for this ticket.

Could the trailing space have something to do with it? Or is that a "red herring"? What would be a good starting place to debug this? (I have no Go experience as of yet, but I'd consider taking a stab at it)

For now, I'm avoiding those configuration keys. It would be nice to have that functionality working, or to simply strip it from the documentation altogether if it's not expected to work correctly.

**Comment by mitchellh** [comment]
FIxed

**Comment by kylegoch** [comment]
This seems to have changed since the issue was created. The Packer Documentation now says that the only valid value is "all". But the document referenced by @jmassara may have since been updated:
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyImageAttribute.html

Shows this example, which is allowing an account to be specified. Not sure if this can be an array of accounts or just a single account passed. But it surely looks possible.

>Example 3
>
>This example grants launch permission to the AWS account with ID 111122223333.
>
>Sample Request
>
>https://ec2.amazonaws.com/?Action=ModifyImageAttribute
>&ImageId=ami-61a54008
>&LaunchPermission.Add.1.UserId=111122223333
>&AUTHPARAMS

@mitchellh / @sethvargo Can this be reopened for investigation, as it may be more than just a documentation issue.

**Comment by michaeltlombardi** [comment]
Is it _still_ the case that AMIs can't have groups assigned to them? I can't find the verbiage limiting the API to only the "All" option in the document, but neither are there examples of adding any specific group.

**Comment by rickard-von-essen** [comment]
Still only all
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchPermission.html

**Comment by michaeltlombardi** [comment]
Derp, of course. Thank you!
