### ISSUE TITLE
Build from snapshot

### ISSUE THREAD

**Issue by pandrew** [mitchellh/packer#1237]
I would like to first build a base snapshot and then by using another packer template continue the installation. For example:

```
{
  "builders": [{
    "name": "ubuntu-lts-puppet",
    "type": "digitalocean",
    "image": "Ubuntu 14.04 x64",
    "region": "ams1",
    "droplet_name": "ubuntu-lts-puppet",
    "snapshot_name": "ubuntu-lts-puppet"
  }],
    "provisioners": [{
    "type": "shell",
    "script": "scripts/puppet.sh"
  }]
}
```

When the snapshot is ready i want to use this snapshot in a new template. I have tried both image_id and image without success.

**Comment by tricon** [comment]
The issue is that Packer's DO API implementation [refers to an image by slug](https://github.com/mitchellh/packer/blob/a60039e720b873008e354c7610bb61d21c28a2bc/builder/digitalocean/api_v2.go#L142).

However, slugs are not set upon snapshot creation, nor can they be set. Response from the API: https://gist.github.com/tricon/fb1164cd32bc3d515bd7#file-packer-digitalocean-api-response-L49

The solution is to always use the image ID (Patch file): https://gist.github.com/tricon/d9cee142bfc44c8fc8cf

As I doubt it would be acceptable to change the use of ID vs. slug in this one instance, I recommend discussing a global change to the API implementation to utilize IDs instead of slugs. I am willing to handle this reimplementation if approved.

**Comment by andrewsomething** [comment]
Are you still able to recreate this? AFAICT, it has been fixed. I'm able to use Packer to create snapshots based on other snapshots by providing the id as an int in the template. It's likely a side effect of being ported to use the godo client.

**Comment by pandrew** [comment]
Building from snapshot using image id is working. I totally agree that referencing ids instead of slugs is a better way to handle this.
