### ISSUE TITLE
Build just an EBS snapshot

### ISSUE THREAD

**Issue by joshk0** [mitchellh/packer#1271]
We have a workflow where we regularly want to build an EBS snapshot but not a whole AMI. It would be cool to provide a source AMI to format the EBS volume and bootstrap the snapshot-builder, then when everything is complete, only retain the snapshot of the EBS volume, tag it as desired, then terminate the builder.

**Comment by mitchellh** [comment]
This still sounds like a good idea but hasn't been requested by anyone else. If we see a PR we'd be happy to accept it but due to the low demand, we don't plan on doing this on our own. Thanks!

**Comment by dnk8n** [comment]
I have a use case in support of this issue.

It would be very useful in maintaining a group of persistant volumes for a cluster of instances that would potentially use automatic scaling groups to increase the number of instances (and therefore persistent volumes) and to ensure that a persistant EBS volume is handed over from a terminated instance to the instance replacing it.

EBS Snapshots are useful to have as a starting template from which to create multiple persistent EBS Volumes (especially due to the fact that they can created EBS Volumes across multiple availablility zones).

The EBS Volume IDs can then be used as a unique filter for startup scripts of the instances to attach to. On initial boot of an instance (as apposed to a recovery boot), an EBS Volume can simply be requested through the relevant Amazon API... whereas a recovery boot could be instructed to attach to a particular EBS Volume.
