### ISSUE TITLE
Temporary floating IP address is not removed

### ISSUE THREAD

**Issue by petehayes** [mitchellh/packer#1534]
When packer is configured with just a floating_ip_pool and not a specific ip address it allocates a new ip address indicating that it is temporary, but once the build is complete, the ip address is not removed.

Packer : 0.7.1
Red Hat Open Stack

packer.json:
```
{
  "builders": [
    {
      "type": "openstack",
      "flavor": "3",
      "provider": "http://10.60.66.11:5000/v2.0",
      "image_name": "ve-controller-build",
      "username": "**********",
      "password": "**********",
      "source_image": "d8d8a763-e313-42db-a4af-ad3410e93bb2",
      "project": "test",
      "floating_ip_pool": "provider-network",
      "ssh_username": "cloud-user"
    }
  ],
  "provisioners": [
  	{
  		"type": "puppet-masterless",
  		"manifest_file": "puppet/manifests/site.pp",
  		"module_paths": [
  			"puppet/modules"
  		]
   	},
  	{
  		"type": "shell",
  		"inline": [
  			"sudo mkinitrd --force /boot/initramfs-$(uname -r).img $(uname -r)",
  			"rm -rf /tmp/packer-puppet-masterless /tmp/script.sh"
  		]
  	}
  ]
}
```

**Comment by jenspinney** [comment]
I hit the same problem with HP Public Cloud and looked into it a bit. Both Red Hat and HP Public Cloud use strings for floating IP IDs, whereas Rackspace (and the gophercloud library) expects integer IDs.

Unfortunately, the fix for this requires making simultaneous edits to packer and its fork of gophercloud. To build a version of packer that has this fixed, you'll need to make [this change](https://github.com/jenspinney/packer/commit/5a756bfab369f9e9a08fb3539c1d55ec1603141f) in packer and [this change](https://github.com/jenspinney/gophercloud-fork-40444fb/commit/8e22f7a490174275b059e42869d447198f03103b) in gophercloud-fork-40444fb.

(If someone with write access to these repos can help me get these checked in together, I'd love to get this in.)

**Comment by gkuchta** [comment]
This is impacting us as well. One of my coworkers has patched around the issue, but it'd be nice if it was in upstream.

**Comment by jamesrf** [comment]
+1 impacting us as well on HP Cloud

**Comment by jvtrigueros** [comment]
@jenspinney your patch worked for me! You should consider created a Pull Request and maybe this gets pulled into the next version. It was really annoying that it never got rid of the IP it created! You're awesome :smile:

**Comment by mitchellh** [comment]
This is now fixed!
