### ISSUE TITLE
x509 errors

### ISSUE THREAD

**Issue by civik** [mitchellh/packer#1683]
Getting error when attempting to use packer provisioner against RDO - Icehouse Openstack. 

Build 'openstack' errored: Post https://ost.<domain>.com:5000/v2.0/tokens: x509: certificate signed by unknown authority

I'm running Packer on Mac OSX 10.9.5.  Seemingly no capability to accept/ignore self-signed certs exists.

This issue is Mac specific - the problem seems to be from golang itself.  In src/pkg/crypto/x509/root_cgo_darwin.go they attempt to get the system default trusted roots using the keychain.  But it appears it only grabs the ‘System Roots’ keychain, and does not make use of any certificates marked as trusted in the ‘System’ or ‘login’ keychain

debug --
https://gist.github.com/civik/d1d4be73b72287e05a64

**Comment by einarf** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/tIK1ON3Pq6s/discussion

"Cross compiling will disable cgo, but accessing system root certificates on Mac OS X
requires cgo."

I guess the only good way to make a working darwin binary is to build it on osx.

**Comment by mitchellh** [comment]
This looks like a Go issue. Sorry! If this is important, please compile your own manually, since we don't want to build with cgo.

**Comment by dharmeshpurohit-24** [comment]
Hi

I am facing this issue while creating a windows bases AMI .

error: Build 'amazon-ebs' errored: RequestError: send request failed
caused by: Post https://ec2.us-east-1.amazonaws.com/: x509: certificate signed by unknown authority

I am running this from my Virtual Machine.

packer version: 1.0.0
windows : windows 7 64 bit

Any one please give any suggestion???

Thank you

**Comment by mwhooker** [comment]
Please open a new ticket with necessary debugging information
