### ISSUE TITLE
EC2 (EBS) builder ssh_private_key_file does not seem to work

### ISSUE THREAD

**Issue by dmitrig01** [mitchellh/packer#1697]
I am trying to use a private key file that's already established as a keypair in AWS. If I do something like `"ssh_private_key_file": "k.pem"`, packer fails with `amazon-ebs: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate%!(PACKER_COMMA) attempted methods [none publickey]%!(PACKER_COMMA) no supported methods remain`. When I look at the instance in the EC2 console, I see this:

![screen shot 2014-11-26 at 2 19 03 pm](https://cloud.githubusercontent.com/assets/10422/5209752/357cf6ac-7577-11e4-9f5a-4670f8ac590e.png)

**Comment by jantman** [comment]
I have to say that I find this option really confusing. From the documentation, I assumed it would allow me to specify the key file and keypair name (in ``temporary_key_pair_name``) and just work.

My first suggestion would be to change packer so that if ``ssh_private_key_file`` is specified, the value of ``temporary_key_pair_name`` is the name of an existing keypair to pass to the instance at start time. Yes, I'm aware that this would stay on the instance; IMO the main use of something like this is shops that have a single keypair they ALWAYS want on EVERY instance.

Alternatively, at a minimum, the documentation for ``ssh_private_key_file`` should at least specify that this keypair needs to already exist on the instance.

**Comment by catsby** [comment]
I've updated the documentation to be more clear that the key is expected to exist in the source AMI
