### ISSUE TITLE
Triplets of each character of the command in the boot screen

### ISSUE THREAD

**Issue by worthwhileindustries** [mitchellh/packer#1796]
- Host: windows 8.1
- Guest: CentOS 7

boot_command echos triplets of each character of the command in the boot screen so the kickstart file is unused. Is this an issue with my boot command? 

<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-7-x86_64/ks.cfg<enter><wait>

![capture](https://cloud.githubusercontent.com/assets/3536254/5562800/34aae8ac-8df9-11e4-9d55-72f9688e4279.JPG)

Thanks, T

**Comment by simon-p-r** [comment]
+1 having this issue also

**Comment by mitchellh** [comment]
This is usually caused by the CPU being overburdened while Packer is running. Since Packer uses keycommands to send it, it may be holding them down too long. We had another long discussion about this and concluded this isn't easier to fix. We can't make it faster because then the keystrokes sometimes never get registered. We can't make it slower because then more people get duplicates like you do.

I recommend trying on another machine. Sorry for the inconvenience, we don't know any more stable way to send keystrokes right now, and the way we do it now works 99% of the time as far as we can tell (reports like yours are very very rare).

**Comment by worthwhileindustries** [comment]
We don't know how to fix it doesn't seem like a reason to close the issue. It's still an issue and I've tried more than one machine.

**Comment by evanstucker-hates-2fa** [comment]
I also have this issue. Rebooting and running Packer before opening any other programs reduces, but doesn't eliminate the problem, so the idea of it being related to CPU load seems legit. I just wanted to mention how I worked around it, which is obvious in retrospect, but I thought I'd share it anyway:

Just remove the "<enter>" at the end of the boot_command.

Now, when Packer runs, you have the opportunity to manually go back and fix the typos. It's not a great workaround, but if you don't have any other hardware to throw at Packer, at least you can complete a build this way.

**Comment by rickard-von-essen** [comment]
There is a difference between we don't know how and it's not possible to entirely fix this. 

If someone have tweaks to improve please open a PR.

**Comment by evanstucker-hates-2fa** [comment]
I don't have any great ideas other than to set up some kind of Packer PXE server, but that seems like a lot of work to fix an issue that most people don't have...

**Comment by flmmartins** [comment]
I am facing this problem now with Windows 7 and CentOS 7 =(

**Comment by mwhooker** [comment]
We have `PACKER_KEY_INTERVAL` to manually tune the key press interval on the vmware and qemu builder. You can try adjusting that.

If it's not available on your builder, it shouldn't be too difficult (see step_type_boot_command.go under the respective builder), and happy to look at PRs.

Another idea is we can split the key interval into the interval between presses, and the interval we hold the key down for. I would love to see a PR for this, or at least a ticket be opened, because I need more information about the builder you're experiencing this issue on
