### ISSUE TITLE
Atlas post-processor fails with "unexpected EOF" when trying to upload a Vagrant box

### ISSUE THREAD

**Issue by KFishner** [mitchellh/packer#1815]
Crash log here:
https://gist.github.com/KFishner/613d17334b96f6967fe4

Packer template here:
https://gist.github.com/KFishner/1084057e7eb970c513d8

**Comment by Cbeck527** [comment]
Were you able to resolve this issue? I am seeing the same thing!

**Comment by KFishner** [comment]
Not yet, however the [Vagrant Cloud](http://www.packer.io/docs/post-processors/vagrant-cloud.html) post-processor works fine and will display the uploaded Vagrant box in the Atlas UI.

**Comment by Cbeck527** [comment]
Is it just as simple as swapping the `type` declaration to `"type": "vagrant-cloud"` ?

This is what I have in the block:

```json
"post-processors": [
    "vagrant",
    {
      "type": "vagrant-cloud",
      "access_token": "AUTH_TOKEN",
      "no_release": "true",
      "box_tag": "ORG_NAME/centos66",
      "version": "0.1.0",
      "metadata": {
        "created_at": "{{timestamp}}"
      }
    }
  ]
```

But when running I get this error when the post-processor tries to run:

```
=> virtualbox-iso: Running post-processor: vagrant-cloud
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, requires box from vagrant post-processor: mitchellh.virtualbox

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type, requires box from vagrant post-processor: mitchellh.virtualbox

==> Builds finished but no artifacts were created.
$
```

**Comment by jsangrador** [comment]
Hi, if this helps, I am seeing the same behavior with different post-processors after the "vagrant" one.

I have the vagrant post-processor followed by the vagrant-cloud and the latter fails miserably with the "Unknown artifact type, requires box from vagrant post-processor: mitchellh.virtualbox". If I build with the amazon-ebs builder, I get the correspondent "Unknown artifact type, requires box from vagrant post-processor: mitchellh.amazon-ebs" (or similar, this one is off the top of my mind). 

Aaaand, if I change the second post-processor to vagrant-s3 [ https://github.com/lmars/packer-post-processor-vagrant-s3 ], I get exactly the same errors.

Digging in the code of both I have seen that the Artifact they receive is not of vagrant (box) type, but respectively of the builder used. Which makes me think it is the dispatching code that is delivering the post-processors the wrong artifacts. But my ability to debug ends there, especially since I got into some reflection code which I didn't very much understand.

I hope that helps, please let me know if there is a fix for this.

Regards!

**Comment by lantrix** [comment]
I have the same issue.
This is from a Dev build from this commit b49d74d9990c56eba0b967fd952347d83cd68488 which I built to include the fix for https://github.com/mitchellh/packer/pull/1789

Template: https://gist.github.com/lantrix/21509c616b4d21c6e55b
Log (with debug):  https://gist.github.com/lantrix/f74ab3d6a1adac187839

Unlike @KFishner I don't see any uploaded Vagrant box in the Atlas UI.

**Comment by pearkes** [comment]
The Atlas post-processor now works. An important element is to define the sequence of post-processor so the Vagrant box will be uploaded and not the image resulting from the build.

Here's a working example:

```json
    "post-processors": [
        [{
            "type": "vagrant",
            "keep_input_artifact": false
        },
        {
            "type": "atlas",
            "only": ["vmware-iso"],
            "artifact": "{{user `atlas_username`}}/{{user `atlas_name`}}",
            "artifact_type": "vagrant.box",
            "metadata": {
                "provider": "vmware_desktop",
                "version": "0.0.1"
            }
        },
        {
            "type": "atlas",
            "only": ["virtualbox-iso"],
            "artifact": "{{user `atlas_username`}}/{{user `atlas_name`}}",
            "artifact_type": "vagrant.box",
            "metadata": {
                "provider": "virtualbox",
                "version": "0.0.1"
            }
        }]
    ]
```

I'm going to leave this open to update the documentation as @lantrix pointed out [here](https://www.packer.io/docs/post-processors/atlas.html#artifact_type).

**Comment by pearkes** [comment]
For the sequence, notice the nested arrays in the post-processor block or read [here](https://packer.io/docs/templates/post-processors.html) (see "Post-Processor Definition").

**Comment by danielghurley** [comment]
@pearkes Does this example still work in Packer 0.7.5?  I'm still getting '422 Unprocessable Entity' errors, but I'm not quite sure what the allowed values of "artifact_type" are.

**Comment by mitchellh** [comment]
This is all fixed up. @KFishner I think that panic is fixed but I can't actually line up the line numbers to check. Next time can you include the full debug log? And @lantrix your panic was fixed as well.
