### ISSUE TITLE
ISOs downloaded to packer_cache are hard to identify

### ISSUE THREAD

**Issue by whiteley** [mitchellh/packer#1826]
I've run into two cases with this:

1. wanting to prune unused ISOs in the `packer_cache` directory
1. wanting to use the ISO outside of packer

I was thinking of modifying `cache.go` to provide a symlink to the original remote file name
```
ubuntu-12.04.5-server-amd64.iso@ -> a96e7bb4875d673a7c716114a93a160625e0e1e63f55a6ea0cf21f54164c7991.iso
```

* Do you think this is acceptable/useful?
* Do you have an alternate idea to solve these issues?

Thanks!

**Comment by vtolstov** [comment]
may be always use name like: builder_vm_name.iso ?

**Comment by tylert** [comment]
Actually, what is the purpose of renaming the ISO files that get downloaded by packer?  Is this just to try to cut down on filesystem clashes in packer_cache when using multiple builders?  Would it be worth having a "packer pull foo.json" option that just downloads from iso_url/iso_urls using temporary hashed filenames that get renamed back to the original source ISO filename after it is finished downloading and checksum verification?

I would much rather preserve the original source ISO filenames for reasons similar to @whiteley.  Lacking an option to turn this renaming off, is there a way to tell packer to derive the strings to be used for the filenames using a different hash method?

I maintain a local cache of ISO files for various non-packer uses and it would be really helpful to be able to pre-populate the packer_cache directory (maybe with symlinks to trick it in the absence of an option in packer) when I want to cut down on re-downloading ISOs that I already have.  I'm just not quite sure what filename I need to give each ISO file since I haven't yet figured out how these hashes get derived.

**Comment by tylert** [comment]
Finally had some time to try to RTFM and figured I should provide the update here...

The method used to determine these packer_cache/*.iso hashes is just sha256 of the original URL string, for example:

    $ echo -n "http://cdimage.debian.org/cdimage/release/7.8.0/multi-arch/iso-cd/debian-7.8.0-amd64-i386-netinst.iso" | shasum -a 256
    ebd41bcd8d6e384b67a85631158506357b745f58ff42e3cb316d2c615aaad0d0  -
    $ ls packer_cache/
    ebd41bcd8d6e384b67a85631158506357b745f58ff42e3cb316d2c615aaad0d0.iso

**Comment by sethvargo** [comment]
As you identified, the values are the sha256 sums :smile:

**Comment by whiteley** [comment]
@sethvargo, my question was never about where the names come from as that was plainly obvious from the code :+1: 

* Do you think this is acceptable/useful?
* Do you have an alternate idea to solve these issues?

I'm guessing since this was closed without answering it's more that you guys don't find the issue important enough to accept the fix or propose an alternate?

Thanks!

**Comment by sethvargo** [comment]
@whiteley the issue is that the alternative is a crazy regex that parses out "bad" characters and somehow works cross-platform. We also are limited to a certain number of characters (because windows), so a shasum gives us all of that basically for free. Does that makes ense?

**Comment by whiteley** [comment]
@sethvargo I appreciate the explanation and freely admit that I never consider (acknowledge?) Windows! An extra iso or two laying around won't kill me :+1:

**Comment by sethvargo** [comment]
:wink:

**Comment by vtolstov** [comment]
@sethvargo in case of user provide multiply urls for the same iso sha changed, what about to download to tmp file, after that calculate sha256/sha512 sum and put file to packer_cache/SHA256/SHA512.iso ?
In all mirrors sha need to be equal, so on various url for same file we have same file on disk.

**Comment by oliviertremblay** [comment]
I understand that this is a closed issue, and that I'm bordering on necromancy here, but would it be okay to make the naming scheme configurable, defaulting to the current behaviour? It would be useful to me.

**Comment by StFS** [comment]
I'm a little confused. According to this the name of the ISO file URL is used to generate the hash. I have two builders (vagrant-iso and qemu), both using the exact same URL (copied and pasted), same checksum and checksum type but when I build one I download a file of one name but when I run the other it downloads the file all over again under a different name.

The URL in question is: "https://mirrors.kernel.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso"

I can only assume that this is because the URL used to generate the hash is the URL where the file is actually fetched from (after the mirror redirect).

Shouldn't this rather use the user specified URL to avoid re-downloading the file when hitting a different mirror?

Again... I'm only assuming this is what happened in my case, maybe I'm way off and something completely different is actually going on.

@sethvargo Curious to know what you have to say about this.

**Comment by deitch** [comment]
Is this still accurate @sethvargo ? I am downloading the latest ubuntu 16.04, URL is `http://releases.ubuntu.com/16.04/ubuntu-16.04-server-amd64.iso`. If I sha256 that (signature truncated in all output):

````
$ echo -n "http://releases.ubuntu.com/16.04/ubuntu-16.04-server-amd64.iso" | shamus -a 256
8d5ea7...
````

But looking in my `packer_cache/` directory:

````
$ ls -1 packer_cache/
05a242....iso
96301d....iso
````

I assume one of these is the vbox additions. Even so, neither of them matches.

**Comment by aespinosa** [comment]
From what i grokked in https://github.com/mitchellh/packer/blob/master/common/step_download.go#L75 , it's supposed to be using sha1 instead though.
