### ISSUE TITLE
Support reboot in the shell provisioner depending on the exit code of the script(s)

### ISSUE THREAD

**Issue by icnocop** [mitchellh/packer#1981]
Hi.

Thank you for packer 0.7.5.

I'd like to request support for reboots in the shell provisioner depending on the exit code of the script(s) being run.

It should reboot the virtual machine's guest OS, depending on the exit code, wait until the guest OS has finished rebooting, and then continue with the next provisioner.

In some cases, a reboot is required in the middle of an installation, or even multiple times, and so we can just re-run the same script(s) for further processing until completed successfully.

I am proposing the following new fields as part of the shell provisioner:
reboot_exit_codes
ignore_exit_codes
repeat_after_reboot

For example,
<pre>
"provisioners": [
        {
            "type": "shell",
            "remote_path": "/tmp/script.bat",
            "execute_command": "{{.Vars}} cmd /c C:/Windows/Temp/script.bat",
            "scripts": [
                "../scripts/win-updates.bat"
            ],
            <b>"reboot_exit_codes": [
                3010, 3011, 3015
            ],
            "ignore_exit_codes": [
                1638
            ],
            "repeat_after_reboot" : true</b>
        }
    ]
</pre>

This configuration would instruct packer to:
1. Run "win-updates.bat".
2. If the exit code is 3010, 3011, or 3015, gracefully reboot the guest OS and re-run "win-updates.bat" only after the guest OS has finished rebooting.
3. If the exit code is 1638, ignore it / treat it as 0 (success), and continue with the next provisioner.

Thank you!

**Comment by vtolstov** [comment]
split you script and reboot, after reboot run next.
i think you wish needed only in specific cases and not suitable for all.

**Comment by sethvargo** [comment]
Hi there,

As @vtolstov said, you can split out the scripts to achieve your desired result. I don't think this is a widely-needed use case, so I'm hesitant to add new options, but I'm going to leave this open to see if I'm wrong :smile:

**Comment by matt-richardson** [comment]
Hi @sethvargo

Its actually a super common use case (on windows at least), and we have had to do some hacky workarounds to deal with it. 

The issue with issuing a reboot on windows, then doing a sleep on the host, it terminates the sleep with an error (unlike on linux, where the sleep terminates without an error).

Otherwise, you have to do a sleep on the host (as there is non-deterministic ordering of ssh daemon shutdown), and wait for the reboot. If you sleep too short, then it will re-attach before the reboot. If you sleep too long, then your build takes longer than necessary (but how long is long enough?)

**Comment by cwarner-mdsol** [comment]
@sethvargo if you look at the return codes here https://msdn.microsoft.com/en-us/library/ee942965%28v=vs.110%29.aspx you'll see that 1641 and 3010 are the same exact thing. Dealing with Windows i'm finding a host of error codes that actually mean success or another error/issue that you might not care about while provisioning. Having a way to manage this would be useful.

**Comment by StefanScherer** [comment]
@icnocop I know the win-updates.bat from Joe's packer-windows repo with an unknown count of reboots needed until all Windows updates are downloaded and installed.

I have just seen the packer community work at https://github.com/packer-community/packer-windows-plugins providing some more windows specific builders and plugins. Perhaps this could be a better place for such windows specific tasks. They also have a WinRM communicator plugin instead of SSH.

**Comment by cwarner-mdsol** [comment]
Actually turns out https://github.com/packer-community/packer-windows-plugins/commit/2cb6f431b3f7050347dd0f4d0d534adb52c90c80 is already cooked; at least for Windows. I have rarely if ever come across anything in nix land that treats anything other than 0 as successful.

**Comment by mitchellh** [comment]
With the windows-restart provisioner now in, I think we shoudl just use that, and not build this into the shell provisioner.

**Comment by vtolstov** [comment]
@mitchellh in case of windows this is fine, in case of linux - what is the recommended way ?

**Comment by dragon788** [comment]
@vtolstov The suggestions I've seen are a simple script containing the following:

    #!/bin/bash
    reboot
    sleep 60

This seems to be working in my testing. If there are problems you can also add a "pause_before" to your template (see documentation for syntax) which tells the next script to wait a bit before trying to run.
