### ISSUE TITLE
How to restart machine during provision

### ISSUE THREAD

**Issue by majkinetor** [mitchellh/packer#1983]
I need to restart machine few times after I provision stuff. OS does some lengthy stuff on next boot, for instance Windows after installing updates.

Is it possible to do this ?

I guess I could be able to do this in setup phase, prior to provision, if I delay ssh service installation as the very last thing I can restart the system. However, setup phase has its limitations on Windows (for instance the amount of files you can upload from the host is limited to the floppy size).

**Comment by sethvargo** [comment]
Hi @majkinetor 

You can reboot the machine using the shell provisioner and your OS's reboot command. You can read more about the shell provisioner and rebooting here https://www.packer.io/docs/provisioners/shell.html. Does that answer your question?

**Comment by tyrken** [comment]
We're using OpenSSH & Windows also, and yes the https://github.com/joefitzgerald/packer-windows/blob/master/scripts/win-updates.ps1 trick of doing repeated windows updates & reboots before ever starting OpenSSH works.

For reboots after this we make it the last item in the set of scripts in one provisioner, and then put a minute or two of pause_before setting in the next provisioner to make sure Packer waits at the host.  Otherwise OpenSSH can keep running & so the next provisioner start before it's finished shutting down pre-reboot.  Slow & yucky but usually works, hope to try the WinRM provisioners in https://github.com/packer-community/packer-windows-plugins soon.

**Comment by majkinetor** [comment]
Exactly as @tyrken. Slow & yucky and most of all, not good enough. Maybe for your use case that was fine, but in general case you can't always have rebooting script to be the last one.

**Comment by mitchellh** [comment]
All of the above is the only way to do this, unfortunately. I'd be happy to entertain a better solution, but we haven't found one yet.

**Comment by vtolstov** [comment]
I think about this. May be add bool variable like need_reboot, and when
script end and ssh not available, wait for connection again...?
14 июня 2015 г. 2:42 пользователь "Mitchell Hashimoto" <
notifications@github.com> написал:

All of the above is the only way to do this, unfortunately. I'd be happy to
entertain a better solution, but we haven't found one yet.

—
Reply to this email directly or view it on GitHub
<https://github.com/mitchellh/packer/issues/1983#issuecomment-111760622>.

**Comment by mitchellh** [comment]
@vtolstov Yeah I think for backwards compatbility we likely need to inverse that boolean but yeah probably something like that.

**Comment by mconigliaro** [comment]
If you ever end up adding an option like that, it would be nice if it accepted a number of reboots to expect rather than just a boolean.

**Comment by wayneworkman** [comment]
@mitchellh What about a packer-native reboot call?
Not everyone's scripts will cause a reboot - the rebooting process for some (like in my case) can happen via a native packer reboot command.
I'll put the reboot provisioner in the order it needs to be.

You can handle the reboot in packer so that it's abstracted as packer aims to be - and handle waiting for the OS to become available again before proceeding.

**Comment by mwhooker** [comment]
@wayneworkman it would be great if you could add your use-case to https://github.com/hashicorp/packer/pull/4555
