### ISSUE TITLE
Intermittent failures for CLI acceptance tests

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2159]
This test sometimes passes and sometimes fails.

    go test github.com/mitchellh/packer/packer

When it fails, the output is inconsistent.

Example 1:

```
--- FAIL: TestRemoteCmd_StartWithUi-8 (0.00s)
	communicator_test.go:37: bad output: 'hello




		world


		there
		'
```

Example 2:

```
--- FAIL: TestRemoteCmd_StartWithUi-8 (0.00s)
	communicator_test.go:37: bad output: 'hello


		world
		there
		'
```

Example 3:

```
--- FAIL: TestRemoteCmd_StartWithUi-8 (0.00s)
	communicator_test.go:37: bad output: 'hello
		world


		there
		'
```

Occasionally it works fine:

```
ok  	github.com/mitchellh/packer/packer	0.226s
```

**Comment by cbednarski** [comment]
Example full output: https://gist.github.com/cbednarski/48285b12ee88bd1d7bbc

**Comment by mitchellh** [comment]
Ah, I've been going through this multiple times and haven't been able to figure it out yet. I first went to `iochan` thinking it was there somehow, but realized that it very likely isn't due to how simple iochan is (it is basically reading a string from a Go stdlib, and putting it on a channel, and also has a blank string check to ignore). So that means it is somewhere in Packer. Would love to see this fixed, but let's not spend too much time on it if we can't figure it out in a couple days.

**Comment by cbednarski** [comment]
The extra output that causes tests to fail comes from `stderr`. This is a side-effect of the scheduler with multiple goroutines sending output to `stdout` and `stderr` simultaneously. The test fails when their output overlaps.

On the other hand if they run serially and `stdout` completes first, the extra whitespace from `stderr` is all at the end and gets cleaned up by `strings.TrimSpace()`. That's why the test sometimes passes.
