### ISSUE TITLE
Make ssh agent forwarding disabled by default

### ISSUE THREAD

**Issue by andytson** [mitchellh/packer#2298]
SSH Agent Forwarding is a bad idea to be enabled by default. Agent forwarding lulls people into thinking they can use it to securely use their SSH key authentication on the server, but has a big problem that it can't easily be secured.

Any person with root permissions (or root via sudo) can find the socket that was created on the server, and use that socket for their own purposes, which allows them to authenticate with other servers the person SSHing in has access to.

The agent itself by default doesn't have any way to prevent this. Although it's possible to sort out a solution that asks for confirmation, most people wont even be aware of the issue.

Since it's best to institute security by default, I think it best that this is disabled by default, and a warning message put in the documentation to say enabling it might have this problem.

**Comment by mitchellh** [comment]
Hah. This is quite amusing, because we had SSH agent forwarding disabled by default on Terraform, and we got exactly the reverse argument that was also compelling. 

The inverse reason is that if you have an SSH agent, `ssh` itself automatically forwards the agent for you, so we should copy the behavior of `ssh` (where you opt out via SSH config). 

Another argument is that when using bastion hosts (a new feature of 0.8), SSH agents are generally used to connect through to the resulting server, or even to the bastion host. We found this by simply surveying our users asking for bastion support. Having agent forwarding by default makes it seamless for them.

I also think having access to the socket isn't too risky, especially with Packer: the machines are ephemeral, and a lot of times the SSH access key is also ephemeral, so it would be pretty difficult for someone else to gain access to the machine for the temporary time it is even available. And, even if you did, you still need root. 

Given I've heard both sides of this argument, I'm inclined to keep it the way it is for now. But I'll keep my ear open to any additional comments.

**Comment by andytson** [comment]
What ssh implementation enables ssh agent forwarding when ssh-agent enabled? Openssh doesn't

**Comment by mitchellh** [comment]
Hm, I'm not sure, assume I'm wrong on that. The rest is valid.

**Comment by andytson** [comment]
That said, I'm not using the latest version of openssh anywhere, but I doubt it's been added.

**Comment by andytson** [comment]
Perhaps at least acknowledge the issue on the documentation?

**Comment by andytson** [comment]
SSH bastion servers can work as a ProxyCommand, allowing tcp tunnelling, and not needing agent forwarding. This is what we do at my workplace, where we ban SSH agent forwarding

**Comment by mitchellh** [comment]
Yes, we're working on a new communicator section of the docs. The docs actually aren't updated to even cover WinRM. It is in a branch that I'll be deploying soon, and I'll be sure to include that in there.

**Comment by mitchellh** [comment]
I _agree_ with you, it is just have that I've heard valid arguments on both sides. It is an unwinnable argument currently for either of us. So let's just leave it as is.
