### ISSUE TITLE
"communicator" and "ssh_port" now needs to be explicitly set for gce builder

### ISSUE THREAD

**Issue by ulrikjohansson** [mitchellh/packer#2340]
I have a packer json file that uses the google compute engine builder, that worked just fine a few months ago, that is now throwing errors.
After some fiddling I managed to figure out that I now need to explicitly set the parameters `communicator to "ssh", and `ssh_port" to 22, or I will either get an "unknown communicator type:" (if communicator is not set in the json file) or it tries to connect to port 0 on the remote machine.

Is this expected behaviour? If so, the documentation for the gce builder should to be updated to reflect this.

I'm using packer 0.8.0

Update:
I noticed that the build also needs "ssh_timeout" set explicitly or I get an ssh timeout error instantly. With the parameter explicitly set, everything works and the image is built.

**Comment by mrcrilly** [comment]
I can confirm this is an issue, and @ulrikjohansson's very useful outline above saved me a lot of time. I do have additional points to add:

* I too had to set `ssh_port` to `22`, that is **not** `"22"`, but `22` - it had to be an integer, not a string;
* I also had to set `image_name` otherwise Packer wouldn't generate a valid name, instead passing: `packer-{{timestamp}}` to GCE, which complained it doesn't match the regular expression: `(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)`
* I have to have `ssh_timeout` set to at least `"30s"` otherwise it fails on a single SSH attempt;

Here are my results, without debug being turned on:

```
$ time packer build gcetest.json 
googlecompute output will be in this color.

==> googlecompute: Checking image does not exist...
==> googlecompute: Creating temporary SSH key for instance...
==> googlecompute: Creating instance...
    googlecompute: Loading zone: us-central1-a
    googlecompute: Loading image: centos-7-v20150603 in project my-project
    googlecompute: Loading machine type: n1-standard-1
    googlecompute: Loading network: default
    googlecompute: Requesting instance creation...
    googlecompute: Waiting for creation operation to complete...
    googlecompute: Instance has been created!
==> googlecompute: Waiting for the instance to become running...
    googlecompute: IP: 104.154.C.D
==> googlecompute: Waiting for SSH to become available...
==> googlecompute: Connected to SSH!
==> googlecompute: Deleting instance...
    googlecompute: Instance has been deleted!
==> googlecompute: Creating image...
==> googlecompute: Deleting disk...
    googlecompute: Disk has been deleted!
Build 'googlecompute' finished.

==> Builds finished. The artifacts of successful builds are:
--> googlecompute: A disk image was created: crilly-01

real	2m0.385s
user	0m2.024s
sys	0m0.132s

```

And here is the (desensitized) JSON file I was using:

```json
{
  "builders":
  [
    {
      "type": "googlecompute",
      "account_file": "/home/me/auth.json",
      "project_id": "my-project",
      "source_image": "centos-7-v20150603",
      "zone": "us-central1-a",
      "network": "default",
      "communicator": "ssh",
      "ssh_username": "packerio",
      "ssh_timeout": "35s",
      "ssh_port": 22,
      "image_name": "crilly-01"
    }
  ]
}

```

If you need anymore details or would like me to upgrade and run tests, please let me know.
