### ISSUE TITLE
In V0.8.0, compress post processor step broken on Mac

### ISSUE THREAD

**Issue by smithgcovert** [mitchellh/packer#2357]
I have some build definitions that use "compress" -- on Mac 10.10.3, they fail after updating to V0.8.0 -- the files will not validate or build.

The error message in the crash.log is:

2015/06/29 14:54:07 packer-post-processor-compress: panic: runtime error: invalid memory address or nil pointer dereference
2015/06/29 14:54:07 packer-post-processor-compress: [signal 0xb code=0x1 addr=0x0 pc=0x48509]
2015/06/29 14:54:07 packer-post-processor-compress: 
2015/06/29 14:54:07 packer-post-processor-compress: goroutine 12 [running]:
2015/06/29 14:54:07 packer-post-processor-compress: github.com/mitchellh/packer/post-processor/compress.(*PostProcessor).Configure(0xc20811a000, 0xc20801f1c0, 0x2, 0x2, 0x0, 0x0)
2015/06/29 14:54:07 packer-post-processor-compress: 	/Users/mitchellh/code/go/src/github.com/mitchellh/packer/post-processor/compress/post-processor.go:59 +0xd39

Full crash.log posted to forum.

**Comment by cbednarski** [comment]
@smithgcovert Thanks for the report. This was previous reported in https://github.com/mitchellh/packer/issues/2311 and fixed in https://github.com/mitchellh/packer/pull/2313. You can try building packer from master to get the fix, or keep an eye open for 0.8.1 which we're planning to release this week.
