### ISSUE TITLE
0.8.1 fails to build a CentOS 6.6 or 7 VM due to suduers file errors

### ISSUE THREAD

**Issue by kphannan** [mitchellh/packer#2394]
A template that works under 0.7.5 fails under 0.8.1 due to the /etc/sudoers file not being accessible.

The following fails in a provisioning script
    ```sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers```
with a read access error under 0.8.1, but not under 0.7.5

Since this fails, all subsequent provisioning commands that require ```sudo``` will fail with an indication that ```sudo``` requires a *tty* for operation.

This has been tried against the following install images:
- CentOS-7-x86_64-Minimal-1503-01.iso
- CentOS-6.6-x86_64-bin-DVD1.iso

Both work under 0.7.5, neither under 0.8.1  all else being equivalent but the version of Packer.

**Comment by cbednarski** [comment]
@kphannan Since `0.8.0` [we no longer allocate a PTY by default](https://github.com/mitchellh/packer/blob/master/CHANGELOG.md#080-june-23-2015), to prevent weird behavior for applications that do not expect one. To work around the issue with CentOS sudo you can use [`ssh_pty: true`](https://www.packer.io/docs/templates/communicator.html), or use a root login.
