### ISSUE TITLE
tags on resulting AMI not created

### ISSUE THREAD

**Issue by lylianmeyemezu** [mitchellh/packer#2426]
run_tags variables are correctly generated in the instance used to generate th AMI but not in resulting AMI though tags variables are the same as run_tags.

**Comment by catsby** [comment]
Hey @lylianmeyemezu – sorry for the trouble here, do you have a Packer configuration that demonstrates this? What Packer version are you running? 

I've tried to reproduce with this template running on the latest version, but I'm seeing the tags as I expect them:

```json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami": "ami-9eaa1cf6",
      "instance_type": "t2.micro",
      "ssh_username": "ubuntu",
      "ami_name": "packer-testing-{{timestamp}}",
      "run_tags": {
        "OS_Version": "Ubuntu",
        "Release": "Latest",
        "Runner": "Packer"
      },
      "tags": {
        "OS_Version": "Ubuntu",
        "Release": "Latest",
        "Runner": "EC2"
      }
    }
  ]
}

```

The instance running the build: 

![screen shot 2015-07-24 at 2 56 07 pm](https://cloud.githubusercontent.com/assets/61721/8883410/5602f142-3214-11e5-99bf-8eab2526bb29.png)


The resulting AMI:

![screen shot 2015-07-24 at 2 58 29 pm](https://cloud.githubusercontent.com/assets/61721/8883429/801b0bb8-3214-11e5-943d-3628d73b4f08.png)

**Comment by lylianmeyemezu** [comment]
Hi ,
thanks for replying.
there was a mismatch between rn_tags and tas in configuration.
It works well now.

**Comment by catsby** [comment]
Great to hear, thanks for following up!

**Comment by Allu1249** [comment]
==> amazon-ebs: Error querying AMI: NoCredentialProviders: no valid providers in chain
==> amazon-ebs: caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
==> amazon-ebs: SharedCredsLoad: failed to load profile, .
==> amazon-ebs: EC2RoleRequestError: no EC2 instance role found
==> amazon-ebs: caused by: EC2MetadataError: failed to make EC2Metadata request
==> amazon-ebs: caused by: <?xml version="1.0" encoding="iso-8859-1"?>
==> amazon-ebs: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
==> amazon-ebs:          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
==> amazon-ebs: <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
==> amazon-ebs:  <head>
==> amazon-ebs:   <title>404 - Not Found</title>
==> amazon-ebs:  </head>
==> amazon-ebs:  <body>
==> amazon-ebs:   <h1>404 - Not Found</h1>
==> amazon-ebs:  </body>
==> amazon-ebs: </html>
==> amazon-ebs:
Build 'amazon-ebs' errored: Error querying AMI: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
caused by: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>


==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
caused by: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>

**Comment by rickard-von-essen** [comment]
Hi @Allu1249, thanks for reaching out. 

This ticket is really old so it's probably not relevant to the issue you're seeing. If you're still having trouble, use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug please open new issue_
