### ISSUE TITLE
Allow providing metadata using Openstack

### ISSUE THREAD

**Issue by darrenhaken** [mitchellh/packer#2434]
I'm using Packer with RackSpace and they've ask us to provide metadata on server creation in reaction to failing image builds which have started happening.

I can't see a way of adding metadata, does this exist? If not would this be a feature that would be accepted?

**Comment by cbednarski** [comment]
@darrenhaken Can you tell me a bit more about the metadata you're trying to track? What data do you need? Is this something that's part of OpenStack or something specific to RackSpace?

**Comment by darrenhaken** [comment]
This was given by Rackspace so I'm not quite sure. They said a hash with a key "metadata" can be passed to their API.
Maybe it's a catch all for additional data.





On Mon, Jul 13, 2015 at 1:15 PM -0700, "Chris Bednarski" <notifications@github.com> wrote:












@darrenhaken Can you tell me a bit more about the metadata you're trying to track? What data do you need? Is this something that's part of OpenStack or something specific to RackSpace?

**Comment by cbednarski** [comment]
I'd like to know a bit more about what metadata should be passed. However, I think we can support arbitrary user data as specified in a configuration file.

I'm also curious whether this metadata field is compatible with other OpenStack providers. Do we have to detect that we're calling RackSpace or can we safely pass this metadata field along to any OpenStack build?

**Comment by trumant** [comment]
Glance and gophercloud both support arbitrary metadata on images. I'd like to PR this in the coming week.

**Comment by darrenhaken** [comment]
Is this something to be picked up? I sense it is from the issue log. 

Need anything else?

**Comment by aggroskater** [comment]
Racker Preston here, a GNU/Linux admin. I've been working on this particular issue (Rackspace "managed cloud" build automation failing) and attempting to act as a midway between our internal development team (which develops the build automation) to get to the bottom of it. Initially, the build failure issue appeared related to metadata passed (or not passed) to instances on spin up via the nova API. In this particular case, the issue was actually elsewhere (instance reboot killing "managed  cloud" automation while it was running on the instance). Regardless, being able to pass metadata might be a useful feature.

I notice that there is already support for waiting for RackConnect automation to complete in pull #1925 . There is similar documentation available to handle waiting for "managed cloud automation" to complete under the "Determining when the Managed Operations Post-Build Automation Process is Complete" section here:

http://www.rackspace.com/knowledge_center/article/how-to-programmatically-determine-the-rackconnect-v20-automation-status-of-your-cloud

I'm not at all experienced with Go, but I suspect it wouldn't be too difficult to adapt #1925 to handle waiting for managed cloud automation to complete instead. Something like:

```
if server.Metadata["rax_service_level_automation"] == "Complete" {
	break
}
```

**Comment by darrenhaken** [comment]
Hi,

We've been looking into this today and it looks rackconnect_wait is looking for the following metadata item:
rackconnect_automation_status

However not all RackSpace account types will have this metadata assigned to their virtual machines.
In our instance we have the metadata "rax_service_level_automation" as mentioned by @aggroskater .

I propose we check for both metadata flags to terminate the loop. Me and my colleague are working on this right now and should have a PR sorted soon (depending how long it takes us to write tests for it as we're new to Go Lang).

@aggroskater we're actually waiting on "rax_service_level_automation" to complete via a Packer post processor. 
Here is a Gist of the script: https://gist.github.com/darrenhaken/15e29c3c2acc445e143f
Do you think that this is still causing us issues if we already wait later?

I still agree that being able to supply metadata is incredibly valuable.

**Comment by aggroskater** [comment]
@darrenhaken Yes, that script should work for determining when managed cloud automation is complete. I spun up an internal test instance and had that script running during its initial spin up, and it worked as expected. I've also imaged the test instance and built another instance from it. The script also worked properly with that second instance.
