### ISSUE TITLE
Inconsistencies between amazon ec2 builder and others regarding units for volume/disk size

### ISSUE THREAD

**Issue by ankon** [mitchellh/packer#2464]
The ec2 builder in the `volume_size` parameter asks for a value in GiB (previously as an integer, in 0.8+ as string ...).

Other builds that support a `disk_size` parameter want that value in MiB.

This makes it a bit ugly to use different builders with the parameters coming in from the command line or defaults, as the values need to be kept in sync.

It would be nice if these could use the same units for their values.

**Comment by cbednarski** [comment]
We _could_ support this. It might be confusing having two options with different semantics to control the same setting, though, and we'd have to maintain both for backwards-compatibility anyway.

Maybe the better way forward is to accept a unit that can change the scale from e.g. `8mb` to `8gb`. We can fall back on the current behavior if no unit is provided.

**Comment by ankon** [comment]
Having a unit of some form would also help, indeed.

**Comment by tb3088** [comment]
only string values are supported by the v0.7.5 parser as well.

**Comment by artburkart** [comment]
This one seems tricky. 

Today, there are more builders configured in GB than in MB. Four of the five builders that use the `disk_size` key measure in MB. The amazon builders are inconsistent with each other. The amazon-chroot builder uses `root_volume_size` (whose accepted unit of measurement seems to be undocumented), while amazon-ebs and amazon-instance both use `volume_size` and measure in GB.

| builder  | key | unit |
|---|---|---|
| virtualbox-iso | `disk_size` | MB |
| parallels-iso | `disk_size` | MB |
| vmware | `disk_size` | MB |
| qemu | `disk_size` | MB |
| googlecompute | `disk_size` | GB |
| azure | `os_disk_size_gb` | GB |
| amazon-instance | `volume_size` | GB |
| amazon-ebs | `volume_size` | GB |
| amazon-chroot | `root_volume_size` | [GB](http://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateVolumeInput) |

I would be concerned that accepting values like '8mb' and '8gb' would encourage mistakes like specifying '8mb' for an amazon volume size, and having it get rejected by the AWS API, since a decimal would be an invalid input.

> ## Size
> 
> The size of the volume, in GiBs.
> 
> Constraints: 1-16384 for gp2, 4-16384 for io1, 500-16384 for st1, 500-16384 for sc1, and 1-1024 for standard. If you specify a snapshot, the volume size must be equal to or larger than the snapshot size.
> 
> Default: If you're creating the volume from a snapshot and don't specify a volume size, the default is the snapshot size.
> 
> Type: Integer
> 
> Required: No

I know I'm sort of resuscitating an old ticket here, but maybe implementing these changes doesn't make sense anymore. Thoughts?

**Comment by tb3088** [comment]
isn't the point of tools like Packer to be abstracted away from implementation inconsistencies among cloud providers? IMO all of the builders should recognize a common keyword, say "disk_size" (and of course can support the "proprietary" keyword like '{root_}volume_size') and also assume GB but can handle MB and convert to GB (modulo) as needed. The same recipe should work across all without changes or targetting. 

As to failing on API calls, it's supposed to fail if you feed it bad data.

**Comment by artburkart** [comment]
What would be the recommended course of action with the googlecompute builder?

**Comment by rickard-von-essen** [comment]
> We don't generally try to normalize the differences between different providers.

and 

> isn't the point of tools like Packer to be abstracted away from implementation inconsistencies among cloud providers?

No, Packer does not try to abstract away differences between builders. It tries to help automating the process of building virtual machine images. Abstracting the differences would lead to a blunt tool and cause a lot of bugs, inconsistencies and troubles. Instead every builder should be explicit and easy to understand _if_ you understand the virtualization it is working on.

> _[builders]_ document their current unit

Yes please provide a PR for the docs.

I think the best way I see forward if anyone really need this is to add some arithmetic functions to the templating so you cloud do something like ```{{ user `disk_size_gb` | mult 1024 }}``` to get from gb to mb.

With this I'm closing this as _wontfix_.

**Comment by artburkart** [comment]
@rickard-von-essen - Please see #4075
