### ISSUE TITLE
Make -machine-readable output consistent with respect to color

### ISSUE THREAD

**Issue by gareth** [mitchellh/packer#2521]
The first line of -machine-readable `packer build` output is often something like:

```
1438088586,,ui,say,amazon-ebs output will be in this color.
```

which is redundant given that issue #684 removed any color codes from this particular output. It feels like this line should be removed from -machine-readable output.

I'm using machine readable output to use the "new artifact" info in a script, but I actually also want to still pipe the ui output to screen. The line above makes the status output confusing.

One other option would be to use the target field which is empty in the example above. From [the docs](https://www.packer.io/docs/command-line/machine-readable.html):

> This is empty if the message is related to Packer globally. Otherwise, this is generally a build name so you can relate output to a specific build while parallel builds are running.

If the target field was filled for ui output as that suggests it should be, then I could differentiate between different targets but still use the machine-readable output:

```
1438088586,amazon-ebs,ui,say,amazon-ebs output will be in this color.
```

**Comment by noahspurrier** [comment]
This is a "Me, too", but more with respect to the empty target field. I'm running 10 parallel builds and the log messages are nearly useless because I can't tell which line of output was produced by any given build. It's like trying to put shredded documents back together. I had to add a flag to disable parallel builds to track down certain bugs.

The message about output color when machine-readable is set is also annoying.
