### ISSUE TITLE
Packer build fails with ssh: handshake failed: ssh: unable to authenticate, attempted methods 

### ISSUE THREAD

**Issue by ramreddy26** [mitchellh/packer#2582]
I am trying to build a centos 6 box on my windows 7 machine, but it is failing with below error.
Same build is running without any issue on OSX machine..

2015/08/11 18:02:51 machine readable: virtualbox-iso,error []string{"ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain"}
2015/08/11 18:02:51 ui error: --> virtualbox-iso: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**packer version 0.8.5**
**virtual box 5.0**

#1363 - Looks like a similar issue..
Here are my json file and debuglog 

https://gist.github.com/ramreddy26/f2d3f29ceca3ede4581f

**Comment by cbednarski** [comment]
Thanks for the report. Are you able to login if you build using `-debug` mode?

Also, I assume your kickstart script is creating the vagrant user?

**Comment by ramreddy26** [comment]
Line endings seems to be the issue, the build is successful after fixing the line endings on kick starter file.Thanks for your prompt reply.

**Comment by qrencha** [comment]
Hi Ram,

I've been working on building an ubuntu vagrant box on my Windows machine, I'm using Mobaxterm (cygwin) to run the packer commands from there, since it has ssh capabilities. However, at the end of the OS install I get the same error as you and after a while the Virtualbox instance disapears.

virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

What do you mean the "Line endings seems to be the issue"?
Thanks

**Comment by ramreddy26** [comment]
Hi,

Files created on Windows uses carriage return and line feed as line endings, whereas on Linux it uses only line feed. So if your file has Windows line endings fix it and try again.

Thanks,

Ram
