### ISSUE TITLE
go make: *** [updatedeps] Error 1

### ISSUE THREAD

**Issue by Kielan** [mitchellh/packer#2594]
after cloning packer into my $GOPATH/github.com/mitchelh repo calling make or make updatedeps throws make: **\* [updatedeps] Error 1 

Seems to be updating the deps but at the end I get the error

the last 4 lines of output in console:
golang.org/x/oauth2 (download)
google.golang.org/cloud (download)
google.golang.org/api (download)
make: **\* [updatedeps] Error 1

using go version 1.4.2

**Comment by rickard-von-essen** [comment]
Make sure you clone packer into $GOPATH/src/github.com/mitchellh.

**Comment by cbednarski** [comment]
@Kielan I've run this lately and it is working for me. I've seen a lot of failures in the past, for various reasons. Rickard pointed out one of them already:

- packer is not checked out to the right spot. In order for `go get` to work, packer has to be in the proper place in your`$GOPATH`. The easiest way to do this is to `go get github.com/mitchellh/packer`. If you created a symlink to the packer folder, you will need to `cd -P` so you get to the symlink target.
- Transient network and service failures. Sometimes `go get` fails because one of the upstream repositories is unreachable. This might happen because the network times out or there is an error response from one of the hosting services (github, gopkg.in, etc.). In this case, running `make updatedeps` again, or later, usually fixes it.
- Modified dependencies. `make updatedeps` runs `go get` with the `-u` flag, which means update. If you have gone into one of the dependencies in your `$GOPATH` and checked out a different branch or made changes, git will not be able to switch back to the master branch to update the dependency, and `go get` will fail.

In any of these cases, you should see an error message in your console that will indicate where the problem is happening. make will exit 1 if any of part of the update process fails, even though most of them can succeed, so you will need to look through the log to see where the failure is.

**Comment by mwhooker** [comment]
we're using govendor now so all this has changed. please create a new issue if you run into problems
