### ISSUE TITLE
Making targetpath customizable

### ISSUE THREAD

**Issue by twentytree** [mitchellh/packer#2600]
So there's a TargetPath var that decides where the iso goes once downloaded in common/step_download.go.

Say I wanted to use this to manage myself the name of the downloaded iso, defaulting to the current behavior if empty, would there be interest for me to actually do the work and merge it back in?

I'd also like for advice on what name to give the new configuration option. would iso_target_path work?

The changes of course would include appropriate documentation updates.

Have a good day!

**Comment by cbednarski** [comment]
Thanks for opening an issue. Can you clarify the use-case here? [`iso_url`](https://packer.io/docs/builders/vmware-iso.html#iso_url) can already be a local file so I'm not sure this adds any new functionality.

There is a problem I've run into where vmware and virtualbox will both download the same ubuntu ISO to two different files, wasting both disk and bandwidth. In this case, I would prefer to fix the problem by making this a deterministic operation and letting multiple builders share the iso file after it is downloaded. For example, it could use a filename generated from a hash of the URL, which will always be the same.

**Comment by oliviertremblay** [comment]
It's just in order to better know what files are what in the packer cache. Packer already names the files based on a hash, I've seen a bit of discussion about that in https://github.com/mitchellh/packer/issues/1826. My use-case is excellently worded by @tylert here: https://github.com/mitchellh/packer/issues/1826#issuecomment-73767976. Cleanup and pre-population of the cache made easier. 

My rationale along exposing the target path as an optional configuration is that it would allow the flexibility to those who see a use in that, and a comfortably useful default to those who don't really care.

**Comment by tylert** [comment]
I have also seen the issue mentioned by @cbednarski where the download URL hash is slightly different sometimes (I have since stopped using VMWare entirely due to the fact that the vagrant-vmware plugin is not free as in beer).  I originally guessted that this behaviour was merely due to HTTP redirect links.

Would it be possible (or desirable) to simply use the basename of the ISO file to derive the sha256 hash rather than the URL?

**Comment by cbednarski** [comment]
@oliviertremblay As I mentioned, I'm under the impression that `iso_url` already does what you want. If `iso_url` doesn't do what you want (makes copies of local data, duplicates downloads, clobbers other builders, etc.), I think we should fix that instead.

**Comment by tylert** [comment]
Hmm... I believe that what is being proposed here is to allow someone to control how the ISO file gets copied into the packer_cache dir;  Rather than simply rename the file after downloading it, @oliviertremblay may be proposing that there be a command-line/configuration setting that would allow this behaviour to be overridden or controlled;  It is my understanding that he already has the code ready for this and was requesting some feedback about the desirability/implementation of this feature.  Perhaps he would like to confirm my interpretation and that there were no misunderstandings.  I will suggest a possible use case for this enhancement below...

The use case for such a feature might be if one was trying to support many different ISO files and also try to cut down on having to delete the entire packer_cache to deprecate single ISO files since it is not immediately obvious which file belongs to which URL(s).  It is assumed that a lot of people who use packer--at least, initially--probably maintain a local mirror of ISO files.  These files are then copied from this ISO cache into their packer_cache.  As folks experiment with multiple distros/versions, they may be dealing with several GBs of stuff in packer_cache which, under normal circumstances, they might want to try to clean this stuff up periodically to try to make maximum use of their fancy SSD, for example.  Trying to "trick" packer into setting "PACKER_CACHE_DIR=/my/iso/cache" does not help much since packer renames all the ISO files it downloads.  Dumping the entire packer_cache or redownloading the entire ISO on each run (perhaps for automated CI runs, say) also seems somewhat inefficient.

My sugestion would be to perhaps allow the configuration item to allow the sha256 hash to either include the full URL for the hash (the default) or not include the "http://foo.com" part of the URL and instead hash only the "my_distro.iso" part of the ISO filename.  Such a setting would allow somebody with a lot of ISO files to guarantee that "http://localhost/my_distro.iso" and "http://foo.com/my_distro.iso" would hash to the same value when specifying multiple "iso_urls" list entries.  Alternately, allowing the setting to toggle the renaming of the file to a hash might also be a reasonable alternative.

**Comment by beddari** [comment]
A cache is a cache and not a store, in my opinion :-) The only change that is a real improvement in my opinion would be to change the hashed naming from using the full URL as input to just the filename, as suggested by @tylert in his last paragraph above.

Maybe to help out those that want to keep a persistent, named iso on disk we could document a pattern like this:

```json
"iso_urls": [
  "{{user `ISO_PREFIX_LOCAL`}}/{{user `ISO_FILENAME`}}",
  "{{user `ISO_PREFIX_URL`}}/{{user `ISO_FILENAME`}}"
],
```

**Comment by oliviertremblay** [comment]
The point of making it a configurable option is to let the user pick and choose when and if it matters to him; I expect some people will care, and others would not. I find the default to be fine for a lot of use cases, in the sense that it's very portable.

**Comment by tylert** [comment]
@beddari that is a reasonable assumption.  However, I already treat all of the "not renamed" ISOs that I retain locally as a cache since some of them change often (they may even get remastered before use).  I was merely hoping that there might be an option to avoid having to copy, for example, a 4GB ISO file from a local store to a local cache, simply so that the file can be renamed to a hash.

Also, in your pattern example shown, I'm fairly certain that both of those ISOs would be given different hash values and, in this example, may take up 8 GB in the local cache on top of the 4 GB for the one in the local store.

Pre-creating the SHA256 URL symlinks for each ISO file in packer_cache is what I have been doing in the meantime (so I can quickly find the original filename with "ls -l | grep foo") but it's still an ugly hack.

I fully acknowledge that my use case is perhaps not typical, however, I would hope that you can see the value of having a way to control this renaming behaviour a bit.

**Comment by yoyo42** [comment]
I use ISOs for many reasons, not just for packer. Having multiple copies of 4GB ISOs around just so Packer can 'cache' the files back onto the same disk they are already on is a bit wasteful. Would it be possible for Packer to check if a file with the correct name (and checksum?) is in the cache first before checking for the hashed name? That way I could preload the cache with a copy, a hard link or a symbolic link (as available) before running Packer and avoid the download altogether.

If hashes stay as the only option is there any chance of generating a simple index file in the cache folder listing what completed files are in there, e.g. many lines of:  "hash", "filename", "full URL"?

**Comment by cbednarski** [comment]
Implemented here: https://github.com/mitchellh/packer/pull/2642

**Comment by tylert** [comment]
I tried out a test build using commit e9657e6 and I am able to confirm this feature is working properly as of that commit.

Here's the rough outline of my template:

````
...
  "variables": {
...
    "packer_cache_dir": "{{env `PACKER_CACHE_DIR`}}",
    "iso_file_name": "ubuntu-14.04.3-server-amd64.iso",
    "iso_file_location_far": "http://releases.ubuntu.com/14.04.3",
    "iso_file_location_near": "http://helper-server.local/iso",
    "iso_checksum": "a3b345908a826e262f4ea1afeb357fd09ec0558cf34e6c9112cead4bb55ccdfb",
    "iso_checksum_type": "sha256",
...
  }
...
  "builders": [
...
      "iso_urls": [
        "{{user `iso_file_location_near`}}/{{user `iso_file_name`}}",
        "{{user `iso_file_location_far`}}/{{user `iso_file_name`}}"
      ]
      "iso_checksum": "{{user `iso_checksum`}}",
      "iso_checksum_type": "{{user `iso_checksum_type`}}",
      "iso_target_path": "{{user `packer_cache_dir`}}/{{user `iso_file_name`}}",
...
  ]
...
````
