### ISSUE TITLE
Packer zip file bombs the current directory

### ISSUE THREAD

**Issue by RJ** [mitchellh/packer#2621]
When unzipping the packer_x.y.z zip file it dumps the binaries into the current directory.

As far as i'm aware, this is universally considered bad zip/tar etiquette.

Please consider changing the zip file download so it unpacks into a ./packer_x.y.z directory, thanks.

**Comment by cbednarski** [comment]
Thanks for opening an issue. Since there are various downstreams like chocolatey, homebrew, etc. that expect the current package format, changing it is likely to break a bunch of stuff.

Also since all of the binaries glob under `packer*` and you can `mv packer*` or `rm packer*` pretty easily, I don't think the flat zipfile causes a lot of problems.
