### ISSUE TITLE
Fix documentation self-reference to "PACKER_LOG" on environment variables page

### ISSUE THREAD

**Issue by tylert** [mitchellh/packer#2623]
The "PACKER_LOG" entry on https://packer.io/docs/other/environmental-variables.html is missing a hyperlink reference like https://packer.io/docs/other/environmental-variables.html#PACKER_LOG_PATH has.

**Comment by tylert** [comment]
I had a look at the actual file under website and it looked fine to me--I don't see why the reference wasn't created.

**Comment by cbednarski** [comment]
Hm. Yeah it might be because it shows up twice so there would be an #id conflict. I think it happens on a few other pages, too. The headings are automatically generated and I have't looked too deeply into middleman so I don't know how to fix that. Maybe it can be fixed by adding `<span id="PACKER_LOG"></span>` just above it.

**Comment by tylert** [comment]
I would say this issue is kinda out of date now.  I would recommend just closing this, waiting for 0.9.0 to settle down and then deal with the new website doc comparisons again later.

**Comment by cbednarski** [comment]
Related: https://github.com/mitchellh/packer/issues/3163
