### ISSUE TITLE
Docker builder: Error creating output file: open : no such file or directory

### ISSUE THREAD

**Issue by cbednarski** [mitchellh/packer#2626]
When trying to build a docker container if you don't specify `export_path` or `commit` you will get an error:

```
 Error creating output file: open : no such file or directory
```

For starters, this is not a very helpful error message. Also we should be able to catch this early on in the config validation. In some cases you may not actually want to keep the docker container (for example, if you are using artifice), but in that case we should probably support something like `"discard": true` so it's explicit, rather than waiting for your build to fail.

/cc @justincampbell

**Comment by derks** [comment]
Bump: Hitting this same issue when setting `export_path` to include a directory that does not exist.  For example:

```json
}
    "builders": [
        {
            "export_path": "{{user `build_path`}}/ubuntu-16.04/docker/ubuntu-16.04.tar",
            "image": "ubuntu:16.04",
            "type": "docker"
        }
    ]
}
```

This fails because `/path/to/ubuntu-16.04/docker` does not exist.  This is the same place I attempt to build `virtualbox-ovf` and `vmware-vmx` ... both of which utilize the `output_path` setting, and if the `output_path` does not exist it is created.

The `docker` builder should create the base directory of `export_path` if it does not exist.
