### ISSUE TITLE
Provisioning shell script propagation of exit code

### ISSUE THREAD

**Issue by david-strejc** [mitchellh/packer#2702]
Provisioning shell script is not propagating exit code - so when it fails VM still builds successfully.

This is my scenario:

I got packer.io for building VM images. I provision VMs with shell script which uses puppet.
Now sometimes there is situation where this provisioning script fails to provision VM correctly.
I am using Rundeck to trigger provisioning by packer.
I need a way how to tell Rundeck that provisioning script inside VM failed.
I haven't found anything in documentation of packer.io according this issue.

**Comment by pecigonzalo** [comment]
Windows or Linux?

**Comment by david-strejc** [comment]
Linux host building Linux guest.

**Comment by cbednarski** [comment]
@david-strejc Thanks for the report, and sorry for the late reply. I have seen this issue before and the problem was that even though the provisioning script failed, puppet reported that the run was successful. To resolve this you will need puppet to fail so the puppet provisioner passes correct the error code back to packer.
