### ISSUE TITLE
Access communicator.Config from provisioner

### ISSUE THREAD

**Issue by LinusU** [mitchellh/packer#2717]
I'm trying to create a provisioner that uses Ansible without `ansible-local`. For that I need to execute `ansible-playbook` on the machine I'm running packer on and then point it, via ssh, to the server I want to provision.

I think that this is a much better way than `ansible-local` since that have problems with `become` and `sudo` and also requires `ansible` to be installed on the target machine which it often isn't.

Is there any way to access this information from the provisioner? This is as far as I have got:

```go
func (p *Provisioner) Provision(ui packer.Ui, comm packer.Communicator) error {
  ui.Say("Provisioning with Ansible...")

  var dasdasd = fmt.Sprintf("%s ansible_ssh_host=%s ansible_ssh_port=%d ansible_ssh_user=%s ansible_ssh_private_key_file=%s", "test-server-1", comm.Config.SSHHost, comm.Config.SSHPort, comm.Config.SSHUsername, comm.Config.SSHPrivateKey)

  ui.Say(dasdasd)
}
```

I just can't figure out how to access the correct options.

**Comment by rickard-von-essen** [comment]
Did you see #1969 ?

**Comment by LinusU** [comment]
No I did not, and now I feel like an idiot :smile: Thank you, I'll have a look

**Comment by rickard-von-essen** [comment]
I bet you learned a lot in the process. :bulb:

**Comment by LinusU** [comment]
Indeed I did :)

I'm still not convinced that it's a bad idea for the provisioned to have access to the ssh confit thought. The other approach is very complex compared to just running "ansible-playbook" and just pointing it to the server. It feels like this would be less error-prone as well...

**Comment by cbednarski** [comment]
> I'm still not convinced that it's a bad idea for the provisioned to have access to the ssh config

The design around communicators accomplishes two things:

The first is that the provisioner requires much less configuration because it does not need to know about where to find the SSH private key. If we pass the configuration in we then also have to duplicate the logic that locates the key file or password, initializes the connection, etc. and generally this makes the code a lot more complicated.

The second is that the provisioner uses the communicator as an interface, and thus the underlying communicator could be `ssh` or `winrm` or the docker API and the same provisioner can work in all three cases (for example the file provisioner works this way) provided that communicator implements the standard interface. This means that we can add new communicators later without necessarily having to re-implement each provisioner to use them.

I'd like to incorporate #1969 into packer core so hopefully that will resolve this issue for you. Cheers!
