### ISSUE TITLE
Support for Odin Virtuozzo (Parallels PVC)

### ISSUE THREAD

**Issue by craneworks** [mitchellh/packer#2721]
Would it be possible to add the support for Parallels PVC aka [Virtuozzo](http://www.odin.com/products/virtuozzo/)?

**Comment by rickard-von-essen** [comment]
It might, I guess the first obstacle is that I don't have access to a Virtuozzo system. (I wrote and maintain the Parallels Desktop builder)

**Comment by rickard-von-essen** [comment]
@legal90 anything to add here?

**Comment by craneworks** [comment]
I'm thinking about giving you access to a Virtuozzo system.
But I'll have to discuss this first with my team. ;)

**Comment by legal90** [comment]
@rickard-von-essen Usefull information: 
> Virtuozzo is built on top of OpenVZ technologies but provides more features, services, and support.

https://openvz.org/Virtuozzo
https://openvz.org/Comparison
http://www.odin.com/support/virtualization-suite/pvc/

Me and my team are using Virtuozzo Containers (v6)  for our internal needs. But we don't have an idea to use Packer for it, at least because we run these containers on servers, so we don't use Vagrant there.

@craneworks Could you explain your final goals and what is the usecase you would like to have with Packer + Virtuozzo Containers? 
Is it building Vagrant boxes ("builder" component only), or the full pipeline from creating images to uploading them to the endpoint ("build" + "post-processor" components)?

**Comment by elyzov** [comment]
@legal90 I can not figure out how you may create vagrant box from virtuozzo container, could you explain, please?

**Comment by legal90** [comment]
@elyzov I did not mean that we do that. It's not possible for now because there is no appropriate Packer driver for that. 

P.s. I'm also not sure that it's possible to manage Virtuozzo containers with Vagrant so far. Probably, [vagrant-openvz](https://github.com/abrooke/vagrant-openvz) provider can be used for that, but I never tried it.

**Comment by mwhooker** [comment]
I think we'd be happy to merge in a PR for this, but we'd want the creator to accept responsibility for maintaining it. We'd also need a test environment we could have access to to support it.

In the meantime, this would probably be best as a third party plugin
