### ISSUE TITLE
skip_clean_client not being obeyed for chef-client provisioner

### ISSUE THREAD

**Issue by chainlink** [mitchellh/packer#2738]
The staging directory is being removed even with ```skip_client_clean: true```

**Comment by cbednarski** [comment]
Thanks for the report. I think this is working as designed.. The staging directory is a `/tmp/packer-something` folder. The two options `skip_client_clean` and `skip_node_clean` correspond to the following commands:

```
knife client delete <node>
knife node delete <node>
```

My recollection is that knife copies the data under `/var/lib/chef` or similar when it does the node setup so those are the paths affected but the `skip_*_clean` options above. There is not an option to skip removing the staging dir, but it would be removed anyway when the machine is restarted since `/tmp` is typically cleared out at that time.
