### ISSUE TITLE
winrm using virtualbox

### ISSUE THREAD

**Issue by chlsmith** [mitchellh/packer#2741]
I'm using build-virtualbox-iso and no matter what I put in my config file for the winrm port, it seems like the builder is picking a random number and using it.   One, it was 2271.   This time, it's 3496.    

Ideas???   I'm using Matt Wrock's work to make this happen, but after digging through all of his scripts, it looks to me like this is something specific to using the virtualbox-iso file.

Thanks!

![2015-09-14 11_51_47-new notification](https://cloud.githubusercontent.com/assets/10780098/9854481/05db991c-5ad7-11e5-8552-5f6e69461225.png)

**Comment by rickard-von-essen** [comment]
Don't attach pictures of text :-1: ..

Gist [log](http://packer.io/docs/other/debugging.html) and your complete config.

**Comment by chlsmith** [comment]
I would've pasted in the text log file, but it complained at me.

**Comment by chlsmith** [comment]
Hope this works.  

https://gist.github.com/07d3cb93a42c594cad62.git

**Comment by chlsmith** [comment]
Try this.   Never used Gist before.   

https://gist.github.com/chlsmith/e93e17ec66a194060405

**Comment by rickard-von-essen** [comment]
From the log, line 141-144 is a bit dubious:
```
2015/09/14 11:43:41 packer-builder-virtualbox-iso.exe: 2015/09/14 11:43:41 Looking for available SSH port between 2222 and 4444
2015/09/14 11:43:41 packer-builder-virtualbox-iso.exe: 2015/09/14 11:43:41 Trying port: 3496
2015/09/14 11:43:41 ui: ==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 3496)
2015/09/14 11:43:41 packer-builder-virtualbox-iso.exe: 2015/09/14 11:43:41 Executing VBoxManage: []string{"modifyvm", "packer-virtualbox-iso-1442245398", "--natpf1", "packerssh,tcp,127.0.0.1,3496,,55985"}
```

Even it talks about SSH it does actually portforwards the _communicator_ in this case _winrm_. So packer sets up port forwarding automatically from a random free port, in this case 3496 to the communicator port on the guest, in this case you specified it as 55985 (line 17, in your template json). But I guess in reality the Windows guest is running WinRM on the default port 5985.

I guess it works if you delete line 5 and 17 from your template json file.

If not gist you floppy-files too so I can test it.

**Comment by chlsmith** [comment]
My understanding is that this winrm port forwarding is required to make it
work.    When the build completes and I'm logged into the VM that's spun
up, I can open powershell on the host machine and do "enter-pssession" to
the forwarded winrm port (55985 in our case) and it works just fine.   So
WinRM is working, and the port forwarding is working, too.

I definitely can't remove the WinRM port part, because that would then have
it listen on 5585, which would conflict with my host PC.  Heck, this thing
shouldn't be doing anything with SSH to begin with, as it's Windows and I
tell it to use the winrm communicator.

On Mon, Sep 14, 2015 at 2:38 PM, Rickard von Essen <notifications@github.com

**Comment by rickard-von-essen** [comment]
You don't need WinRM port forwarding. 

It works for you since you connect to localhost:55985 which is forwarded to guest:5985. This works since the custom port forwarding you added. If you remove ```"winrm_port": "55985",``` it will default to 5985 which is where WinRM is running, and it's not conflicting with your machine since they are on different interfaces (try ```ipconfig``` on the host while running the build).

And it doesn't do anything with SSH even the messages says so, it's just legacy from the time when the only communicator was SSH. If you substitute SSH with WinRM in the log messages it is more accurate.

To conclude my previous suggestions still seems like it should solve your issue.
> I guess it works if you delete line 5 and 17 from your template json file.

**Comment by rickard-von-essen** [comment]
I created a new issue to fix the log messages, see #2743

**Comment by pecigonzalo** [comment]
If you leave it running it works?

To answer your question about the port:
Its picking a random port to do the port NAT between your HOST, and the virtualbox machine(GUEST).
When using Virtualbox, the GUEST is not sitting on the same network as your HOST, but rather its in its own network and uses virtualbox as a NAT.

To refer to the machine ports, you can use a NAT where Virtualbox will listen on a port on your HOST machine and fw the communication to a port in the internal machine.
EG: HOST:3496 to GUEST:55985

The winrm_port parameter on the json refers to the GUEST winrm port. Packer then will map a random not currently utilized port from your HOST to it and try to communicate over it. 55985 is not a valid winrm_host in the GUEST unless you have configured it on your anwerfile/init script.

In other builders, EG: VMWare the machine being built does sit on a network you can reach directly, and the NAT is not needed.

As @rickard-von-essen pointed out the log message is wrong because packer is reusing the port forwarding code of ssh, so messages output that but its just a text issue.

**Comment by mwhooker** [comment]
looks like this was a misunderstanding. please open a new issue if I'm wrong
