### ISSUE TITLE
 provisioner/shell: remove file after exec failed : need to not stop building process

### ISSUE THREAD

**Issue by roumano** [mitchellh/packer#2803]
Hi,
We have a issue with the packer version 0.8.x
since it's was add this new function 
 provisioner/shell: remove file after exec [GH-1536] #2259

The idea is good, but in some case it's can be disturbing & annoying, for exemple for us, we use packer to create AMI from public AMI from RHEL,CentOS, OEL

we need to connect with these user
CentOS6,  CentOS7 == centos
Debian == admin
OEL6 , RHEL6 , RHEL7 == ec2-user

Our last task to build AMI is to remove this user but 
after the delete of the user (userdel ... ) 
we can't connect anymore (to delete the temporary script ) on the machine & the build is stopped as packer detect a issue & it's not build the AMI
- Can you add a possibility to not remove file after exec
- Or even better a possibility to not stop the building process as it's not a important issue if a script file is still on /temp.

**Comment by kikitux** [comment]
@roumano Can you share a shell provisioner block on how you are doing this?
You can run scripts inline, those shouldn't upload/delete a helper script.

**Comment by rickard-von-essen** [comment]
@kikitux glancing at the code it sure looks like in line scripts do create/upload/delete a helper script. See
 https://github.com/mitchellh/packer/blob/master/provisioner/shell/provisioner.go#L176

**Comment by Poil** [comment]
+1

**Comment by dave2** [comment]
Managing users on the target is fine if it can reliably destroy all of it's access. However, it's probably much more general to just allow a "noclean" option that doesn't bother at all with cleaning up after itself.

This is currently blocking building AMIs for me - I don't need key auth or the packer user hanging around since we join servers to FreeIPA that we intend to persist. (Short lived, auto-scaling, etc are not expected to be joined but are built off different AMIs.)

**Comment by mwhooker** [comment]
reasonable workaround is available in #2942
