### ISSUE TITLE
Support for GoPkg.in?

### ISSUE THREAD

**Issue by Miserlou** [mitchellh/packer#2821]
Since 0.7.6 introduced a change incompatible with 0.7.5, a downstream plugin I'm using is broken. This goes against the "stable HEAD" philosophy of Go package versioning - but is there any chance you'd consider using GoPkg.in for publishing Packer tags so I could have something consistent to point plugin dependencies at?

**Comment by cbednarski** [comment]
@Miserlou Thanks for opening an issue. The more common request we get is for use godep, which I think would help resolve this issue to some extent, since you could continue building 0.7.5 forever. Since packer is not a library I don't think gopkg.in is going to help much. You could simply check out the tag to build but our upstreams are likely to have drifted in the mean time.

We currently do not have plans to vendor dependencies with godep. I think there are some nice characteristics but it's also an extremely heavy-handed tool and causes a lot of workflow problems for us. Terraform releases typically snapshot the current godep versions at the time of release. If this would help solve your use case we can add this to our packer release process.
