### ISSUE TITLE
parallels-iso fails with "Could not detect Parallels Desktop! Make sure it is properly installed."

### ISSUE THREAD

**Issue by pcastellazzi** [mitchellh/packer#2836]
Running `packer build centos7.json` fails with `Could not detect Parallels Desktop! Make sure it is properly installed.`

You could find a debug log at: https://gist.github.com/pcastellazzi/17676409dab6c8e25c38

I traced the problem to this command: `mdfind "kMDItemCFBundleIdentifier == com.parallels.desktop.console"` which outputs nothing.

**Comment by pcastellazzi** [comment]
It was fixed with a Parallels Desktop reinstall. After the reinstall the correct metadata was found on /Applications/Parallels Desktop.app. I found this problem after the upgrade from 10 to 11. May be it was a problem with my system, or a problem with the updater, i can't say for sure.

**Comment by rickard-von-essen** [comment]
FYI: @legal90

**Comment by legal90** [comment]
Wow, I've run the same issue by the same scenario. My machine have lost `com.parallels.desktop.console` package identifier right after PD 10 -> 11 upgrade.
I'll try to catch it again and will report to the responsible people at Parallels.

@pcastellazzi Thanks for pointing on this!

**Comment by legal90** [comment]
Seems like this problem has been caused by OS X updates, but not Parallels Desktop updates. I've run into this issue after installing system updates, but without updating the Parallels Desktop.
It most likely related to the `Launch Services` API of OS X, so there is nothing to do on the Parallels Desktop side.

In that concrete situation we can try to minimize the annoyance of such issues by adding a workaround.
Let's add one more step here: https://github.com/mitchellh/packer/blob/f01956405bf2a263d6f8d86f97f6339f39a036a0/builder/parallels/common/driver_9.go#L97

If `mdfind` output is empty, then check whether `"/Applications/Parallels Desktop.app"` path exists or not. If it exists - just use it. Otherwise - return the error.
Actually, this path is differ only for those, who have installed Parallels Desktop via homebrew or moved/renamed the bundle manually.

@rickard-von-essen What do you think about it?

**Comment by rickard-von-essen** [comment]
@legal90 yes that sounds good. Will you do a PR? otherwise I can fixe it later today.

**Comment by legal90** [comment]
> I can fixe it later today

It would be great! I'm pretty busy today, sorry :(
