### ISSUE TITLE
Salt problems

### ISSUE THREAD

**Issue by ariscn** [mitchellh/packer#2847]
When using salt-masterless, a `/etc/salt/minion_id` artifact is left on the filesystem. It's easy to remove this file manually, but this seems like something that should happen in the provisioner.

`/etc/salt/pki` is also created, I _think_ this directory should also be blown away, but I'm less certain about this.

Finally, at the beginning of provisioning salt-masterless blows away the remote state and pillar directories if they exist. This can be unwanted behavior, and probably shouldn't be the default.

**Comment by cbednarski** [comment]
@ariscn Thanks for the report! Since I don't know salt I don't know what the expected / intended behavior is here. For the time being I don't want to make any backwards-incompatible changes which might break existing builds. I will leave this issue open for further feedback.

**Comment by ariscn** [comment]
I think this is largely up to Packer's judgment, because machine images are outside the scope of Salt generally.

It seems reasonable to expect salt-masterless (and all Packer provisioners?) to clean up after itself. I can't think of any circumstances where someone wants to start an instance from an AMI and have it pre-populated with any data (instance ID, IP address) relating to the instance used to build the AMI.

**Comment by cbednarski** [comment]
> It seems reasonable to expect salt-masterless (and all Packer provisioners?) to clean up after itself. I can't think of any circumstances where someone wants to start an instance from an AMI and have it pre-populated with any data (instance ID, IP address) relating to the instance used to build the AMI.

Yeah, that makes sense. I think it's likely we can safely remove `/etc/salt/minion_id` and `/etc/salt/pki`, though I will need to double-check. I am curious why `/etc/salt/minion_id` shows up using `salt-masterless`, though. That seems out of place.

> Finally, at the beginning of provisioning salt-masterless blows away the remote state and pillar directories if they exist. This can be unwanted behavior, and probably shouldn't be the default.

This would be a breaking change with unspecified side effects. I recall discussing this before and IIRC the rationale for cleaning up _before hand_ is that packer can't control the build process if there are drifting / unknown scripts in the base image. The base image should be blank and/or the packer template should provide complete provisioning scripts for the build.

We might be able to provide an option to tweak this behavior, but changing the default for this is likely to result in broken builds.

**Comment by mafrosis** [comment]
I had a little think about this on the weekend. Salt can be used in "masterless" mode, where it will run scripts from the local filesystem, against the current machine. Or it can run in normal mode, where it will connect to a salt-master process (typically on another server) and retrieve the provisioning config from there.

The decision to clean up or not comes down to one thing: should the resulting image have a working `salt-minion` installed?

- Removing `/etc/salt/minion_id` will have no impact on a working `salt-minion` in the resulting image (it will be regenerated from the FQDN or IP).
- Removing `/etc/salt/pki` will be a problem if the machine image has been configured to talk to a salt-master server, since encryption keys for the communications will be removed.

**Comment by mwhooker** [comment]
Going to leave this as-is for now.
