### ISSUE TITLE
Change amazon-instance builder to use ec2-bundle-instance command

### ISSUE THREAD

**Issue by grahamc** [mitchellh/packer#2858]
re #517: just over 2 years later, x509 certs are thoroughly deprecated and the access keys are definitely supported now.

Ref: https://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-BundleInstance.html

**Comment by cbednarski** [comment]
Thanks for the suggestion. We support access key id and access key secret via https://github.com/aws/aws-sdk-go so I'm not sure there's anything to change here? If I misunderstood please let me know.

**Comment by grahamc** [comment]
Hi, Yes. Sorry - I thought I had attached more detail here. The instance builder is still expecting a key / cert: https://github.com/mitchellh/packer/blob/024132a698092b0d950d0aaffdb8821616de6a72/builder/amazon/instance/builder.go#L100-L111

**Comment by cbednarski** [comment]
It looks like we need to change this to use `ec2-bundle-instance` instead of `ec2-bundle-vol`.

**Comment by tracyde** [comment]
[ec2-bundle-instance](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-BundleInstance.html) is to create Windows images, ec2-bundle-vol is still used for Linux.

**Comment by joestump** [comment]
Any updates on this? We have zero need for EBS-backed instances & would really love to bundle with Packer.

**Comment by grahamc** [comment]
I switched to using the NixOS.org support for building AMIs decoratively, I never got this working.

**Comment by mwhooker** [comment]
I haven't investigated this too thoroughly, but it looks like you still need to use ec2-bundle-vol even if you're running on instance-store:

* http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-instance-store.html
* http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/create-instance-store-ami.html#amazon_linux_instructions

and that ec2-bundle-instance is only for windows: http://docs.aws.amazon.com/cli/latest/reference/ec2/bundle-instance.html

I'd be happy to take a look at any PR that supports ec2-bundle-instance in addition to bundle-vol, but for now, though, since this not something we're targeting for 1.0, I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by joestump** [comment]
@mwhooker if I get a chance I'll take a look. Probably won't come up until the boss gets grumpy about the EBS bills.
