### ISSUE TITLE
How to continue from next step?

### ISSUE THREAD

**Issue by vvchik** [mitchellh/packer#2871]
For example I making build and have some artifacts as result.
and want to provision and make vagrant box after it.
but provision fall, because of my error in provision script, or few errors.
creation of windows box can take 4-8 hours. (depends on configuration and number of updates to install)

so in case of error I have to start from beginning again and again.

How to avoid it, how to append existing artifact and continue after error fix?

**Comment by cbednarski** [comment]
@vvchik The best results I've had here are using the `vmware-vmx` builder (there may be another way to do this with virtual box but I have not tried it).

Basically you will have several packer templates. One will perform the base OS install. The next will do updates. The third will provision your software on top of the updated OS.

This is a bit more work because you have to run three builds, but as you noted it also allows you to snapshot periodically.
