### ISSUE TITLE
Vagrant catalog file

### ISSUE THREAD

**Issue by janwalther** [mitchellh/packer#2888]
I really like Packer to create vagrant boxes. But one last manual step stays in our virtualization workflow: When we change the packer template and build a new box, the users of the vagrant box do not get notified that there is a new version.
Is there a way to create a vagrant catalog file (e.g. with a packer post-processor)? The version number could be generated from the date when the box is created: e.g. 2015.10.30 - then vagrant could recognize the new version.

**Comment by cbednarski** [comment]
@janwalther Thanks for opening an issue. Packer does not generate this file automatically but you can do so yourself with a script. The reason packer doesn't generate it is because it does not have enough information, such as where the box will be stored or what other versions exist.

Fortunately the format is pretty simple JSON. The specification for this is documented [in the Vagrant docs](https://docs.vagrantup.com/v2/boxes/format.html), under the "BOX METADATA" heading.

Also, if you use [Atlas](https://atlas.hashicorp.com) to build your vagrant boxes Atlas can do this versioning for you.
