### ISSUE TITLE
Raspberry pi builder

### ISSUE THREAD

**Issue by ang-st** [mitchellh/packer#2922]
Hello,

I have just came around your project, and would find interressant to have a raspberry pi image builder ( for raspbian, arch linux ...

A bit of poking around the net brought me on : http://www.kmp.or.at/~klaus/raspberry/build_rpi_sd_card.sh 

Based on this,  would you think   gluing a builder would be  doable  ?

In such case, may you suggest a "least resistance path" to implement it ?
I would be glad to give a shot ...

**Comment by cbednarski** [comment]
@ang-st This is a pretty interesting idea and I have this use-case myself. I've written a [few](https://github.com/cbednarski/ubuntu-usb-osx) [scripts](https://github.com/cbednarski/vmware-usb-osx) to bootstrap USB sticks. I'm not sure this is the best fit with packer, though. It would be particularly difficult for us to test and maintain it, for example.

Packer's focus is on performing unattended installs and automated building of machine images. In the SD card case you actually have to be present at the system in question to build the image, and we also have to solve for the cross-platform case which is pretty messy (since it involves hardware drivers and such), so I think this doesn't really fit with packer's overall design goals.

On the other hand, if you want to use packer to build the boot iso (and potentially use a different tool to image the SD card after packer has built it) I think this would make sense for packer.

All that said, don't let any of this stop you from building this for yourself. I would probably use this, even if it's not a good fit as a packer core plugin.

**Comment by tylert** [comment]
@ang-st Hmm... interesting... I've had some luck using the qemu builder to make bootable USB images for x86_32/x86_64 on x86_64 but there might be something in there that could help you get started (https://github.com/tylert/packer-build/blob/master/README.rst#making-bootable-usb-drives).

**Comment by fr34k8** [comment]
could the packer tcg help here ?

**Comment by cescoferraro** [comment]
This would be awesome!

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by yuval-k** [comment]
hot off the press: https://github.com/solo-io/packer-builder-arm-image

**Comment by rickard-von-essen** [comment]
@mwhooker maybe we should have a list of 3pp plugins on https://www.packer.io/community-tools.html ?
