### ISSUE TITLE
Feature Request: Add CLI option to export parsed template JSON

### ISSUE THREAD

**Issue by techjacker** [mitchellh/packer#2976]
I like using variables to DRY up my template but this makes it difficult for other services to consumer the template eg virtualbox.

It would be nice to be able export a version of the JSON that has been interpolated through the CLI.

**Comment by cbednarski** [comment]
Can you describe what you're trying to do? In many places the variable interpolation is contingent on packer's internal state during the build or post-processing phase so we can't render these. Rather, the variables are interpolated in memory in the context of an in-process build.

**Comment by techjacker** [comment]
I'd like to use the packer template JSON in my Vagrantfile which I use to provision boxes for developing and testing chef cookbooks locally.

I'm having to hardcode a couple of properties because they contain variables.

If you think it's possible and accept PRs then I'd be happy to work on this feature.

**Comment by mwhooker** [comment]
I don't think this is something we'd like to add to packer core. Our recommendation for this kind of thing is to use a separate tool to move data from a central place into formats needed by different processes. This is because we don't want packer to do too many things (part of the [tao](https://www.hashicorp.com/blog/tao-of-hashicorp.html)). I vote no for those reasons, but willing to hear other arguments
