### ISSUE TITLE
vmware-vmx: HTTPIP and HTTPPort are empty in vmx_data

### ISSUE THREAD

**Issue by gevans** [mitchellh/packer#2978]
I'm using Packer to customize one of CoreOS's prebuild VMX/VMDKs. CoreOS has the ability to fetch its config by reading `guestinfo.coreos.config.url` from its VMX. The issue is, setting this in `vmx_data` to something like `http://{{.HTTPIP}}:{{.HTTPPort}}/cloud-config.yml` results in `http://<no value>:<no value>/cloud-config.yml`.

I believe this is because the [HTTP server is started later in the process](https://github.com/mitchellh/packer/blob/v0.8.6/builder/vmware/vmx/builder.go#L75-L79). Is it possible to move this *before* the [VMX configuration step](https://github.com/mitchellh/packer/blob/v0.8.6/builder/vmware/vmx/builder.go#L71-L73)?

**Comment by rickard-von-essen** [comment]
No, it's not possible the IP is assigned by dhcp from VMware when the VM boots and thus unknown at VM creation.

**Comment by rickard-von-essen** [comment]
But you can as easily do:

```json
"boot_command": "sudo /usr/bin/coreos-cloud-init --from-url=http://{{.HTTPIP}}:{{.HTTPPort}}/cloud-config.yml
```

**Comment by gevans** [comment]
I'm not sure what you mean by impossible. I modified the `builder/vmware/common` package in my own fork and didn't have any trouble acquiring the host IP before booting. Since Packer always operates on vmnet8, wouldn't the interface always be up?

I'd have passed this as a boot command but the CoreOS VMs don't work like the live CD. :cry: Going this route means I'd have to set a really short boot timeout to interrupt Grub, add `coreos.autologin` to the kernel command line, wait for the machine to *actually* boot, then do the coreos-cloudinit dance. That's not an ideal solution...

**Comment by cbednarski** [comment]
Not sure what you're trying to do, so these suggestions may not help much.

You suggested moving the HTTP server earlier in the process. This might be as simple as moving [builder.go#L75-L79](https://github.com/mitchellh/packer/blob/v0.8.6/builder/vmware/vmx/builder.go#L75-L79) to [builder.go#L70](https://github.com/mitchellh/packer/blob/v0.8.6/builder/vmware/vmx/builder.go#L70).

> I modified the builder/vmware/common package in my own fork and didn't have any trouble acquiring the host IP before booting. Since Packer always operates on vmnet8, wouldn't the interface always be up?

Writing the IP into the VMX data potentially causes conflicts with concurrent builds and/or problems post-build when the VM is moved to another machine. The interface in question is the interface internal to the VM, which is not present until boot time, rather than the vmnet network on the host. The vmnet behavior is undocumented and our current implementation is based on reverse engineering and testing so it's not trivial to tweak stuff there.

As an alternative strategy, you could mount the vmdk into another VM running a normal linux OS where you can treat it as a dumb block device and do whatever you want outside the constraints of the CoreOS boot procedure.

**Comment by gevans** [comment]
Thanks for clearing things up for me. I didn't know that was the status on VMWare's networking. In that case, there isn't much that can be done there.

Mounting the vmdk into another VM is something I hadn't thought of. I might have to give that a try instead. The workaround I ended up going with for now was to publish a minimal cloud config as a Gist with just enough to get Packer access over SSH.
