### ISSUE TITLE
packer --version and packer --help set the error code to 1

### ISSUE THREAD

**Issue by fermaem** [mitchellh/packer#2998]
```bash
$ echo $?
0
$ packer --version
0.8.6
$ echo $?
1
```

The behavior is the same the `--help`.

Is that expected? We're relying on `--version` in our Travis build and having setting the error code... well... fails our build. :crying_cat_face:

**Comment by cbednarski** [comment]
Thanks for opening an issue. The reason these exit 1 is because there is no command specified.

A hack I use to get around this problem in general is `cmd || true` so for example `packer --version || true`. Also there is a `packer version` command which exits with code 0. The output from `packer version` is a bit more verbose so you might need to `awk` it.

**Comment by fermaem** [comment]
>Also there is a packer version command which exits with code 0. 

@cbednarski Awesome feedback! :heart:

/cc @monythi
