### ISSUE TITLE
Packer Doesn't Restart QEMU Guest for Provisioners Step

### ISSUE THREAD

**Issue by bnied** [mitchellh/packer#3012]
Environment:

    [bnied@luna ~/C/packer] $ uname -a
    Linux luna.local 4.2.7-300.fc23.x86_64 #1 SMP Wed Dec 9 22:28:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    [bnied@luna ~/C/packer] $ packerio version
    Packer v0.8.6

Provisioning a qemu guest works fine for the initial install; guest comes up, gets the kickstart, etc. Once the kickstart finishes, however, and the guest shuts off, Packer doesn't start it back up for the `provisioners` step.

**Comment by cbednarski** [comment]
Thanks for opening an issue, and sorry for the delayed response. I think this should be handled by the VM using a restart command rather than a shutdown command. If your kickstart sends a shutdown signal at some point the VM will be powered off. Packer doesn't do anything about this -- you'll need to use restart instead of shutdown for provisioning.
