### ISSUE TITLE
Feature Request: add user-data support to OpenStack Builder

### ISSUE THREAD

**Issue by dmourati** [mitchellh/packer#3018]
The amazon-ebs builder supports two really nifty options: user_data, and user_data_file. Extending this support to the OpenStack builder would enable a streamlined workflow driven all by Packer. Nova natively supports the option:

nova boot --image ubuntu-cloudimage --flavor 1 --user-data mydata.file

Thanks for the OpenStack builder!

**Comment by rickard-von-essen** [comment]
This feature is already available since v0.8.0 (see b3a97124), but unfortunately the docs where not updated to reflect this. The docs have been updated and will be available at the site at next release. In the mean time you can view them at [Docs - OpenStack](https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/openstack.html.markdown).

**Comment by dmourati** [comment]
Thanks for the update!
