### ISSUE TITLE
 Not found link in documentation

### ISSUE THREAD

**Issue by edamov** [mitchellh/packer#3075]
On the page [PACKER AND THE HASHICORP ECOSYSTEM](https://www.packer.io/intro/hashicorp-ecosystem.html) the link [The Atlas Mindset: Version Control for Infrastructure](https://www.hashicorp.com/blog/atlas-mindset.html/?utm_source=packer&utm_campaign=HashicorpEcosystem) is not working (404 Not Found)

**Comment by cbednarski** [comment]
Thanks for the report. There was an extra `/` in the URL. This is fixed in master but the website will be out of date until we push the next release. You can visit [https://www.hashicorp.com/blog/atlas-mindset.html?utm_source=packer&utm_campaign=HashicorpEcosystem](https://www.hashicorp.com/blog/atlas-mindset.html) in the mean time.
