### ISSUE TITLE
Linode Builder for Packer

### ISSUE THREAD

**Issue by wduncanfraser** [mitchellh/packer#3131]
Linode is a very large VPS/Cloud "Lite" provider, and it would be useful to have the ability to create base images using packer. There was a previous issue for a Linode builder that has since been closed which can be found here: https://github.com/mitchellh/packer/issues/174. It looks like the original issue was that Linode did not have real method for snapshotting nodes and keeping images for later use, that is no longer the case.

Linode now has the Images feature, which allows for snapshotting a node into a master image, which can then be used to later deploy another node. Documentation for Images can be found here: https://www.linode.com/docs/platform/linode-images.

Images also has API functionality which is documented here: https://www.linode.com/api/image.

[linode.disk.imagize()](https://www.linode.com/api/linode/linode.disk.imagize) allows you to create an image out of an existing node.
[linode.disk.createfromimage()](https://www.linode.com/api/linode/linode.disk.createfromimage) allows you to create a node from an existing image.

Additionally, it looks like there is an existing Vagrant provider plugin for Linode: https://github.com/displague/vagrant-linode.

**Comment by devinrsmith** [comment]
+1

**Comment by mwhooker** [comment]
Will be happy to look at any PRs that come in for this, but this is not something we're targeting for 1.0, so I'm going to close the issue. We rely on the community to support new builders, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Comment by dradtke** [comment]
Apologies if this is the wrong place for this, but for anyone who stumbles across this issue, I just finished a simple Linode builder for Packer: https://github.com/dradtke/packer-builder-linode. It's not very polished, and you have to build it from within Packer's source tree due to vendoring issues, but otherwise it seems to work well enough.

Is Packer's plugin strategy to try and incorporate as many as possible into Packer's source directly, or to maintain a list of third-party plugins in the README?
