### ISSUE TITLE
ami-72b9e018 from "Build an Image" instructions has been deregistered

### ISSUE THREAD

**Issue by yaron-idan** [mitchellh/packer#3132]
Can you update the documentation with a more relevant AMI?
I've used this AMI - ami-b1c6ebdb, but it seems these images are being updated daily and maybe you should create an AMI of your own that would not be deregistered in the near future.
Thanks,
Yaron.

**Comment by justintilson** [comment]
+1 I ran into this problem last night too.

**Comment by cbednarski** [comment]
Can you link to where this AMI is referenced?

**Comment by justintilson** [comment]
Here: https://www.packer.io/intro/getting-started/build-image.html under: 'The Template'

**Comment by sheerun** [comment]
Also, tutorial doesn't work anyway, because t1 instances need vpc to work. The ami of `ami-b2e3c6d8` and instance type `m1.small` worked for, but mind this instance type is not a free tier one.

So you either need change instance type to `m1.small` and remove information that it is fee, or add vpc configuration to example.

**Comment by dave2** [comment]
I believe this has all been fixed in this merged PR: #3066 

If not, I can do a PR which fixes any that I missed.

**Comment by chainlink** [comment]
Definitely playing wack a mole with AMI ID's (since they are different by region) Maybe a quick paragraph on how to find a valid one? (ie. In the AWS console, launch instance > ubuntu HVM) I realize it's not ideal, but potentially less brittle than the current solution.

**Comment by cbednarski** [comment]
> Also, tutorial doesn't work anyway, because t1 instances need vpc to work.

That's a bummer. VPC setup is kinda a pain.

@dave2 I think that might have been a nightly. I was curious whether it would disappear and this answers my question. :) I think [these](http://uec-images.ubuntu.com/releases/14.04/release/) are more stable since they're LTS images.

@chainlink Great idea.

Thanks for the feedback, folks. If someone wants to take a stab at a PR I'd be happy to review!

**Comment by rickhull** [comment]
This page is still referencing ami-72b9e018

https://www.packer.io/intro/getting-started/build-image.html

It's really bad to give an example, tell the user to copy/paste it, and have it not be "valid".

```
We'll start by creating the entire template, then we'll go over each section briefly. Create a file example.json and fill it with the following contents:

{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "source_ami": "ami-72b9e018",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-example {{timestamp}}"
  }]
}
When building, you'll pass in the aws_access_key and aws_secret_key as a user variable, keeping your secret keys out of the template. You can create security credentials on this page. An example IAM policy document can be found in the Amazon EC2 builder docs.
```

**Comment by aarcro** [comment]
ami-d05e75b8 is ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20150325 And worked for me.

**Comment by mwhooker** [comment]
this has been updated to `ami-fce3c696`
