### ISSUE TITLE
Packer crash when using amazon-ebs builder

### ISSUE THREAD

**Issue by dougalb** [mitchellh/packer#3136]
I am building packer from source to get updates for new regions and ephemeral device un-mapping. My build on MacOSX has no issues but my build on Amazon Linux is crashing when I build. 

The `make testacc TEST=./builder/amazon/ebs` passes with no issues.

The packer json is here - https://github.com/awslabs/cfncluster-cookbook/blob/develop/packer_alinux.json

Crash log here - https://gist.github.com/dougalb/4e03ebf747446cf1dff2

**Comment by dougalb** [comment]
Looks like an issue with the subnet to AZ mapping.

```
2016/02/01 04:50:05 packer: 2016/02/01 04:50:05 [INFO] Finding AZ for the given subnet 'subnet-c06054b4'
2016/02/01 04:50:05 packer: panic: runtime error: invalid memory address or nil pointer dereference
2016/02/01 04:50:05 packer: [signal 0xb code=0x1 addr=0x0 pc=0xcc86b5]
```

**Comment by dougalb** [comment]
It looks like an issue with using an EC2 IAM role vs access keys. If I set the AWS_ACCESS_* variables, packer does not crash. 

EC2 IAM role was working with the 0.8.6 binary install versus the github dev build.

**Comment by ThatGerber** [comment]
I experienced a similar problem. I traced it to here.: https://github.com/mitchellh/packer/blob/master/builder/amazon/common/access_config.go#L27

The Credential chain is unable to get credentials through the first three methods and is falling back to try and pull them from the EC2 instance metadata, but you're not on an EC2 instance. I believe it's trying to return an error from https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/ec2rolecreds/ec2_role_provider.go#L88 but that error is uncaught and causing it to panic A check should be made to ensure that Packer is being run on an EC2 instance before it tries to pull the credentials from the instance IAM role and failures should be caught and returned.

**Comment by dougalb** [comment]
I am running on an EC2 instance with a valid EC2 IAM role associated. I
recently moved from 0.8.6 binary release to building from source and it
fails to pick up the credentials.

**Comment by ajfitzpatrick** [comment]
I've worked around this crash by replacing [`&EC2RoleProvider{}`](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/access_config.go#L53) with `&EC2RoleProvider{ Client: ec2metadata.New(session.New() }`, since in the SDK where EC2RoleProviders are created (in [defaults.CredChain](https://github.com/aws/aws-sdk-go/blob/master/aws/defaults/defaults.go#L91-L94) and [ec2rolecreds.NewCredentials](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/ec2rolecreds/ec2_role_provider.go#L59-L61)), they're given an EC2Metadata client.

I don't know whether using `session.New()` as the ConfigProvider is an appropriate fix, though.

**Comment by mwhooker** [comment]
Having trouble reproducing this. There've been many changes around this so I'd be surprised if it were still an issue. If someone can produce with a current build of packer, please open a new issue with how to reproduce and I'll gladly work to solve
