### ISSUE TITLE
ISO in the local packer_cache doesn't get removed if it has a bad checksum

### ISSUE THREAD

**Issue by dragon788** [mitchellh/packer#3155]
I frequently work with ISOs on a server that have a static name but may have their checksums change. I update my template to use the new checksum, but if I've built from a prior version of the ISO Packer warns me the local ISO doesn't match the checksum, but it doesn't purge it and attempt to redownload. This is frustrating as the expected behavior would be to invalidate the local cache and check with the server for a "correct" version (if defined) and only if all iso sources were exhausted to then throw a failure.

**Comment by cbednarski** [comment]
Thanks for the report! Can you share a snippet of your template so I can see how you're configuring the remote URL?  Also, what error message are you getting?

To clarify the expected behavior here: If the specified file is local and we have not made a copy we will not delete the file. This is to prevent data loss e.g. when the source ISO is on a networked drive.

If the file is available over HTTP we _should_ try to purge and download again. There's quite a bit of test coverage here so if you can identify which scenario is failing it should be easy to fix / add a test to cover it.

**Comment by dragon788** [comment]
I'm using a lightly customized variables file with a lightly customized template file based on https://github.com/boxcutter/ubuntu, see https://github.com/boxcutter/ubuntu/blob/master/ubuntu1404.json and https://github.com/boxcutter/ubuntu/blob/master/ubuntu.json#L216 .

It is supposed to look first in the local path I believe, and then go hit the server if it can't find it locally. We aren't using the local path for this particular case because of the frequently changing ISO contents, but once Packer has grabbed the ISO from the HTTP url, it assumes it is the golden master and never replaces it even when the SHA1 of the ISO has changed in our variables file or the base template.

**Comment by cbednarski** [comment]
Thanks for the example. This will help me repro.

**Comment by mwhooker** [comment]
Can you please verify that this is still an issue? Packer now stores the ISOs under `packer_cache/<shasum>.iso`, and I don't think it saves the ISO names any more

**Comment by mwhooker** [comment]
Going to close this for now. Please re-open or submit a new ticket if this is still an issue
