### ISSUE TITLE
id attribute for headers in website

### ISSUE THREAD

**Issue by artburkart** [mitchellh/packer#3163]
I know the website is generated using pandoc, so I'm unsure whether my request is possible, but it would be really nice if I could link people to exact locations within the docs. For example, if I wanted to explain to someone how the automatic credential lookup works for AWS in packer, I could send them to this page, https://www.packer.io/docs/builders/amazon.html, but it would be even better if I could send them here: https://www.packer.io/docs/builders/amazon.html#automatic_lookup

I did some searching in the issues, but I can't be certain this is not a dupe. 350+ issues is a high mark for due diligence. Cheers!

**Comment by cbednarski** [comment]
Thanks for opening an issue. Pandoc is used to format our markdown source so everything uses a consistent style, but the HTML is generated using [middleman](https://github.com/hashicorp/middleman-hashicorp). I'm not sure why but bullet points have anchors but headings do not.

/cc @sethvargo

**Comment by cbednarski** [comment]
I dug into this earlier and the reason we don't have IDs is because we don't have a way to handle redirects if a heading is changed or to handle duplicates if a heading is reused. Unfortunately this is a lot of work to fix manually. We may fix it later via improved doc tools but for now we will not be fixing this. Thanks!
