### ISSUE TITLE
[post-processor: vsphere]: Truncating ".period" when uploading ovf to vCenter

### ISSUE THREAD

**Issue by NetworkBytes** [mitchellh/packer#3204]
Getting truncation errors with the latest packer (released) build 8.6 when calling ovftools,  
this didn't happen on the previous release of packer 

`
Error: Failed to create directory: "vi://Administrator%40vsphere.local:<#removed#>@<#vcenter removed #>/DC1/host/Cluster1/Resources\3\
`

The Resource pool line seems to be truncating  "3.Bronze" to "3"
will attempt to use hex code "%2E" instead to see if that works 

`
2016/02/14 22:28:24 ui:     vmware-iso (vsphere): Uploading output\Redhat-7.2-x86_64_Template_20160214.2207\Redhat-7.2-x86_64_Template_20160214.2207.vmx to vSphere
2016/02/14 22:28:24 packer.exe: 2016/02/14 22:28:24 Starting ovftool with parameters: --noSSLVerify=true --acceptAllEulas --name="Redhat-7.2-x86_64_Template_20160214.2207" --datastore="Site_1" --diskMode="thin" --network="<#network removed#>" --vmFolder="Templates" output\Redhat-7.2-x86_64_Template_20160214.2207\Redhat-7.2-x86_64_Template_20160214.2207.vmx "vi://Administrator%40vsphere.local:<#removed#>@<#vcenter removed #>/DC1/host/Cluster1/Resources/3.Bronze"
`
* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output\Redhat-7.2-x86_64_Template_20160214.2207\Redhat-7.2-x86_64_Template_20160214.2207.vmx
Opening OVF target: "vi://Administrator%40vsphere.local:<#removed#>@<#vcenter removed #>/DC1/host/Cluster1/Resources/3.Bronze"
Error: Failed to create directory: "vi://Administrator%40vsphere.local:<#removed#>@<#vcenter removed #>/DC1/host/Cluster1/Resources\3\
Completed with errors

**Comment by NetworkBytes** [comment]
I can confirm using "%2E" instead of "." works around the issue, 
this mean there is a parsing bug introduced in the latest release

**Comment by zverocool** [comment]
I am experiencing a similar issue, after upgrading to 0.9.0. It worked in 0.8.6 with no problem
```bash
Build 'CentOS7-282f1663-1552-055' errored: 1 error(s) occurred:


* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output/build-CentOS7-282f1663-1552-055/packer-CentOS7-282f1663-1552-055.vmx
Opening OVF target: "vi://user:pass@esxhost.com/datacenter/host/cluster/Resources/resourcepool"
Writing OVF package: "vi://user:pass@esxhost.com/datacenter/host/cluster/Resources/resourcepool"/"CentOS7-282f1663-1552-055"/"CentOS7-282f1663-1552-055".ovf
Transfer Failed                       
Error: System error: (std::exception)
Deleting directory tree below: "vi:
Completed with errors
```

I am not sure what the issue is, but its probably parsing:  This does not look correct:

> **"/"**CentOS7-282f1663-1552-055**"/"**CentOS7-282f1663-1552-055**"**.ovf

**Comment by mistercaste** [comment]
+1 for this fix

I have successfully created a packer artifact (CentOS-7 via vmware-vmx) and the post processor fails due to the same error.

After the failure (and before packer deleted the temp artifact) I have tried to manually execute:
ovftool --noSSLVerify=true --acceptAllEulas --name=my-template --datastore="VMTier_01" --diskMode=thick --network="VM Network" --vmFolder= output-vmware-vmx\my-template.vmx "vi://<vmware-server>/<vmware-datacenter>/host/<vmware-cluster>"

The output was:

Opening VMX source: output-vmware-vmx\my-template.vmx
Enter login information for target vi://<vmware-server>/
Username: myname
Password: **********
Opening VI target: vi://myname@<vmware-server>:443/<vmware-datacenter>/host/<vmware-cluster>
Deploying to VI: vi://myname@<vmware-server>:443/<vmware-datacenter>/host/<vmware-cluster>
Transfer Completed
Completed successfully

Something is indeed wrong with the post-processor.

**Comment by jalmansor** [comment]
Seeing this as well since updating to 0.9.0.

**Comment by godfryd** [comment]
When do you plan to integrate this PR?
I have another issue #3204 that seems that this PR is fixing it.

**Comment by iamthemuffinman** [comment]
PR #3321 is tagged for the v0.11.0 release.
