### ISSUE TITLE
Metadata not being passed to openstack

### ISSUE THREAD

**Issue by Stono** [mitchellh/packer#3207]
Hi, 
Your documentation says that we support metadata being passed to openstack (https://www.packer.io/docs/builders/openstack.html); however looking at the code - the metadata is never passed:
https://github.com/mitchellh/packer/blob/master/builder/openstack/step_run_source_server.go#L57

Subsequently we're unable to pass our bespoke rackspace configuration data.

**Comment by rickard-von-essen** [comment]
Did you verify that, a quick glance at the code and it looks to me that it is. (But it's hard to read code on a mobile.)

**Comment by bitbier** [comment]
I believe that the metadata is specifically for the image that is created and not for the server that you are trying to run. I've also been looking into this because I need a way to make the image public in our openstack instance.

[Here](https://github.com/mitchellh/packer/issues/2434) is more information about the metadata stuff. The [PR](https://github.com/mitchellh/packer/pull/2460/commits/988cf2fecff95e20933fcd43b3aefb6c6ae14b95) specifically shows the metadata being sent on the image creation.

**Comment by rickard-von-essen** [comment]
Closing this since it works as it should. Metadata is passed to Glance when the image is created. Userdata is passed to the instance when created.
