### ISSUE TITLE
Add flag to avoid or delay file existence check in file provisioner

### ISSUE THREAD

**Issue by jumapico** [mitchellh/packer#3210]
Hi all.
I want to create many symbolic links in the image (systemd customization).
For do that, i choose to create the symbolic links in the host and create a tar file using the shell-local provisioner.
The problem is that the build step fails with the message "* Bad source '/tmp/files.tgz': stat /tmp/files.tgz: no such file or directory".
Maybe a flag that disable the check of the file or delay it until the file need to be copied can help.

Here is a test template with the idea (that currently gives the error mentioned before):
```
{
    "builders": [
        {
            "type": "null",
            "ssh_host": "127.0.0.1",
            "ssh_username": "user",
            "ssh_password": "pass"
        }
    ],
    "provisioners": [
        {
            "type": "shell-local",
            "command": "tar zcvf /tmp/files.tgz -C ./files/ ./"
        },
        {
            "type": "file",
            "source": "/tmp/files.tgz",
            "destination": "/tmp/files.tgz"
        },
        {
            "type": "shell",
            "execute_command": "echo pass | sudo -S sh '{{.Path}}'",
            "inline": "tar xf /tmp/files.tgz -C /"
        }
    ]
}
```

Greetings,
JMPC

**Comment by dave2** [comment]
PR #2877 was raised to implement something like this (not my PR, but I have commented on it)

**Comment by cbednarski** [comment]
Thanks for opening an issue. As @dave2 mentioned, this feature has been suggested already.

As a workaround, the recommended way to create symlinks is to use a provisioner to create them inside the VM, rather than creating them on the host and tarring them. This allows your build template to work even when the host environment changes (e.g. between different OSes or different filesystems).

If you want to copy an entire directory you should already be able to do this using the [file provisioner](https://www.packer.io/docs/provisioners/file.html).

If you need the tar to exist before hand you can create it with a makefile (for example) before packer runs.

**Comment by ashb** [comment]
The docs https://www.packer.io/docs/provisioners/file.html#symbolic-link-uploads are wrong because of this, and I get this error:

```
1 error(s) occurred:

* Bad source './toupload': stat ./toupload: no such file or directory
```

**Comment by rickard-von-essen** [comment]
Hi @ashb , thanks for reaching out. 

This ticket is really old so it's probably not relevant to the issue you're seeing. If you're still having trouble, would you please open a new issue with the debug log and a json that reproduces the issue? Thanks!
