### ISSUE TITLE
Customize linux ISOs with kickstart/preseed file

### ISSUE THREAD

**Issue by techtangents** [mitchellh/packer#3277]
In https://www.packer.io/docs/builders/vmware-iso.html it describes configuring a sequence of keystrokes to start the installer with the required options and load the kickstart/preseed file. This sounds clumsy and error-prone to me.

Wouldn't it be better to get the ISO, unpack it, bake in the kickstart/preseed file (like https://help.ubuntu.com/community/InstallCDCustomization) and boot the VM off that? 

I haven't done this myself, but I would hope that this sort of customized ISO could install the OS with the desired options without any user interaction.

**Comment by kikitux** [comment]
Hello,

The normal process to install an OS like debian based or redhat based is use a response file to installer, and type some information in the console to tell the installer from where grab the iso.

You could update the iso, and tell packer to use that iso, and no boot line will be required.

I believe, having packer to update isos wont be very portable, and decoupling the iso from the response file covers lots of use cases. ie. 1 Iso can be used to many different installs.

Lots of companies use this install approach, since is one of the most common methods of installation.

I will close this ticket for now, however you are very welcome to test this and submit a PR for review if get something working.


Alvaro.

**Comment by techtangents** [comment]
Do you ever get problems with the timing of Packer producing the keystrokes over VPN?
