### ISSUE TITLE
 x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tvlooy** [mitchellh/packer#3289]
I'm following the tutorial and I get an error on the "packer push" step.

Error starting upload: upload: Get https://atlas.hashicorp.com/api/v1/packer/build-config... x509: certificate signed by unknown authority

I'm running packer 0.9.0 on Ubuntu 15.04 64bit.

What's wrong?

**Comment by rickard-von-essen** [comment]
Could you run with ```PACKER_LOG=1 packer build ...``` and gist (at least relevant parts of) the log. 

I'm guessing that you don't have an up to date ssl cert bundle.

**Comment by tvlooy** [comment]
Thanks for your help @rickard-von-essen 

The exact error from PACKER_LOG is

```2016/03/01 21:10:03 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/packer?arch=amd64&os=linux&signature=b753e43e-d6cb-c1a4-cf24-465c9a4d0414&version=0.9.0: x509: certificate signed by unknown authority```

This certificate is from GeoTrust.

Curl, my browsers, etc. do not complain about this certificate. I have OpenSSL 1.0.2d (latest from Ubuntu packages).

What exactly do you mean with the "ssl cert bundle"?

**Comment by cbednarski** [comment]
@tvlooy GeoTrust is the root CA, but as you may notice there are 3 certificates in the chain:

![screen shot 2016-03-01 at 12 35 39 pm](https://cloud.githubusercontent.com/assets/649798/13441105/7e8e6576-dfaa-11e5-8810-477ae7a24e44.png)

Typically the root CA public certificate is included in your OS. On ubuntu this is `/etc/ssl/certs`, which you can see by making a request using `curl -vvv` and seeing what the `CApath` is set to.

The root CA cert is used to sign intermediary certs (RapidSSL in this case) that are then used to sign individual site certificates (*.hashicorp.com). This provides a means for the CA (e.g. GeoTrust) to revoke the immediate signing cert without requiring a change to all of the operating system root CA certificates.

Typically intermediary certificates are _not_ included in the OS (for the reasons above, so they must be presented by the web server you are connecting to. Sometimes a server is misconfigured and includes the site certificate but not the intermediary cert, and as a result curl on linux typically fails because it cannot validate the cert chain.

Some browsers (e.g. Chrome) and some implementations of `curl` (like the one on OS X) will resolve the intermediary cert dynamically even if it is not pre-installed on the OS, so you will not see the problem everywhere.

If this root cert is missing the entire TLS validation will fail because the final part of the chain cannot be resolved.

Some of this is academic since go uses its own crypto library, so the only way to be sure is to invoke the code path in packer. That said, I tested both URLs you indicated with curl and I don't see the x509 problem. I also tested using `packer push` and I don't see the problem.

So (I would like you to clarify because I can't tell for sure) one of the following is the case:

- Your ubuntu machine is missing the root cert so it cannot validate the cart chain
- There is a bug in packer that prevents the cert from being validated
- There is/was a network problem that causes the TLS handshake to be aborted

I have not observed anything that indicates that the TLS certificates are misconfigured on our side (likely it would be failing elsewhere also).

**Comment by tvlooy** [comment]
@cbednarski believe it or not, I changed nothing and today it just works. Computers ...
