### ISSUE TITLE
Avoiding "Vagrant insecure key detected. Vagrant will automatically replace..." in boxes created with Packer

### ISSUE THREAD

**Issue by jerzygangi** [mitchellh/packer#3293]
I'm building a CentOS Packer box for Vagrant and VirtualBox.

In my Packer template, I run a bash script to configure the box for Vagrant:

```
mkdir -pm 700 /home/vagrant/.ssh
curl -L https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -o /home/vagrant/.ssh/authorized_keys
chmod 0600 /home/vagrant/.ssh/authorized_keys
chown -R vagrant:vagrant /home/vagrant/.ssh
```

After the box is built, I `vagrant up` with it. This warning comes up:

```
default: Vagrant insecure key detected. Vagrant will automatically replace
default: this with a newly generated keypair for better security.
default:
default: Inserting generated public key within guest...
default: Removing insecure key from the guest if it's present...
default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

What do I need to do in my Packer to avoid this warning?

**Comment by cbednarski** [comment]
Thanks for opening an issue. This is working as designed and there is nothing you need to change here.

When you package a box for use with Vagrant, Vagrant must be able to use the shared Vagrant private key in order to login to the VM. However, because the vagrant private key is not secret, someone on your network could conceivably login to any VM started by Vagrant by downloading the private key from github.

Since we don't want random people logging into our Vagrant VMs, Vagrant changes the key pair when you first boot a VM.

It _is_ possible for you to customize this key when you build a machine with packer but it will no longer work out of the box with `vagrant up`. You would need to provide the private key to each prospective user along with instructions on how to install it. For usability reasons I would not recommend this.

**Comment by jerzygangi** [comment]
Thank you @cbednarski
