### ISSUE TITLE
provisioners and lxc

### ISSUE THREAD

**Issue by wilrnh** [mitchellh/packer#3294]
Just found an issue with packer and LXC. Apparently, packer hangs when trying to provision (tested with shell provisioner) an LXC container. This happens on CircleCI since they use LXC: https://circleci.com/docs/docker#docker-exec.

My question: is there a way to get packer to use lxc-attach instead of docker exec to run the provisioner?

Thanks!

**Comment by cbednarski** [comment]
Thanks for opening an issue. I think our documentation on this topic may be a bit misleading or out of date. Docker and LXC have diverged significantly since the early days, and at this point I would consider them independent technologies. In an upcoming version of packer we will be completely replacing the docker CLI implementation with one that communicates directly with the docker API, so we will not be able to accomplish the type of command replacement you're suggesting.

At this point if you'd like to use LXC I think the best path forward is to make a new packer plugin, perhaps to communicate with LXD instead. This is not on our roadmap, tough we would accept a contribution. There is an issue open for this in #2864. If you have additional feedback please include it in that issue.

To work around the CircleCI problem you can modify your packer build to spin up a VM in AWS or Google cloud for the build, run docker via shell provisioner, and then [export the container](https://www.packer.io/docs/post-processors/artifice.html) from the VM. You may also want to try running your build in [HashiCorp's Atlas](https://atlas.hashicorp.com/), where packer docker builds are supported natively, or any other CI server that does not use LXC as a docker backend.
