### ISSUE TITLE
RFQ: Allow provisioner to get communicator details.

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#3331]
If would allow provisioners to read connection details (ip, port, type, key, etc) from the communicator if would open up some nice features.

E.g.
- `ansible` (remote): we could remove the convoluted ssh proxy code, get WinRM, and Docker API support.
- `shell-local` (both): Could set a lot of variable, e.g. `PACKER_COMM=ssh, PACKER_SSH_IP=127.0.0.1, PACKER_SSH_PORT=22, PACKER_SSH_USER=vagrant, PACKER_SSH_PASSWORD=vagrant`. This would allow you to run arbitrary commands that communicates over SSH against the VM. Equally for WinRM.
- Other providers could use this in a different way, maybe changing the behaviour depending on the communicator type etc.

To make this universal we need to write the `ssh_private_key_file` to a temp file if it is a temporary key (Amazon, DigitalOcean, and OpenStack).

**Comment by rickard-von-essen** [comment]
FYI @bhcleek

**Comment by rickard-von-essen** [comment]
Related to #3307 and #3260

**Comment by cbednarski** [comment]
> ansible (remote): we could remove the convoluted ssh proxy code, get WinRM, and Docker API support.

Since ansible is (currently) the only one that needs this, is there a way we can pass in the communicator and get an ansible connection string? Maybe we can use a hook for this. I think this is simpler to maintain and doesn't result in credentials ending up in strange places.

> Could set a lot of variable, e.g. PACKER_COMM=ssh, PACKER_SSH_IP=127.0.0.1, PACKER_SSH_PORT=22, PACKER_SSH_USER=vagrant, PACKER_SSH_PASSWORD=vagrant. This would allow you to run arbitrary commands that communicates over SSH against the VM.

I appreciate the flexibility here but I can't support this. This is not packer anymore. Constraints are useful.

**Comment by bhcleek** [comment]
I don't see why this should be necessary. The ansible provisioner should work with WinRM and Docker builders now. The shell provisioner can be used to run arbitrary commands on the node now. Also, the communicator may not be communicating using the TCP/IP at all; the communicator abstraction is useful precisely because it defines a contract that allows clients to be unconcerned about the transport.

**Comment by rickard-von-essen** [comment]
Ok, I kind of agree with all the above. The main use case was `ansible` (remote). But as @bhcleek points out it should work now.
