### ISSUE TITLE
packer.io support to PPC

### ISSUE THREAD

**Issue by fbo** [mitchellh/packer#3341]
I wish the Packer.io extends the ability to support the solution for PowerPC servers (PPC), I find no documentation explaining the possibility ...

**Comment by rickard-von-essen** [comment]
Do you mean that you are looking for a PPC build of packer? Could you add more details? OS, 32/64-bit, etc.

I doubt that we will build packer for PPC since it's a diminishing platform, but it should be possible to build from source if Go support for your OS and PPC is good enough.

**Comment by cbednarski** [comment]
@fbo You may be able to build this using gccgo in gcc 5, which includes the go 1.4 standard library. For now we are maintaining backwards compatibility with go 1.4, so if you can get gcc 5 with gccgo to work you should be able to compile packer.

Unfortunately we cannot support this build, since we don't have a PPC machine to build or test it and go does not support cross-compiling to that platform. This document may help you get started:

- https://golang.org/doc/install/gccgo
