### ISSUE TITLE
Enabling PTY stops Ansible Remote from connecting

### ISSUE THREAD

**Issue by richard-hulm** [mitchellh/packer#3375]
Describe the problem and include the following information:

- Packer Version: 0.10.0
- Host platform: CentOS7
- Debug log output: https://gist.github.com/richard-hulm/e4be9243757b0f1aed5b

If I have an amazon_ebs builder which boots a t2.micro Centos7 image (requirestty by default)

I then have an ansible provisioner with the following:

```
  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "playbook.yml",
      "sftp_command" : "/usr/libexec/openssh/sftp-server -e"
    }
  ]
```

If I set ssh_pty to false, then it works until I do anything in the ansible script that requires sudo, where it obviously fails due to requiring a tty

If I enable tty, I get the attached error.

Is there anything I can do to work around this in the packer or ansible settings? Otherwise I'll look at disabling the requirement for tty

**Comment by rickard-von-essen** [comment]
Did you check http://docs.ansible.com/ansible/intro_configuration.html#pipelining

**Comment by richard-hulm** [comment]
I had seen that pipelining required tty being disabled - so hadn't tried turning it on.

What specifically should I be checking? I didn't think it was related to this as such, does the ansible-remote provisioner make implicit use of pipelining? If so I can't see this anywhere in the docs :confused: 

It seems the only currently solution is for me to completely remove the requiretty from all our boxes? (which would then also allow me to turn pipelining on as well)

**Comment by rickard-von-essen** [comment]
If you read the log you see this message
`remote command exited with '130': /usr/libexec/openssh/sftp-server -e`
Could you trouble shoot why this command doesn't work for you?

**Comment by richard-hulm** [comment]
It does work if I run it from a shell - (I'm not entirely sure what *working* looks like? But it sits and waits around for input)

From a brief googling - 130 is an error code from bash that signals the process has been killed, so I assumed that packer was killing the subprocess for some reason?

**Comment by bhcleek** [comment]
@richard-hulm I don't think there's anything you can do to work around this. You'll need to turn off requiretty in your sudoers file. Red Hat used to ship with requiretty enable in the sudoers file, but that's since been changed: https://bugzilla.redhat.com/show_bug.cgi?id=1020147#c9, because it caused other problems and provided no benefit.

**Comment by richard-hulm** [comment]
Ok thanks @bhcleek - We have disabled requiretty and it does seem to be working, just thought I'd check in and see if there were any other workarounds.

**Comment by bhcleek** [comment]
As far as I understand it, the problem with `requiretty` is that it signals to the shell on the remote side that it's an interactive shell, so anything in `.bashrc` that writes to the console for interactive logins is then sent, and the sftp client on the other side (Ansible in this case), will receive whatever the remote is sending instead of sftp compliant data. If you were able to turn off all `motd`s, and any other data that is written when a new shell is created, you may be able to leave `requiretty` on.

**Comment by bhcleek** [comment]
FWIW, I've been trying to work around this problem by using the first packet sent by an SFTP server, `SSH_FXP_VERSION` as a magic cookie and discarding all output until that cookie. I've been unsuccessful, though; I still get `remote command exited with '130': /usr/libexec/openssh/sftp-server -e`. From what I can tell, it's because the `SSH_FXP_VERSION` packet sends an ASCII 3, which is being interpreted by the shell as CTRL-C. I'll keep working on it, because I'd like to get this resolved for everyone.

In the meantime, you can use the technique described for the [shell provisioner](https://www.packer.io/docs/provisioners/shell.html) to run a script using sudo to turn off `requiretty`
```
{
      "type": "shell",
      "scripts": ["edit_sudoers.sh"],
      "execute_command": "echo '{{user `ssh_password`}}' | sudo -E -S /bin/sh '{{ .Path }}'"
    }
```
