### ISSUE TITLE
Make `ssh_host` option available to provisioners

### ISSUE THREAD

**Issue by mlrobinson** [mitchellh/packer#3404]
I would like to be able to reference the `ssh_host` variable that builders either create or can be supplied in a connection block, from within provisioners. I want to be able to run a shell-local provisioner with this variable as an input, so I can then add it to whitelists, or other such tricks, then run the remote provisioner on the temp server as needed, and then another shell-local provisioner to cleanup the whitelist.

**Comment by rickard-von-essen** [comment]
Related to #3331

**Comment by cbednarski** [comment]
@mirobinson Thanks for the suggestion. Unfortunately I don't think there's a way for us to support this going forward, because it opens up all sorts of weird execution paths that packer no longer has any control over. For example, if we want to change the way the communicator works (e.g. adding a bastion connection, for example) we will have no way to propagate this information to these out-of-band connections.

There are a slew of plugins for various provisioning use-cases so if those are inadequate I would like to know more about the specific use-case you have that is not met by packer's current featureset.

**Comment by mlrobinson** [comment]
That is understandable. My main use case for now, was I am trying to build instances provisoined by a custom Puppet script, inside a new provider environment. Our Puppet master is in AWS, but we wanted to be able to build new images in Azure, Google, and any other provider we could, without having to leave the Puppet master open to the world. I was hoping I could have a shell-local provisioner provide the IP address to a local script to whitelist the IP address temporarily.

For now, I think I can work around it with some other providers by using a static IP address (at least for Azure), and just whitelisting that address to reuse for rebuilding the image again later. Thanks for taking a look. I'll take a look at the plugins to see if there is anything that could support this workflow.
