### ISSUE TITLE
vmware fails to start with more than 7 additional disks

### ISSUE THREAD

**Issue by jhkrischel** [mitchellh/packer#3411]
Creating seven additional disks (#2 - #8), with the following snippet:

```
"disk_additional_size": "{{user `harddisk2_size`}},{{user `harddisk3_size`}},{{user `harddisk4_size`}},{{user `harddisk5_size`}},{{user `harddisk6_size`}},{{user `harddisk7_size`}},{{user `harddisk8_size`}}",
```

When trying to build, the vm fails to start with the following error in vmware.log:

```
[msg.hbaHosted.conflict] Unable to configure virtual device 'scsi0:7', whose type is disk. This virtual device is assigned a SCSI ID which is reserved for the virtual SCSI adapter. Move the virtual device to an unused SCSI ID and try again.
```
[vmware.log.zip](https://github.com/mitchellh/packer/files/200262/vmware.log.zip)

**Comment by cbednarski** [comment]
Thanks for opening an issue. This is not a common use-case so I do not plan to implement this, but I would be happy to review a PR to make this work.

**Comment by kbpease** [comment]
The issue here is that scsi id 7 is reserved under vmware for the scsi controller's use, so you have to skip that id when assigning disks to the vm.  I ran into this previously using a vmware esx5 remote, and got around it using the following to add 8 1GB disks to a VM I was creating - this is outside of Packer's control, but is in the script that invokes Packer to create the VM:

```
for i in `/usr/bin/seq 1 8`; do
  if (( $i < 7 )); then
    target=$i
  else
    target=$(( $i + 1 ))
  fi
  vmdk=/vmfs/volumes/$BUILD_HOST_DATASTORE/$vm_name/${vm_name}_$i.vmdk
  /usr/bin/ssh -o StrictHostKeyChecking=no root@$BUILD_HOST /sbin/vmkfstools -c 1g -d thin -a lsilogic $vmdk
  /usr/bin/ssh -o StrictHostKeyChecking=no root@$BUILD_HOST /bin/vim-cmd vmsvc/device.diskaddexisting $vmid $vmdk 0 $target
done
```

I believe a workable fix would need a change in .../builder/vmware/iso/step_create_vmx.go, to add some awareness of scsi id 7 as a special id for each controller, so any disk number >= 7 would need to be offset by 1 to avoid an attempt to use reserved id 7.  I'm a rank novice with Go, but I can take a stab at a PR for this at some point in the next couple weeks - but if anybody more fluent in Go beats me to it, I sure won't mind.

**Comment by dandunckelman** [comment]
This is still an issue. Can it be re-opened?

**Comment by SwampDragons** [comment]
See comment here for motivation for closing and steps forward: https://github.com/hashicorp/packer/issues/3411#issuecomment-205434186

**Comment by dandunckelman** [comment]
@SwampDragons I did. Sounds like you want to keep issues closed that you won't implement, even though someone in the community could do it. I disagree with that approach but that's just me.

I suppose I'll open a new issue that will look nearly the same if/when I create a PR for this.

**Comment by SwampDragons** [comment]
If you're interested in creating a PR, then I will reopen the issue. 

I can understand why you'd disagree with the approach.  For what it's worth, we don't close all issues that we aren't going to implement. However, we generally do close ones that we think have a small chance of community engagement. This is simply because having low-priority open issues that no one is motivated to work on for years has tended to cause community members to get frustrated, with "why is this still a problem 3 years out" kinds of comments which then causes "PRs welcome" to get lost in the noise. Closing at least gives a clear indication that the maintainers aren't planning to do the work while still allowing people like you to find the issues and comments relating to them in the future. 

I think the right approach varies from project to project but for Packer, I think this has tended to be the path of least frustration. :)

Thanks!  If you do open a PR for this you can still reference this issue and we'll reopen it for you.

**Comment by dandunckelman** [comment]
Right. I can see both sides. Makes sense for a project having hundreds of issues...keeps the noise down.
