### ISSUE TITLE
Feature Request: Deprecate Google Images

### ISSUE THREAD

**Issue by JamieCressey** [mitchellh/packer#3428]
To match the behaviour of other upstream image vendors (Debian, Ubuntu, RHEL etc.):

When building new GCE images, there should be an option to deprecate existing images which match the same image prefix.

E.g if you build an image and call it `"packer-{{timestamp}}"` all other `"packer-{{timestamp}}"` images should then be marked as deprecated.

**Comment by ChrisMcKenzie** [comment]
Would this work as a post-processor possibly?

**Comment by ido** [comment]
See issue  #3587 - the google compute engine image builder should be replaced with one that builds the image outside of GCE and imports it as a QEMU, VirtualBox, or AWS AMI into GCS/GCE.

**Comment by rickard-von-essen** [comment]
@ido #3587 doesn't  really change anything for this issue.

**Comment by rickard-von-essen** [comment]
@JamieCressey  Packer specifically avoid doing life cycle management. We are looking into changing the shell-local post-processor, see #3671. After that change it might be possible to use that to execute a local script that will manage your images.

**Comment by ido** [comment]
@rickard-von-essen I think it is relevant - if we switch to GCE image builders building GCS objects instead of using PD snapshots, then the import happens in a post-processor that can have as an option the ability to deprecate the existing lead image in that family when it pushes a new image into that GCE image family.  This would probably cover most use cases, where users want new instances using that image family on GCE to use the "latest" imported image and the older ones to be available but deprecated.  (For example, see the use case for immutable images described in the second link in the OP of #3587.)

I have no strong feelings either way, if the shell-local post-processor can fill this niche, I'm happy to use it.

**Comment by mwhooker** [comment]
The shell-local post-processor has been updated and can support this use-case now. Per @rickard-von-essen's point, I don't think auto-deprecation is something we intend to build for the GCE builder.
