### ISSUE TITLE
vrde port defaults to 127.0.0.1 not configurable to 0.0.0.0

### ISSUE THREAD

**Issue by jmiller0** [mitchellh/packer#3429]
The latest version of packer defaults the vrde list address to 127.0.0.1.  This is a change in behavior from 0.8.6 where the default is 0.0.0.0.  I would ask for one of the following

1) Change the default back to 0.0.0.0
2) Allow this to be configurable either directly in the json or through manual vboxmanage
  This does not work:     "vboxmanage": [                  ["modifyvm", "{{.Name}}", "--vrdeaddress", "0.0.0.0"]          ],

-Packer Version : 0.10
-Host platform: Centos 7

hard coded location: https://github.com/mitchellh/packer/blob/master/builder/virtualbox/common/step_configure_vrdp.go#L54

Thanks

**Comment by cbednarski** [comment]
Thanks for opening an issue. I don't know the context for the change but I would guess that it was changed as a security measure. We will need to expose a configuration option for this rather than reverting the default to `0.0.0.0`. Sorry about the BC break here.

For now if you are blocked on this I would recommend making the change yourself and recompiling packer. I realize this is pretty involved it should be fairly straightforward process. If you aren't sure how to do this please email me and I'll get you sorted.

**Comment by jmiller0** [comment]
Can you confirm if it will make it in the next release?  If not I'll compile if you can point me to the instructions.

Thanks,
Jeremy

**Comment by cbednarski** [comment]
> Can you confirm if it will make it in the next release?

I do not have plans to work on this.

Our contributing doc includes [general instructions for working on packer](https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md#setting-up-go-to-work-on-packer) which should help you recompile it.

**Comment by mwhooker** [comment]
fixed in 9ec319e2
