### ISSUE TITLE
Windows-Restart fails to reconnect after restart.

### ISSUE THREAD

**Issue by tomswartz07** [mitchellh/packer#3434]
Hey there:
I'm running into some issues with the `windows-restart` provisioner not always catching the computer after it comes back up.
The VM being built is Windows 7. I'm also seeing the same issues with Windows 10.

I'm not exactly sure what's going on, but I'm thinking that it might be related to the [`waitForRestart`](https://github.com/pecigonzalo/packer/blob/f01f62dc88e81c2133e898eaa86c8881e4b3c75b/provisioner/windows-restart/provisioner.go#L102-L141) function in the `windows-restart` provisioner.

It seems that Packer is constantly trying to run the 'check if rebooting' command, but never escapes up to the connect command.

- Packer Version: 0.10.0
- Host platform: Arch, Linux 4.4.5
- Debug log output and template.json Gists [here](https://gist.github.com/tomswartz07/8a85b229717ea673b39aa035f23e42df)

I appreciate any feedback! Thanks for the awesome project. :+1:

**Comment by tomswartz07** [comment]
Interestingly, if I bump the "restart_timeout" to about 1 hour, it will connect within 10 minutes.

Perhaps the default 5m wait time is not enough?

**Comment by cbednarski** [comment]
Thanks for the report. The 5 minute timeout for restart [is documented](https://www.packer.io/docs/provisioners/windows-restart.html) and given my experience with Windows, 5 minutes seems pretty reasonable. In my experience windows 7 restarts in <2 minutes and windows 10 typically restarts in <1 minute.

If you expect your restart to take longer because you are applying system updates or have installed a bunch of startup services or your build host is very busy, you will need to increase the timeout, but I think the current default is reasonable.

I reviewed the code and it should retry the connection every 5 seconds until the connection succeeds or the timeout is reached so I don't see a bug here (please clarify if you think this is buggy).

**Comment by tomswartz07** [comment]
Hi there:

Thanks for the reply.
You are correct: the `windows-restart` provisioner does correctly restart the machine.
However: it appears that *something* is blocking Packer from properly detecting that the machine is back up for slightly longer than the 5 minute delay.

If you check the gist; I'll describe the issue with the indicated lines.
- [Line 778](https://gist.github.com/tomswartz07/8a85b229717ea673b39aa035f23e42df#file-packer-log-L778): Computer is connected via SSH and is restarted using the `windows-restart` provisioner
- [Line 809](https://gist.github.com/tomswartz07/8a85b229717ea673b39aa035f23e42df#file-packer-log-L809): The machine is restarted at this point.
- [Lines 809-867](https://gist.github.com/tomswartz07/8a85b229717ea673b39aa035f23e42df#file-packer-log-L809-L867): Machine restarts within several seconds, and packer outputs an 'Error 181' each time it checks, up to the 5 minute timeout. [See line 838, for example](https://gist.github.com/tomswartz07/8a85b229717ea673b39aa035f23e42df#file-packer-log-L838).

I'm not sure if this is a bug in the detection or what, but without bumping the timeout it definitely fails to connect.

I'd be happy to help provide any more info, if needed.

**Comment by cbednarski** [comment]
This call path communicates with Windows over HTTP / SOAP and parses the response from the Windows machine. Based on the code path the error could be in the HTTP layer, in parsing the SOAP/XML response, or in the body of the SOAP response.

Since the HTTP connection is successful and (it seems) the error is not coming from the XML parser, it seems like the error is probably from Windows. However, I think both a parse error or an error response via SOAP indicate the same problem: that the Windows Remote Management service is not ready to respond yet. Perhaps the machine has completed a power cycle but Windows has not finished starting up or some other service is causing the WRM service startup to be delayed.

From Packer's perspective, though, an error from Windows means that the machine is not ready and Packer doesn't know whether the machine will _ever_ be ready, so it stops trying after 5 minutes. Perhaps we should clarify in the docs that the machine has to reboot _and be ready_.

For instance in the Linux world if the machine reboots but the ssh daemon never starts, or starts before we can run commands, then the restart will fail. It's not sufficient for us to power cycle the machine. The OS must be ready to do work in order for us to continue.

Unfortunately I'm not a Windows expert so I can't offer any tips to diagnose this. I would agree that that error messages are not very helpful, but lacking domain knowledge I can't offer any improvements here. However, I still do not see an indication that there is a bug in Packer. If increasing the timeout resolves the issue, I think this is an affirmation that Packer is working properly.

**Comment by tomswartz07** [comment]
Hey there, @cbednarski:

Thanks for clarifying.

I would suppose that it's the case as you describe; the VM is restarted, but not quite *ready*.

Increasing the timeout delay does resolve the issue, and in line with your latest response, I would agree that it's not a bug with Packer itself.

Perhaps it would be helpful to make a note in the online docs, as you've mentioned.

Anyway, I appreciate the help!

**Comment by cbednarski** [comment]
Thanks for the feedback! I will make a note in the docs to clarify what is happening under the hood.
