### ISSUE TITLE
amazon-chroot builder and block device mappings

### ISSUE THREAD

**Issue by morganchristiansson** [mitchellh/packer#3458]
Hello.

Put simply - there's no way to specify block device mapping for the AMI being created by the amazon-chroot builder.

Is the omission of this feature intentional or has it just been left out? I found this post from 2 years ago about it but not much else: https://groups.google.com/forum/#!topic/packer-tool/ox7gwlao2zk

**Comment by cbednarski** [comment]
In EBS the block device mapping is specified when the instance is booted, which happens at the start of the build. When the build finishes the mapping is associated with the AMI automatically.

However, there is no instance booted for the chroot so we would need to modify the AMI metadata _after_ the build. More here: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html

I don't have plans to implement this, but I'd be happy to review a PR for it. If you are interested in trying this yourself, I think you will find some relevant parts of the code here:

- [chroot build steps](https://github.com/mitchellh/packer/blob/master/builder/amazon/chroot/builder.go#L157-L206)
- [modify ami attributes step](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_modify_ami_attributes.go)

If you don't want to mess with the code, please see if the EBS builder will work for you since this allows you to specify the mapping already.

**Comment by morganchristiansson** [comment]
Yeah I see that, but as there is a source AMI and packer takes on the responsibility of creating the output AMI it would be nice to specify parameters (in my case a data volume mounted under /mnt).

There's a number of alternative ways to specify block device mappings:
1. AMI
2. When launching new EC2 instance
3. Specify in launch config

I've ended up using the other approaches. Might have a look at a PR later if there's still need for it. The other approaches have the benefit of not needing to rebake the AMI to change the block device mappings.

**Comment by cbednarski** [comment]
Yep, you've covered it pretty well. This is certainly a feature gap and the UX is understandably frustrating. As far as AWS is concerned the original resource is not an AMI, but rather is a EBS snapshot which does not have any of those other properties like BDM.

We can paper over this but we need to write and test new code for the both the **specify** and **retain** cases you mentioned.
