### ISSUE TITLE
Feature Request: Babushka provisioner

### ISSUE THREAD

**Issue by techjacker** [mitchellh/packer#3470]
I'd like to be able to provision with [babushka](http://babushka.me/).

Is it something you'd accept a PR for?

**Comment by cbednarski** [comment]
Thanks for opening an issue. I'm not familiar with babushka, personally. Can you share your goals for this provisioner? E.g. what would a babushka-specific provision do for you that the shell provisioner does not already do?

**Comment by kwilczynski** [comment]
@techjacker I am not sure how hard would it be to add babushka support (I am not very familiar with it), but writing a new provisioner is fairly easy. I recently made [one](https://github.com/kwilczynski/packer-provisioner-itamae-local/) for [Itamae](https://github.com/itamae-kitchen/itamae), following what other provisioners already do very well, and it was very straight-forward. Give it a go, I would say.

**Comment by techjacker** [comment]
I guess you could use the shell provisioner for chef, ansible etc too if you had to, it's the convenience factor.

@kwilczynski thanks for the link to your provisioner. I there any reason why you decided to create a separate repo for it rather than forking the packer one?

**Comment by kwilczynski** [comment]
@techjacker not particular reason. I wasn't sure if @cbednarski would be keen on adding it to Packer (if so, then I am happy to send a PR), so I kept it separate. There is another one, which leverages `itamae ssh` (contrary to `itamae local`) to execute locally against remote node, but it requires working SSH proxy with SCP support, so not yet finished :(

**Comment by mwhooker** [comment]
I think we probably would accept it, but would want to know enough people used it so that it would be supported. Worse case for us is an abandoned provisioner we don't know how to support. I'd say it's unlikely, but possible it would get merged.

Our general feeling is that we want to move away from supporting specific provisioners, and more towards support generic provisioners, like file and shell.

I think probably next step would be to submit an RFC issue, and mention what the interface would look like, why it's more convenient than shell/file processors, and try to get +1s from the community. If people are engaged in the idea, I'd say throw up a PR and reference the RFC.

For now though, I'm going to close this since we're not targeting it for 1.0
