### ISSUE TITLE
Passing ansible config to target machine

### ISSUE THREAD

**Issue by ns-phennessy** [mitchellh/packer#3480]
Currently I'm using packer to build AMI's with an Ansible provisioner. 

There are a large number of options in my `ansible.cfg` to make it run faster and have some custom plugins. So far as I can tell; Packer has no built-in way to pass this information to the Ansible provisioner. 

Would the best practice be to copy these things over to the target machine via shell before running the Ansible provisioner? (This seems sloppy and unclean to me)

Thanks!

**Comment by cbednarski** [comment]
There is no native "ansible.cfg" option for the ansible provisioner. You can use [environment variables](http://docs.ansible.com/ansible/intro_configuration.html#environmental-configuration) but if you already have everything in a file that's probably a lot easier.

You can upload your config file using a [file provisioner](https://www.packer.io/docs/provisioners/file.html). Since there are potentially lots of differences between the host and guest OS we don't do this automatically.
