### ISSUE TITLE
[provisioner/salt] Ability to run other states rather than highstate only

### ISSUE THREAD

**Issue by TaiSHiNet** [mitchellh/packer#3526]
It would be really helpful to be able to run state.sls module aside state.highstate.
I've tested this using shell provisioner on a machine with salt already bootstrapped (by packer) and worked fine.

Thanks in advance

**Comment by cbednarski** [comment]
Thanks for the suggestion! Our salt module is maintained by the community so if you are willing to take a stab at this I would be happy to review your PR. Since this is not a feature I plan to implement I am going to close this, but I would be happy to include this feature someone contributes it.

You might be able to accomplish this by adding an option to specify the desired state, or an option to specify the salt invocation command (other provisioners have ways to override the provisioner call, for example).

In the mean time you might want to try invoking salt using the shell provisioner, since this will allow you to specify the entire invocation however you like.
