### ISSUE TITLE
qemu builder on OS X does not need -display option with default Homebrew build

### ISSUE THREAD

**Issue by mfischer-zd** [mitchellh/packer#3563]
The default qemu build on OS X uses the Cocoa display system and does not use SDL.  

```
2016/05/20 16:45:44 packer: 2016/05/20 16:45:44 Qemu stderr: qemu-system-x86_64: -display sdl: SDL support is disabled
2016/05/20 16:45:44 ui error: ==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.
==> qemu: Error launching VM: Qemu failed to start. Please run with logs to get more info.
```

Consider allowing the user to run qemu without the `-display sdl` option.

**Comment by imduffy15** [comment]
You can workaround this by using `headless: true` https://github.com/mitchellh/packer/blob/master/builder/qemu/step_run.go#L103 is the relevant section of code.

**Comment by mfischer-zd** [comment]
Thanks, but it's not really a workaround as it disables the display.  I want it to work!

**Comment by mwhooker** [comment]
hmm, this would be a lot easier if you could pass `-display cocoa` to qemu, but it looks like cocoa will only work if you *don't* pass a `-display` option.

Because of the way our arg parser works, we can't easily delete the display arg without adding an entirely separate config option.

If someone wants to PR a new config option similar to `headless` that just elides the `-display` option, i'd merge it in. perhaps something like `-defaultdisplay`.

I'm not super familiar with cocoa, so if someone could validate my assertions ^
