### ISSUE TITLE
Ansible (remote) provisioner does not retain user with a reboot step

### ISSUE THREAD

**Issue by Daemoen** [mitchellh/packer#3569]
Was able to get the authentication phase working after fixing the correct provisioner stanza... however, the logs show that we do encounter an error after rebooting the instance :  https://gist.github.com/Daemoen/026f18f77fa7cbff0350b97b167f750c

Starting at 1158, we can see that the user being used is root:

```
2016/05/24 00:48:52 ui: [0;32m    vb: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root[0m
[0;32m    vb: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root[0m
```

However, after the reboot is issued, it returns to the proxy and is attempting to use the local user instead (line 1186 begins the next part)

We can see:

```
2016/05/24 00:48:53 ui: [0;32m    vb: ESTABLISH LOCAL CONNECTION FOR USER: mmercer[0m
[0;32m    vb: ESTABLISH LOCAL CONNECTION FOR USER: mmercer[0m
```

**Comment by cbednarski** [comment]
Thanks for the report! I think what you might be able to do in the meantime to work around this bug is to run two provisioners; one that does everything up to and including the reboot, and one that does everything after the reboot. This is what we recommend for shell provisioners, and I'm actually surprised that Ansible continues working after a reboot (shell certainly would not).

I'm curious where this local ssh user is coming from, though. AFAIK packer only reads this data from the config and we don't use the system SSH agent or SSH configuration at all. Maybe Ansible is actually changing the user after the reboot / reconnect happens? Maybe we need to pass an extra flag there to retry with the same user after reboot.

**Comment by conorsch** [comment]
Ran into this problem today. For some reason, Packer wasn't reconnecting to the host after rebooting it. No username config changes were required—instead, a bump in the ANSIBLE_TIMEOUT value caused Packer to reconnect successfully after the host came up. Add this to your provisioner block:

```
ansible_env_vars": [ "ANSIBLE_TIMEOUT=3000" ]
```

That's an unnecessarily high value, but it works for me, running packer v0.10.1.

**Comment by mwhooker** [comment]
Going to close this as there seems to be a viable workaround, and this posted gist is a 404.

Please open a new issue with the required debugging information if you continue to see this
