### ISSUE TITLE
fail build if non zero exit code received within boot_command execution 

### ISSUE THREAD

**Issue by thechile** [mitchellh/packer#3591]
If a command is run within the context of `boot_command` and it fails with non 0 exit code, is there a way to fail the build ?

Examples might be 
a) when running dhcp client, it fails to get lease.
b) running wget with HTTPIP/HTTPPort fails because the request file doesn't exist
c) passing an answer file to some OS setup helper like setup-alpine which has a typo that causes it to fail
d) running wget to get some bash script, and then running it... which exits with failure.

I wasn't able to find this in doc's. Can someone confirm if this is a feature i overlooked or not possible ?

Thanks
Scott

**Comment by rickard-von-essen** [comment]
It's not possible to handle from Packer's side. The `boot_command` types the command on a virtual keyboard and there is no communication back to Packer.

**Comment by cbednarski** [comment]
@thechile As @rickard-von-essen mentioned, this process happens over VNC / RDP so there is no process exit status. To debug or develop a new OS you should use GUI mode. If you make your boot command deterministic and do not rely on the network (for example) it will be reliable.

Boot failures will show up as an ssh connection timeout but since there is no way for packer to see inside the OS at this point the only thing you can do is use the GUI or take a screenshot of the VM and inspect it yourself.
