### ISSUE TITLE
AMI life cycle management - deregistering old amis 

### ISSUE THREAD

**Issue by thiyagas** [mitchellh/packer#3610]
FOR FEATURES:

To deregister older(st) ami(s) in the account ? Next, would be life cycle management of the ami !!

FOR BUGS:

AWS_TIMEOUT_SECONDS can be set in variables ?!

**Comment by cbednarski** [comment]
> To deregister older(st) ami(s) in the account ? Next, would be life cycle management of the ami !!

We don't do this since packer runs are stateless and we do not know anything about other AMIs in your account. Managing those other AMIs is out of scope. There are other tools suited to doing this, such as the AWS CLI, which you can use to script the behavior you want.

> AWS_TIMEOUT_SECONDS can be set in variables ?!

Yes! This can be specified as an environment variable. See the [code here for reference](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/state.go#L223-L241). Example:

    AWS_TIMEOUT_SECONDS=60 packer build ...
