### ISSUE TITLE
Error launching security group

### ISSUE THREAD

**Issue by joslinm** [mitchellh/packer#3627]
- Packer Version: 0.10.0
- Host platform: OSX
- Debug log output: https://gist.github.com/joslinm/9dc613a0b9bc3b3d0a4ffdb7a388d192

Sorry for the poor logs -- I am kicking packer off from my own build process within Ruby scripts.

This is an intermittent error, but the crux of it is that a security group can't be found and crashes the whole build. I believe I've seen it more regularly while performing simultaneous packer builds. 

Please let me know if you need more info.

**Comment by cbednarski** [comment]
Thanks for the report!

> I believe I've seen it more regularly while performing simultaneous packer builds.

I noticed this happens in the cleanup section. I wonder if Build A is cleaning up Build B's security groups while B is still in flight, and then when B tries to clean up after itself it can't find the SG anymore.

This sounds like a bug to me!

To work around this you can create a security group manually and [specify it in your build](https://www.packer.io/docs/builders/amazon-ebs.html#security_group_id). This way packer will not create / delete a temporary one.

**Comment by joslinm** [comment]
By the way, minor documentation bug: 
```
access to the ssh_port given below.
```

However, you do not describe that option anywhere else in the page. Of course I'm sure it defaults to 22 and as a result, set the SG accordingly but just FYI.

**Comment by nerk01** [comment]
- Packer Version: 0.10.1
- Host platform: Ubuntu 10.10, Max OSX 10.10.5

Just to chime in, I've seen this now too.

**Comment by jamiethermo** [comment]
Running this on a Jenkins box, so quite likely that multiple builds running at once. Also, perhaps packer could output its version number as part of log output...
```
2016/09/02 17:03:14 ui: ==> agent: Authorizing access to port 22 the temporary security group...
==> agent: Authorizing access to port 22 the temporary security group...
2016/09/02 17:03:14 ui: ==> agent: Launching a source AWS instance...
==> agent: Launching a source AWS instance...
2016/09/02 17:03:14 ui error: ==> agent: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-e6e0629c' does not exist in VPC 'vpc-xyz'
==> agent: 	status code: 400, request id:
==> agent: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-e6e0629c' does not exist in VPC 'vpc-xyz'
```

**Comment by pporada-gl** [comment]
I get this when running local packer builds.
```
2016/10/06 09:07:50 ui: ==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
2016/10/06 09:07:50 packer: 2016/10/06 09:07:50 [DEBUG] Describing tempSecurityGroup to ensure it is available: sg-59c6ea23
2016/10/06 09:07:50 packer: 2016/10/06 09:07:50 [DEBUG] Error in querying security group InvalidGroup.NotFound: The security group 'sg-59c6ea23' does not exist
2016/10/06 09:07:50 packer: 	status code: 400, request id: dba19f95-1bd4-46f9-88bb-c8a6d0d95713
2016/10/06 09:07:55 packer: 2016/10/06 09:07:55 [DEBUG] Describing tempSecurityGroup to ensure it is available: sg-59c6ea23
2016/10/06 09:07:55 packer: 2016/10/06 09:07:55 [DEBUG] Found security group sg-59c6ea23
2016/10/06 09:07:55 ui: ==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Launching a source AWS instance...
2016/10/06 09:07:56 ui:     amazon-ebs: Instance ID: i-020c0584e0150c35e
    amazon-ebs: Instance ID: i-020c0584e0150c35e
```

**Comment by rickard-von-essen** [comment]
@pporada-gl pp I retries as you can see on the next line. Also see https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_security_group.go#L67

**Comment by rickard-von-essen** [comment]
@jamiethermo I does print the version in the log.

**Comment by rickard-von-essen** [comment]
@joslinm If you are happy with the solution to not use temporary SG's I think this should be closed.

**Comment by joslinm** [comment]
yea I think the solution not to use temporary SGs works just fine

**Comment by heph** [comment]
I'd like to point out that this requires knowing and hard-coding sg-ids in packer config, which means the same packer template isn't portable into different regions or accounts.

This is incompatible with Netflix's Spinnaker, and I imagine I'm not the only one who's been hoping for an actual fix to this issue.

This is a workaround, not a fix, and the issue should not have been closed.

**Comment by rickard-von-essen** [comment]
@heph we are open for PR's. It's also trivial to set the sg via `variables` which probably covers most users.

**Comment by ryanrupp** [comment]
I've ran into the issue intermittently over the past several months and have followed some of the issues trying to resolve this issue. Here's the following related issues:

https://github.com/mitchellh/packer/pull/3656 - initial attempt to verify the security group exists after creation
c4c46c349e4860d3b959b2bbe8f306630db55751 and d47e47cf1f22ef3b24d344ec08e91d863e6a8ba6 made the waiting more robust and longer.

However even with those latest commits using v0.12.1 (should have the above fixes) we still get some intermittent failures. I didn't have debug logging enabled unfortunately when this occurred but it looks like the "DescribeSecurityGroups" part does actually pass however when going to create the EC2 instance it actually fails. I'm not sure if this is just part of the AWS API and eventual consistency, they note to use the strategy that's essentially being used (loop describe until its found) - mentioned [here](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency) specifically:

> InvalidGroup.NotFound
If you successfully run the CreateSecurityGroup command, and then immediately run another command using the instance ID that was provided in the response of CreateSecurityGroup, it may return an InvalidGroup.NotFound error. To confirm the state of the security group, run the DescribeSecurityGroups command using an exponential backoff algorithm.

Given my log output I can see at least getting passed the "describe" loop:

```
==> amazon-ebs: Prevalidating AMI Name...
    amazon-ebs: Found Image ID: ami-78fe8d6f
==> amazon-ebs: Creating temporary keypair: packer_586d5e4e-ddff-c67e-2caf-2ee96b7aac35
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing access to port 22 the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-b419f8c8' does not exist in VPC 'vpc-60420605'
==> amazon-ebs: 	status code: 400, request id: be98b0ab-4738-4188-bbbf-a116ea126495
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-b419f8c8' does not exist in VPC 'vpc-60420605'
	status code: 400, request id: be98b0ab-4738-4188-bbbf-a116ea126495
```

Specifically because "Launching a source AWS instance" gets logged after it. So therefore the security group is being found by "describe" but is not found again then when trying to create the EC2 instance. The AWS guide I linked does mention simply waiting again even if the describe returns correctly which isn't the greatest:

> Add wait time between subsequent commands, even if a Describe command returns an accurate response. Apply an exponential backoff algorithm starting with a couple of seconds of wait time, and increase gradually up to about five minutes of wait time.

I probably will hardcode the security group ID in the meantime just trying to think what the fix would actually be here something like:

- Wait for multiple describes to successfully complete (does that make sense?)
- Retry on EC2 instance create (bit messy, would want to only do it probably if it was the security group failure and nothing else)
- Arbitrary wait of some sort after the describe (doesn't make sense really, how long to wait?)
- Something else is going on

As a side note it's interesting here this happens before the describe loop to create the security group with SSH access  - https://github.com/mitchellh/packer/blob/d310de8cf5871354bd1d12996a87020803d373ea/builder/amazon/common/step_security_group.go#L67 - there's retry logic when trying to modify the security group to add SSH access to it. Guessing this may work because it's specifically modifying a resource by its ID, some eventually consistent systems like Elasticsearch work if you read by ID it will be immediately available but eventually consistent in search results.  So you have:

1) Temp security group created
2) SSH access added to it (works)
3) Describe loop on the security group (works)
4) Create EC2 instance referencing that security group (fails)

**Comment by rickard-von-essen** [comment]
One adidtional fixa for SG's have been added in master on #4369, still not relased as of v0.12.1. @ryanrupp please test if that solves your issue.

> This is a workaround, not a fix, and the issue should not have been closed.

@heph This was closed by the original issue author since he is sattisfied with the current implementation. If that isn't working for you open a new issue and describe in detail you scenario or open a PR with a improvement.
