### ISSUE TITLE
Ansible remote slow with packer

### ISSUE THREAD

**Issue by teu** [mitchellh/packer#3647]
Hi,

experiencing slow build times on packer 0.10, osx.

The playbook builds about twice as long with packer compared to a ansible-playbook invocation and getting this:
```
amazon-ebs: rejecting auth-agent-req@openssh.com request
```
in the logs a lot.

My packer config https://gist.github.com/teu/5a845471cb3edbf5a0c799dd52049382

Thanks!

**Comment by rickard-von-essen** [comment]
Could you provide your playbooks too.

**Comment by cbednarski** [comment]
@teu I noticed you are using a t2.medium which is a "timeshare" instance. These types of instances are granted additional CPU credits over time. Since packer instances are short-lived they do not have time to accumulate CPU credits, and as a result they will probably be throttled right away.

Can you try to reproduce this behavior on a non-t-series machine?

**Comment by teu** [comment]
Hi,

measured the playbooks with different machine types:
- t2.medium - forever
- m3.medium - 35min
- c4.large - 25min

However could not test with packer as the playbooks fail (but they work with ansible-playbook). Getting errors that there are variables from group_vars missing. 

Any clue why my playbooks would fail with packer but work just fine with ansible?

```yml
{
  "variables": {
    "ami_ordering_number": "008"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "us-west-1",
      "source_ami": "ami-06116566",
      "instance_type": "c4.large",
      "ssh_username": "ubuntu",
      "ami_name": "exportsbox-{{ user `ami_ordering_number` }}-{{timestamp}}",
      "associate_public_ip_address": false,
      "vpc_id": "vpc-e5b5ae87",
      "subnet_id": "subnet-4e371808",
      "ssh_private_ip": true,
      "security_group_ids": [
        "sg-a01af2c5",
        "sg-833eb6e7"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'Waiting for cloud-init...'; sleep 1; done"
      ]
    },
    {
      "type": "ansible",
      "playbook_file": "./playbooks/exportsbox.yml",
      "ansible_env_vars": [
        "ANSIBLE_HOST_KEY_CHECKING=False"
      ],
      "extra_arguments": [
        "--ask-vault-pass",
        "-b"
      ],
      "groups": [
        "base",
        "exportsbox",
        "amazon",
        "debops_all_hosts"
      ]
    }
  ]
}

```

Playbook:
```yml
---
- include: base.yml target=exportsbox
- name: Configuration for uxpin SWF exports boxes
  hosts: "{{ target | default('exportsbox')}}"
  gather_facts: true
  vars_files:
    - "../inventory/files/templates/exportsbox/credentials.yml"
```

**Comment by cbednarski** [comment]
@teu Sorry to keep you waiting for a reply -- I don't use ansible often so you will likely get a better response on the [mailing list](https://www.packer.io/community/).

**Comment by ricardclau** [comment]
If you are seeing problems related to group_vars, this can be due to the fact that unless you specify an inventory file, packer executes Ansible with an inventory of only localhost so unless you have some defaults / group_vars for "all" hosts you may experience such issues as there are no groups in that run mode.

I don´t have a good explanation for packer being so slow with Ansible. We have seen the speed fluctuate significantly but it usually takes 5-10 minutes tops to create an AMI with say Ubuntu 14 + fully upgrade + something like install erlang + rabbitmq with t2.micro

What sort of tasks are you doing in base.yml?
