### ISSUE TITLE
Amazon: Enable ENA registration support for new instance types

### ISSUE THREAD

**Issue by phobos182** [mitchellh/packer#3688]
AWS has new instance types which support a new Elastic Network Adapter (ENA), much like SR-IOV. Packer should allow us to set support for ENA while registering a new image, much like SR-IOV inside of the templates.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html

**Comment by kwilczynski** [comment]
@phobos182 since I need this too, I will get this done, I hope.

Since the attribute name "enchaned_networking" is just a boolean at the moment, since back when it was added only the SR-IOV (Intel 82599 VF) was available, we would need to introduce another attribute called "enchanced_networking_type" which would take either "sriov" (maybe "simple" would be better?) or "ena" and set it accordingly.

Internally, the API takes an attribute with an attribute value, and for SR-IOV it is a string that spells "simple", whereas for ENA the attribute value is a boolean type, so just true/false to enable/disable. That is why I am thinking about introducing new attribute for setting up the type.

Any thoughts before I get a stab at this, @phobos182 and @cbednarski ?

**Comment by kwilczynski** [comment]
To add.

The reason why I was thinking about adding other option, as changing the existing one to accept a string instead of a boolean would be a breaking change. For people will older templates this might be an issue. Although, if it's fine, then we could just have e.g.

`enhanced_networking": "sirov"`

And that would be it.

**Comment by kwilczynski** [comment]
Support for Enhanced Networking will be coming to Terraform in the future, as per: https://github.com/hashicorp/terraform/issues/7815, hopefully.

**Comment by mwhooker** [comment]
This sounds reasonable, but isn't something we're targeting for 1.0, so I'm going to close this. There is a WIP PR out for this (#3688), and as soon as it's ready to go, we'll merge it. There are some specific things in the PR that need doing, so help wanted there. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
