### ISSUE TITLE
Incorrect docker run command on Windows 7

### ISSUE THREAD

**Issue by mrchief** [mitchellh/packer#3734]
Basically packer is trying to run this command with an invalid file path: 

```
docker: Run command: docker run -v C:\Users\mrchief\AppData\Roaming\packer.d\tmp\packer-docker811607059:/packer-files -d -i -t centos:7 /bin/bash
```

**packer.json**

``` json
{
    "builders":[{
        "type": "docker",
        "image": "centos:7",
        "export_path": "myapp.tar"
    }],
    "provisioners":[
      {
        "type": "shell",
        "inline": [
          "yum install -y epel-release",
          "curl --silent --location http://nsolid-rpm.nodesource.com/nsolid_setup_1.x | bash -",
          "yum -y install nsolid nsolid-proxy nsolid-console etcd",
          "node -v; npm -v;"
        ]
      }
    ]
}
```

Running `packer build packer.json` fails on Windows with this error:

```
Stderr: docker: Error response from daemon: Invalid bind mount spec "C:\\Users\\mrchief\\AppData\\Roaming\\packer.d\\tmp\\packer-docker811607059:/packer-files": invalid mode: /packer-files.
See 'docker run --help'.
```

Packer version: 0.10.1
OS: Windows 7 x64 Enterprise with SP1

packer log: https://gist.github.com/mrchief/2f0f01b831029506b99a623cec92931b

**Comment by mrchief** [comment]
On MINGW (Docker Quickstart Terminal), this command works: `docker run -v '/C/Users/pandah/AppData/Roaming/packer.d/tmp/packer-docker293110795:/packer-files' -d -i -t centos:7 /bin/bash` (note the quotes and forward slashes).

In Powershell, all variants fail (with quotes, without quotes...).

**Comment by mrchief** [comment]
Ok, ran some more tests. Quotes are not needed. The following works fine in both Powershell and MinGW:

`docker run -v /C/Users/mrchief/AppData/Roaming/packer.d/tmp/packer-docker293110795:/packer-files -d -i -t centos:7 /bin/bash`

**Comment by mrchief** [comment]
This doc page shows Windows example with forward slash: https://docs.docker.com/engine/tutorials/dockervolumes/

> On Windows, mount directories using:
`docker run -v /c/Users/<path>:/<container path> ...`

So I guess packer needs to switch how it expands paths?

**Comment by tmzt** [comment]
I've noticed this before, MingW sh expands certain paths with /c/ to Windows style paths. You can avoid this by prefixing a second / on the path. This is necessary if the path is to be passed to the docker daemon verbatim, i.e. the path actually exists a Linux VM and not the host Windows filesystem.

**Comment by mrchief** [comment]
> You can avoid this by prefixing a second / on the path.

Umm but where? All I have is the `packer.json`. Everything else is internal to packer...

**Comment by mwhooker** [comment]
the remote mount path seems to be hard-coded into `builder/docker/step_run.go`: `  runConfig.Volumes[tempDir] = "/packer-files"`

this may be a documentation problem, I'm not sure we're intending to support this builder on Windows.

If someone wants to make that tempDir a windows path and recompile to test if it's even possible to run on Windows, we should be able to support it. Otherwise I think we need to just update the docs and work on Windows support later

**Comment by mwhooker** [comment]
I'm afraid I'm unable to reproduce this. The above json worked for me with [docker for windows](https://docs.docker.com/docker-for-windows/install/) and the latest version of packer.

If this is a specific problem with cygwin, then please re-open with the exact steps to reproduce this issue. I'm afraid I'm not able to support that usage of docker on windows, but perhaps someone from the community has an idea for how to fix.

If you can't get it to work with docker for windows, I'd suggest sending a message to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool), and we'll see if we can help.

**Comment by rion18** [comment]
I believe @mrchief was talking about Docker Toolbox (which uses boot2docker) instead of Docker For Windows. One of the ways to avoid name mangling is to prepend a slash to a path. i.e:
/c/projects/test will become C:\\projects\\test.
However, //c/projects/test will become /c/projects/test.

How feasible is it to have an env variable (DISABLE_MANGLING)  or something of the sort to set this prepended slash?
