### ISSUE TITLE
Need a way to pass environment vars to Chef provisioner commands

### ISSUE THREAD

**Issue by berniedurfee-ge** [mitchellh/packer#3742]
- Packer Version = 0.10.1
- Host platform = vagrant-ubuntu-trusty-64 3.13

While behind a corporate proxy, the Chef provisioner install_command and execute_command need to be fed the proxy environment variables to work properly.

As a workaround, I was able to override the install_command and the execute_command to embed the proxy variables. 

Something like below...

```
"provisioners": [{
        "type": "chef-solo",
        "cookbook_paths": ["work/vendor/cookbooks"],
        "run_list": ["mycookbook::default"],
        "prevent_sudo": true,
        "install_command": "export https_proxy=http://our-proxy-server.com:80; curl -L https://www.chef.io/chef/install.sh | {{if .Sudo}}sudo{{end}} bash",
        "execute_command": "export https_proxy=http://our-proxy-server.com:80; {{if .Sudo}}sudo {{end}}chef-solo --no-color -c {{.ConfigPath}} -j {{.JsonPath}}"}],
```

This is a bit of a kludgy workaround, as I'd like to just leave the install and execute commands alone. It would be nice to be able to use the 'environment_vars' property to ensure the commands have the right environment variables set.

Thanks!

**Comment by kwilczynski** [comment]
That would be trivial to add for Linux et al, but since the provisioner also handles Windows. I mean, we could set a variable with `setx`, but it would not work for `System.Net.WebClient` from PowersShell which needs an instance of `System.Net.WebProxy` to be passed to it for this to work.

I think, the way how you handled that I probably the way to go, and would be on Windows, I suppose. Both parameters are exposed to allow to be overridden to handle such use cases.

Usually, the `environment_vars` tend to be used for `execute_command` only, so should it be used for both? If this gets added.

**Comment by berniedurfee-ge** [comment]
Allowing environment_vars to be applied to both install and execute commands would be convenient, but less flexible.

Not ideal, but it would be cleaner than having to modify the commands just to add the environment variables.

**Comment by mwhooker** [comment]
I appreciate the kludgeyness of needing to override the execute/install command, however, I think this is the best way to do it.

One alternative would be to use the file provisioner to upload the cookbooks, and then run chef-solo manually with the shell provisioner. That way you could set the https_proxy env var.

Another way would be to set the `https_proxy` var inside a `.profile` or `.bash_rc` file, so it would be available on login.

Ultimately, though, the chef-solo provisioner is maintained by the community, and not one we maintain directly. If someone wants to open a PR for this, I would be happy to take a look, but in the mean time I don't think this is going in any time soon, so I'm going to close it.
