### ISSUE TITLE
azurerm - feature req - add the ability to create the packer temporary vm on an existing virtual network

### ISSUE THREAD

**Issue by tasquith** [mitchellh/packer#3749]
As part of our packer build process, we need the ability to refer to other resources at packer time - i.e our PuppetMaster, however for security we have removed all public IPs. 

Would it be possible to add the functionality to allow the creation of the temporary packer vm  to join an existing network/subnet (from a different resource group)?

Thanks,
Tom

**Comment by boumenot** [comment]
There's a [PR][1] that allows you to specify an existing VNET  I just made some updates on review feedback that I need to revalidate, but otherwise my plan is to merge.  If you are ambitious, you can pull down the PR, and give it try before it hits master.  Feedback is welcome.

[1]: https://github.com/mitchellh/packer/pull/3683

**Comment by tasquith** [comment]
Thanks @boumenot - I'm deploying it now, I'll let you know how it goes :)

FYI - you've labeled this issue as Amazon

**Comment by boumenot** [comment]
Oops!  Good catch, fixed.

**Comment by boumenot** [comment]
The PR has been committed.
