### ISSUE TITLE
BUG: vmware-iso esxi 6 fails to power on vm

### ISSUE THREAD

**Issue by s4mur4i** [mitchellh/packer#3781]
I am try to create a vmware image on esxi 6 u2. When running packer, vmware poweron fails:

Build 'box-base' errored: Error starting VM: 'vim-cmd vmsvc/power.on 35'

Stdout: Powering on VM:

Stderr: Power on failed

Packer is running from docker container, with template mounted in. tempalte used: https://hub.docker.com/r/hashicorp/packer/
packer-full

https://gist.github.com/s4mur4i/a1973951e7fb192433d6e22e7949efa5
vmware esxi hostd logs in ist, no information found in them.
Event 1507 : Cannot power on base-image on localhost.localdomain in ha-datacenter. A general system error occurred:
If I copy the vmx file locally anre remove set RemoteDisplay.vnc.enabled to False, I can start the image succesfully. but when in template packer doesn't use this value, it will always be true.
Packer version: 0.10.2.dev 
I did not provide scripts, since the machine can't even power on, so it is not even at that stage.

**Comment by mwhooker** [comment]
From your logs
https://gist.github.com/s4mur4i/a1973951e7fb192433d6e22e7949efa5#file-packer_debug_log-L360

```
2016/08/05 13:08:31 packer: 2016/08/05 13:08:31 Setting VMX: 'RemoteDisplay.vnc.enabled' = 'FALSE'
```

I didn't understand what you meant by
> If I copy the vmx file locally anre remove set RemoteDisplay.vnc.enabled to False, I can start the image succesfully. but when in template packer doesn't use this value, it will always be true.

Could you please clarify? The logs show that you are running with `RemoteDisplay.vnc.enabled` set to false, and VNC is required for packer to work. Please enable VNC and try the build again. 

Please open another ticket if you enable VNC and still are having issues.

You might also try setting the version to `9`, since that's the only version we support

**Comment by spmiller** [comment]
I ran into an issue which looked similar on the ESX server side. In my case it was the same issue as #982 -- the `guest_os_type` was set incorrectly. Once I changed it to a value from [this table](http://sanbarrow.com/vmx/vmx-guestos.html) everything started working again.

**Comment by marema31** [comment]
Thanks for this link, I've encountered in the same issue several times and my google-fu wasn't able to find this.
