### ISSUE TITLE
Can't run build in windows 10 bash

### ISSUE THREAD

**Issue by Ehekatl** [mitchellh/packer#3783]
```
Failed to initialize build 'amazon-ebs': error initializing builder 'amazon-ebs': Unrecognized remote plugin message: Error starting plugin server: listen unix /tmp/packer-plugin059395834: setsockopt: invalid argument
```

- Packer Version
 - 0.10.1
- Host platform
 - windows subsystem linux 
- Debug log output
 - https://gist.github.com/Ehekatl/867eb13503504bc4cb1938d1382c7937

**Comment by StefanScherer** [comment]
Maybe a problem in https://github.com/Microsoft/BashOnWindows itself?

**Comment by rickard-von-essen** [comment]
From googling a bit it seems like wsl doesn't support sockets correct. I'll close this since Microsoft have to fix that. Any more info/opinions on this @boumenot?

**Comment by rickard-von-essen** [comment]
The reason this doesn't work is because packer communicates with plugins over a Unix socket except on Windows which doesn't have sockets. Instead it uses TCP/IP. 
When running on wsl packer thinks it running on a posix system and tries to use a Unix socket and fails. 

The might be a possibility to detect that packer is running on wsl and then use TCP/IP to connect plugins. If anyone finds out how to implement such a workaround a PR is always appreciated.

**Comment by boumenot** [comment]
Let me find the correct person for this issue, and I'll re-raise it internally.  I think WSL needs to support/emulate this; it is an important scenario.

**Comment by boumenot** [comment]
I collected an strace of Packer and there are two calls to setsocketop, but both with the same parameters.

```text
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 4
setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
```

The BashOnWindows team is aware of the [issue][1] (there are others), and is working on a fix.

[1]: https://github.com/Microsoft/BashOnWindows/issues/674

**Comment by Ehekatl** [comment]
@boumenot thx for your work ! It would be really nice to see packer work in WSL
