### ISSUE TITLE
How to load contents of a file into config?

### ISSUE THREAD

**Issue by ivanjaros** [mitchellh/packer#3784]
I am trying to set up a Google Cloud instance with my own SSH key passed in the meta attribute in the GCE builder but I haven't found any support for loading contents of a file(public/private ssh key) into the config and pasting the whole key into it does not make any sense. I know there is support for variable files but that's the same wrong approach. I want to use `file()` just like in Terraform.

**Comment by mwhooker** [comment]
Unfortunately that's not something we support right now. I would recommend using an external tool to perhaps generate a template with your keys inserted into it. you could delete the file afterwards. You could also use environment variables, which is different from variable files.

That being said, having something like ` files()` function is a good idea. We'll be moving closer to how terraform works this year, so we'll most likely be adding something like this.  Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. Not trying to shut you down or say your opinions don't matter or are bad. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon.
