### ISSUE TITLE
Generic 'chroot' builder

### ISSUE THREAD

**Issue by juaningan** [mitchellh/packer#3813]
I would like to build images with traditional approach of chroot + debootstrap (or pacstrap or dnf).

The use case is generate tarballs with a simple os tree to use with systemd-nspawn, lxc or other full system containers.

**Comment by rickard-von-essen** [comment]
Take a look at `amazon-chroot` builder.

**Comment by juaningan** [comment]
Yes, something similar but building in local and generating a tar.gz not an AMI.

**Comment by juaningan** [comment]
And the source has to be a dir provisioned with arbitrary command (ie debootstrap)

**Comment by ChrisLundquist** [comment]
I had a similar thought when writing https://github.com/mitchellh/packer/pull/3523

The hard part was you needed `yum` to build redhat targets, and `dpkg` to build debian targets. Even then it didn't cover all the other flavors of linux.

A generic debootstrap builder makes sense, but the rest of packer doesn't *quite* have that expectation. It would be really nice to import `.tar.gz`s to start containers for example. I think it is also possible to convert them into qemu images, etc.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea. After months of being open, this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is due to our push towards a 1.0 release and taking a look again at all open issues. Please see the mailing list for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. Not trying to shut you down or say your opinions don't matter or are bad. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Comment by q2dg** [comment]
There's a tool that could help to achieve this (it's not Packer related but Systemd's one): https://github.com/systemd/mkosi
