### ISSUE TITLE
Unable to connect to WinRM on Windows Server 2016

### ISSUE THREAD

**Issue by BenHall** [mitchellh/packer#3820]
```
2016/08/21 22:26:02 packer: 2016/08/21 22:26:02 [INFO] Attempting WinRM connection...
2016/08/21 22:26:02 packer: 2016/08/21 22:26:02 [DEBUG] connecting to remote shell using WinRM
2016/08/21 22:27:17 packer: 2016/08/21 22:27:17 [ERROR] connection error: unknown error Post http://127.0.0.1:5985/wsman: read tcp 127.0.0.1:45978->127.0.0.1:5985: read: connection reset by peer
2016/08/21 22:27:17 packer: 2016/08/21 22:27:17 [ERROR] WinRM connection err: unknown error Post http://127.0.0.1:5985/wsman: read tcp 127.0.0.1:45978->127.0.0.1:5985: read: connection reset by peer
2016/08/21 22:27:22 packer: 2016/08/21 22:27:22 [INFO] Attempting WinRM connection...
```

In the builder I've force the port to be 5985 but it doesn't seem to work
```
"ssh_host_port_min": "5985",
"ssh_host_port_max": "5985",
```

I can connect to the WinRM port:
```
nc -z -w1 localhost 5985;echo $?
0
```

Boot command:
```
2016/08/21 22:25:45 packer: 2016/08/21 22:25:45 Executing /usr/bin/qemu-system-x86_64: []string{"-netdev", "user,id=user.0,hostfwd=tcp::5985-:5985", "-boot", "once=d", "-fda", "/tmp/packer032696661", "-m", "8048M", "-name", "packer-qemu", "-machine", "type=pc,accel=kvm", "-device", "virtio-net,netdev=user.0", "-cdrom", "/home/projects/packer-windows2016-standard/iso/14300.1000.160324-1723.RS1_RELEASE_SVC_SERVER_OEMRET_X64FRE_EN-US.ISO", "-drive", "file=output-qemu/packer-qemu,if=virtio,cache=writeback,discard=ignore", "-vnc", "0.0.0.0:31", "-cpu", "Westmere"}
```

I'm using Packer v0.10.1.

Any ideas? Instead of 127.0.0.1:45978, I expected it to use 127.0.0.1:5985

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by BenHall** [comment]
Logs are at https://gist.github.com/BenHall/c69a107d2ce8b86d6235b9a8f84dda29

`./packer version
Packer v0.10.1`

`uname -a
Linux host02 4.2.0-040200-generic #201508301530 SMP Sun Aug 30 19:31:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by BenHall** [comment]
I took the repo https://github.com/lwieske/packer-windows2016-standard/ and tried to port it over to qemu

**Comment by mwrock** [comment]
I was noticing in the `enable-winrm.ps1` script you have:
```
Set-WSManQuickConfig -Force
Set-Item WSMan:\localhost\Service\AllowUnencrypted -Value True
Set-Item WSMan:\localhost\Service\Auth\Basic       -Value True
Set-Service WinRM -StartupType Automatic
Restart-Service winrm
```

I have had bad experiences with this approach on wi2012R2 and anticipate the same on 2016. These windows versions have winrm enabled and running by default. There is no need for the `Set-WSManQuickConfig -Force` or `Set-Service WinRM -StartupType Automatic` and I think your problem is from the `Restart-Service winrm`. The moment basic auth is enabled, packer makes a connection but soon afterwards the winrm service restarts dropping the connection.

I "think" the 45978 may be a red herring. The guest is listening on 5985 and I believe packer sets up auto port forwarding and I have seen `ssh_host_port_min/max` not acting as expected.

I wouldn't rule out the port but a "reset by peer" indicates to me that a socket was established and the other end just hung up and I have absolutely see winrm restarts cause issues and in undeterministic ways due to timing and distance between the host and guest.

**Comment by BenHall** [comment]
Thank you for your suggestion. I removed the start winrm script from the auto unattended xml but it doesn't seem to have worked.

I've uploaded my directory to https://github.com/BenHall/packer-windows2016

**Comment by mwrock** [comment]
You actually want to keep that command in your unattend.xml, but you want to change `enable-winrm.ps1` to:
```
##############
# Enable WinRM
##############

New-Item                                                                       `
    -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Network\NewNetworkWindowOff" `
    -Force

Set-NetConnectionProfile                                                       `
    -InterfaceIndex (Get-NetConnectionProfile).InterfaceIndex                  `
    -NetworkCategory Private

Set-Item WSMan:\localhost\Service\AllowUnencrypted -Value True
Set-Item WSMan:\localhost\Service\Auth\Basic       -Value True
```

On 2016, the file would be more appropriately named configure-winrm instead of enable-winrm since it is already enabled but not configured in such a way that packer can reach. This will prevent the winrm service from stopping and restarting mid flight.

**Comment by BenHall** [comment]
Thank you @mwrock I should have read your original change more closely. 

I just tried https://github.com/jakobadam/packer-qemu-templates for Windows 2012 R2 and I'm starting to believe it could be something related to the server I'm running it on. The only thing I changed was to enable headless and it still is unable to connect to WinRM.

**Comment by mwrock** [comment]
Might also have a look at https://github.com/mwrock/packer-templates/pull/40

**Comment by BenHall** [comment]
Thank you so much for your help @mwrock - Turns out the reason was because the installation couldn't read the ProductKey from the xml. There was a nice dialog waiting for me.

Managed to find it by running it locally against Virtualbox. Thankfully Packer makes it very easy to move between the different targets so I will do this in future for debugging.
