### ISSUE TITLE
Recommend Racker?

### ISSUE THREAD

**Issue by mrjcleaver** [mitchellh/packer#3854]
I was recommended by the Chef community to use https://github.com/aspring/racker as an overlay to Packer.

It does have some nice features, (that frankly might benefit if standard!), but I'm cautious about using something peripheral.

Any feedback about suitability?

If it's like "awesome," has the Packer project considered incorporating it or it's functionality into Packer?

Thanks,
   Martin

**Comment by cbednarski** [comment]
Hi Martin,

I can't say that Racker will satisfy your use case but it's a popular tool and I'd give it a thumbs up. Since Packer configs are JSON it's also easy to roll your own. On the Consul project we have a list of community tools. I'm sure we could come up with something like that for Packer also. Aside from that, though, you'll have to assess for yourself whether it meets your needs.

Cheers!

Chris
