### ISSUE TITLE
SSH communicator does not use fast path for uploads

### ISSUE THREAD

**Issue by bhcleek** [mitchellh/packer#3870]
Packer should have everything it needs to avoid writing files to a temporary directory before uploading them, but it discards that information during an rpc call. Consequently, the ssh communicator writes files to a temporary directory before uploading them to the node. There is code in the ssh communicator to fastpath the file uploads (https://github.com/mitchellh/packer/blob/master/communicator/ssh/communicator.go#L752), but it's never used, because the rpc communicator always uses nil for `Upload`'s `*os.FileInfo` argument (https://github.com/mitchellh/packer/blob/b99a5ab3a2acc7ccbeda868d7c7d0a354b61d287/packer/rpc/communicator.go#L270).
- Packer version from `packer version`: Packer v0.10.2.dev
- Host platform: OSX
- Debug log output from `PACKER_LOG=1 packer build template.json`: https://gist.github.com/bhcleek/5722747b5147f654afccbaff7c92c6be
- The _simplest example template and scripts_ needed to reproduce the bug: https://gist.github.com/bhcleek/fd47ed20db1e450aa0503a73ae30f0e2

**Comment by vtolstov** [comment]
Nice catch!

**Comment by rickard-von-essen** [comment]
Nice!

**Comment by bhcleek** [comment]
I've tried to fix it, but I can't seem to get the decoder to marshal the `*os.FileInfo` value correctly.  I'm getting an error, `cannot decode non-nil codec value into nil os.FileInfo(6 methods)`. I suspect I may need to create and configure an extension to use with `github.coom/ugorji/go/codec`, but I'm not sure. Can you point me in the right direction?

Here's what I have so far: https://github.com/mitchellh/packer/compare/master...bhcleek:fix-fastpath

**Comment by mwhooker** [comment]
@bhcleek the problem is that we can't send an interface with methods attached to it over rpc like that. There's a solution that's used by terraform (see [client]/(https://github.com/hashicorp/terraform/blob/master/plugin/resource_provisioner.go#L53)[server](https://github.com/hashicorp/terraform/blob/master/plugin/resource_provisioner.go#L110)), but the two code bases are not 100% compatible, so some back-porting is needed.

As I get more familiar with the code-base I might be able to help out more, here.

There's also a (somewhat vague) plan to migrate packer to (go-plugin)[https://github.com/hashicorp/go-plugin], which is what terraform is using, but there's no timeline around that.

It might be best to just wait until that happens. If the current behavior is causing problems, feel free to post here and we can try to prioritize this

**Comment by bhcleek** [comment]
@mwhooker I found a simpler path forward than the solution used by terraform by simply providing an `os.FileInfo` implementation that can be used for the rpc communication. RE: #3940
