### ISSUE TITLE
View ttys0 output from qemu builder

### ISSUE THREAD

**Issue by colemickens** [mitchellh/packer#3903]
**Feature request** (I think):
1. I want to see the output from Anaconda when using Packer/Qemu to provision a VM image.

I don't think this is possible now. Packer only wants to show me the status of SSH connecting. It's fine, because eventually the Anaconda installer finishes, reboots with SSH active and Packer can finish provisioning. However, I'd greatly prefer being able to see the actual console output from Anaconda.

I've added args such as `earlyprintk=serial,ttyS0,115200 console=ttyS0` to the `boot_command` but Packer doesn't seem to be passing along the raw output from qemu.

Is there an environment variable that controls this? Or is there no support for this today?

**Comment by rickard-von-essen** [comment]
Let me see if I understod what you want. You would like to have packer printout the serial console so you can see the interaction of `boot_command`.

I have been just recently been looking into this for the (new) bhyve/xhyve builder. Unfortunately it's no possible since packers output is _line oriented_ but serial output is _terminal oriented_. To explain a bit more in detail packer outputs line by line and can't go back and change already out putted lines, they are also interleaved between different builders. But a serial console on the other hand emulates a terminal which allow escape codes for moving the cursor to go back end change previous output.

This leaves you with two options 1) run with `"headless": false` so you get a SDL display, or 2) attach a terminal program to the other end of `ttyS0`. (`ttyS0` on the VM should be connected to a virtual serial port on the host, something like `screen /dev/ttys012  9600`)

**Comment by colemickens** [comment]
Hi @rickard-von-essen. That explanation makes sense, but I'm unable to reconcile it with this:

* I had this process working with raw `qemu` and a Jenkins job before moving to Packer. In that setup, I was fully able to see the serial output from `qemu`... despite the fact that Jenkins does not have any way of giving a real TTY to its jobs. So I feel like it must be possible to say "we don't care about input, just show me the output" to qemu, and thus that could be passed up through `packer` as well?

**Comment by rickard-von-essen** [comment]
The serial output would look ok if it is line oriented, that was why it worked in Jenkins. An example from connecting to FreeBSD bhyve VM:
<img width="585" alt="screen shot 2016-09-20 at 21 21 21" src="https://cloud.githubusercontent.com/assets/557699/18685529/b0f8f1d4-7f78-11e6-9dd3-8562cd2232f0.png">
Non line oriented stuff like running top (htop) would look broken:
<img width="592" alt="screen shot 2016-09-20 at 21 22 38" src="https://cloud.githubusercontent.com/assets/557699/18685613/2252ce40-7f79-11e6-9d63-879c12324181.png">

Most TUI installers run in a similar way for example anaconda would produce strange output.
![anaconda](https://cloud.githubusercontent.com/assets/557699/18685701/79ea9912-7f79-11e6-9ec3-7a729922d1c9.png)

But there are no way of knowing which type of output we will get. Does it make more sense now?

**Comment by colemickens** [comment]
I understand. I don't see why the option couldn't be enabled with the caveat that some types of output (TUI/ncurses/etc) won't work right. Anaconda, for example, has options to force text only output for these types of scenarios.

IMO it'd be better to offer the choice than prohibit it based on the fact that some types of output will not be legible. It's no worse than the current situation where they're equally illegible.

**Comment by mwhooker** [comment]
This isn't something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.

**Comment by pingberlin** [comment]
As a workaround use your current tty as a variabel for 'qemuargs':
```
~/gopath/bin/packer build -var serial=$(tty) centos.json
```

With this config 'centos.json':
(Notice that since we override the "-device"-switch for serial, we need to specify the network device again with "virtio-net,netdev=user.0" as it's run usually by the packer qemu builder.)
```
{
  "variables": {
      "serial": ""
  },
  "builders":
  [
    {
      "type": "qemu",
      "communicator": "none",
      "iso_url": "https://buildlogs.centos.org/rolling/7/isos/x86_64/CentOS-7-x86_64-DVD-1702-01.iso",
      "iso_checksum": "214398910535b815251049ea887c300f5fb87b613f442e39cb0ffb093152cf5b",
      "iso_checksum_type": "sha256",
      "output_directory": "output_centos_tdhtest2",
      "disk_size": 5000,
      "format": "raw",
      "headless": true,
      "accelerator": "kvm",
      "shutdown_timeout": "90m",
      "vm_name": "tdhtest",
      "net_device": "virtio-net",
      "disk_interface": "virtio",
      "floppy_files": "http/ks.cfg",
      "boot_wait": "5s",
      "boot_command": [
        "<tab> console=ttyS0,115200n8 inst.text inst.ks=hd:fd0:/ks.cfg<enter><wait>"
      ],
      "qemuargs": [
        [ "-m", "2048" ],
        [ "-cpu", "host" ],
        [ "-smp", "4,sockets=1,cores=2,threads=2"],
        [ "-chardev", "tty,id=pts,path={{user `serial`}}"],
        [ "-device", "isa-serial,chardev=pts"],
        [ "-device", "virtio-net,netdev=user.0"]
      ]
    }
  ]
}
```


And this kickstart file 'http/ks.cfg' for example:
```
install
lang en_GB.UTF-8
keyboard us
timezone Australia/Melbourne
auth --useshadow --enablemd5
selinux --disabled
firewall --disabled
services --enabled=NetworkManager,sshd
eula --agreed
poweroff

bootloader --location=mbr
zerombr
clearpart --all --initlabel
part swap --asprimary --fstype="swap" --size=1024
part /boot --fstype xfs --size=200
part pv.01 --size=1 --grow
volgroup rootvg01 pv.01
logvol / --fstype xfs --name=lv01 --vgname=rootvg01 --size=1 --grow

network --bootproto=dhcp --device=eth0
rootpw --iscrypted YourHashHere

%packages --nobase --ignoremissing
@core
%end
```
