### ISSUE TITLE
Feature: Allow a list of instance types for Amazon to bypass InsufficientInstanceCapacity 

### ISSUE THREAD

**Issue by janpieper** [mitchellh/packer#3924]
Most of us know the following message, if using Amazon AWS with `t2.*` instances:

```
==> amazon-ebs: Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient t2.medium capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get t2.medium capacity by not specifying an Availability Zone in your request or choosing eu-central-1b.
==> amazon-ebs:     status code: 500, request id:
```

The problem is, that Amazon only has a limited amount of instances of each type available and if this limit is reached, they respond with status code 500 (Error: InsufficientInstanceCapacity) and you need to change `instance_type` to another instance type in hope to not get the same error a second type because there aren't any `t2.large` anymore... Changing the value is easy, if you're running packer manually on your local machine, but if your CI is runnig it, you need to change the CI configuration or you need a new commit to your project to change the instance type.

What about allowing a list of instance types and packer will try them before failing.

``` json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "instance_types": [ "t2.micro", "t2.medium", "t2.large", "m3.medium" ]
    }
  ]
}
```

If `t2.micro` and `t2.medium` aren't available:

```
start t2.micro --> Error: InsufficientInstanceCapacity
start t2.medium --> Error: InsufficientInstanceCapacity
start t2.large --> Success
Packer --> Go on!
```

If there aren't any instances available for all specified instance types:

```
start t2.micro --> Error: InsufficientInstanceCapacity
start t2.medium --> Error: InsufficientInstanceCapacity
start t2.large --> Error: InsufficientInstanceCapacity
start m3.medium --> Error: InsufficientInstanceCapacity
Packer --> FAIL
```

Affected builders: `amazon-ebs` and `amazon-instance`

**Comment by rickard-von-essen** [comment]
Did you specify `"availability_zone": "eu-central-1a"` ? Or was it auto-selected by AWS?

**Comment by janpieper** [comment]
We are using a VPC, so we specified a `subnet_id` and no `availability_zone`.

```json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "eu-central-1",
      "source_ami": "{{user `aws_source_ami`}}",
      "instance_type": "m3.medium",
      "ssh_username": "ubuntu",
      "ami_name": "app-{{isotime \"2006-01-02T15.04.05Z\"}}",
      "associate_public_ip_address": true,
      "ssh_keypair_name": "Dummy",
      "ssh_private_key_file": "dummy.pem",
      "subnet_id": "subnet-da4496a2",
      "vpc_id": "vpc-4ab87f55",
      "security_group_ids": [
        "sg-f3147c8e",
        "sg-f61d718a"
      ],
      "run_tags": {
        "Name": "App (Packer)",
        "Build": "{{user `build`}}"
      },
      "tags": {
        "Name": "App ({{isotime \"2006-01-02\"}})",
        "Build": "{{user `build`}}"
      }
    }
  ]
}
```

**Comment by mwhooker** [comment]
I wonder if it would be better to accept a list of subnet IDs instead of list of instance types. I'm not sure I like the idea of a list of instance types, since I think that's the wrong level to solve this problem.

I think a list of subnets/AZs would be ideal, with an external process to rerun packer if it fails because of an `InsufficientInstanceCapacity` error.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. Not trying to shut you down or say your opinions don't matter or are bad. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
