### ISSUE TITLE
Packer crash: Build 'amazon-ebs' errored: unexpected EOF

### ISSUE THREAD

**Issue by mwarkentin** [mitchellh/packer#3944]
Packer version: `0.10.2`
Host: OSX El Capitan

### crash.log

https://gist.github.com/mwarkentin/6b07c02d283ef0fc1b1a687ff4e3721c

**Comment by rickard-von-essen** [comment]
This is fixed on master. Let me see if I can find the PR.

**Comment by mwhooker** [comment]
I think this is the issue https://github.com/mitchellh/packer/issues/3496

Looks like it was fixed in https://github.com/mitchellh/packer/pull/3865

If you feel comfortable building from master, it should be fixed for you. If you want help with that, feel free to reach out here.

We'll try to make a new release soon.

**Comment by mwarkentin** [comment]
@mwhooker Thanks! I've only seen it occur the one time, so I'll probably stick with the official release for now. If it crops up again I'll look at building from master.. thanks!
