### ISSUE TITLE
Packer VM image creation for opennebula.

### ISSUE THREAD

**Issue by william-graphsql** [mitchellh/packer#3963]
Hi packer team, I am trying to create VM image and make it work in opennebula, however, seems that you don't have support for this platform, like Amazon EC2 or Microsoft Azure. May I ask do you have plan to support this? If not, how much efforts do you estimate it will take to migrate the image created by packer to opennebula? Thanks!

**Comment by mwhooker** [comment]
hi @william-graphsql,

I'm not very familiar with opennebula, but it looks like it should run both vmware and qemu images (using the vmdk and qcow2 image formats). Packer can produce these types of images with https://www.packer.io/docs/builders/qemu.html and https://www.packer.io/docs/builders/vmware-iso.html .

We currently have no plans to support opennebula, but given that we can export a supported image, it shouldn't be too difficult to use some additional tooling to import them to opennebula.

closing this for now

**Comment by william-graphsql** [comment]
Thanks for the reply, @mwhooker , I will spend some time figuring out how to make it work then, thanks!

**Comment by FlorianHeigl** [comment]
For some reason I keep ending up in this issue but never commented the obvious thing.

OpenStack has a builder module. OpenNebula not. Why exactly is that?
Admittedly one big difference is that no one created a fund with millions of USD for marketing OpenNebula, while such a fund existed for OpenStack.

In 2016 OpenNebula was the more mature and widely used product. Even today the number of OpenNebula installs likely still exceeds OpenStack ones, with clouds going to over 300.000 cores (real ones, not vCPUs). 
Yes, the ecosystem is a lot smaller, but also more reliable, you don't have yet another vendor dropping out yearly (Pre-RedHat IBM, HPE, SUSE and likely a few I can't even recall). 
Plus, everything is written in ruby, which matches i.e. Vagrant.

Can I ask you to please discuss internally if it's possible to revisit that roadmap decision, and maybe gather the actual reasons for to do or not to do it? Maybe it's super complicated and not feasible. And of course we can hack something.
But, as far as I can see, the whole Hashi product palette is built around _not hacking something_.
So why is it in best interest of everyone to default to hacking something, in this case?

**Comment by SwampDragons** [comment]
The reason we have an OpenStack builder instead of an OpenNebula one is that a community member decided to spend the time to build the OpenStack one. We've never had someone step up to create an OpenNebula one. 

Packer is widely used, but it's a small project in terms of the number of full-time engineers working on it; basically all of the OpenStack work has been contributed by the community rather than by HashiCorp-paid engineers (of which there are currently two, and at the time this issue was closed, mwhooker was the only one). I have nothing against the idea of an OpenNebula builder or an OpenNebula-import post-processor, but we don't have the internal team bandwidth to create one.

That said, if someone from the community wants to create a third-party OpenNebula builder, I'd love to help by reviewing it and providing links to it on our website.

**Comment by FlorianHeigl** [comment]
Hey, thanks for the insights.
Lets suppose I would find a way that the builder is created and passes review, how would it have a chance of being upstreamed? is equal functionality to others sufficient? is there a doc showing contrib requirements?

**Comment by SwampDragons** [comment]
That's kind of a tricky question. Right now, I'm not merging any more builders, regardless of their quality, because with only two people we're already overwhelmed with the maintenance of what we have. The whole point of creating Packer as a plugin-based system was to allow the community to create and maintain their own builders when Packer couldn't keep up with maintaining them. Historically we've been really permissive about letting people merge their own builders and then just saying "yes this is in the Core repo but it's not being maintained by the HashiCorp engineers" but I think that is kind of a crummy distinction to make and I'd prefer not to make that bad situation even more confusing by merging another five or ten builders which won't have anyone maintaining them. 

Internally, it's a middle-to-long-term priority of mine to have a better registry of community-maintained builders something kind of like the way Terraform does with providers and modules. The idea would be that if you create an OpenNebula builder, users can call "Packer init" to pull down the OpenNebula plugin from your repo and it should Just Work. That way it can be used with Packer, users don't have to worry about compiling any extra binaries, and the mental overhead of using the community builders is basically the same as using the ones that ship with the core. 

We don't have docs showing contribution requirements, but I can link you some more docs about creating plugins if you're interested.
