### ISSUE TITLE
RFC: Expose generic SSH / WinRM proxies for provisioner

### ISSUE THREAD

**Issue by rickard-von-essen** [mitchellh/packer#3969]
This has been discussed in different issues.
Maybe we should provide a adapter/proxy that could be use with `shell-local` (or other provisioners) to allow running tools local targeting the host that use SSH/WinRM.

Example:

```json
{
  "type": "shell-local",
  "inline": [ "git push ssh://git@localhost:$SSH_PORT" ]
}
```

Where $SSH_PORT is a port where the adapter receives connections and forwards it to a SSH Communicator. The nice thing about this is that it would hide all the details from the provisioners about the connection so for example using a bastion host would be transparent.

This would require us to extract the excellent work of @bhcleek on the `ansible` provisioner and add a WinRM adaptor but that should be trivial since WinRM use HTTP as bearer.

Thoughts, comments, etc? Would this be useful somewhere else from `ansible` or `shell-local`?

Related to #3911

**Comment by rickard-von-essen** [comment]
Ping @bhcleek @mwhooker 
FYI @cbednarski

**Comment by cbednarski** [comment]
The biggest objection I have is that this opens up many host-level dependencies required to run your build, but packer has no way to manage or know about these things so your build is inevitably going to stop working and potentially be unfixable.

E.g. "this build only works on a Windows 7 host with a linux guest when you have X, Y, Z, and Q installed and configured on Windows". That's a horrible UX, and I think it fundamentally violates packer's design.

My second biggest objection is that -- even if the above is solely the user's problem -- this will open up a long tail of edge cases that we need to fix, and I would _personally_ prefer to spend the time on other features.

**Comment by rickard-von-essen** [comment]
> The biggest objection I have is that this opens up many host-level dependencies required to run your build

I agree with this, it will tie the usage harder to the host. But at least in some in some cases depending on the host is fine (i.e. `ansible` or `shell-local`). But in general it's bad.

A middle ground could be to create this functionality for provisioner plugins to use but _not_ expose it in `shell-local`. Just to simplify implementation of similar plugins as `ansible` that runs from the host.

The pro of exposing to the `shell-local` is that it could solve some use cases for people where there is a "missing" plugin. This is also a drawback since it decreases the pressure on writing that plugin.

**Comment by bhcleek** [comment]
I understand why people want something like this, but I tend to agree with @cbednarski; the constraints that Packer imposes are useful, and this would remove a lot of those constraints at the cost of introducing edge cases. The counter-argument, though, is that `shell-local` has already introduced the complexities that @cbednarski is worried about.

Now that the `ansible` provisioner can use scp, it makes sense to me to extract the SSH adapter to its own package so that it's available to other plugins.

**Comment by cbednarski** [comment]
> shell-local has already introduced the complexities that @cbednarski is worried about.

Exactly. But I don't think we should use this as justification to make that mistake again! That's sloppy reasoning. I learned anything from that experience, it's that there are times we should say "no" to a feature because it is a marginal value add but greatly increases complexity and maintenance burden.

I think there is a tendency in software development to say, "I don't know what the best thing is here so I'll just add an option." The second best thing you can do is choose a sensible default. The best thing you can do is make a decision about which approach is better and not include an option at all. This is what it means to design software.

I think there is also an expectation that an open source project should go in whatever direction a person wants it to go simply because it's convenient in that case. If that direction is anathema or unrelated to the project's vision it just doesn't make sense to put it here.

As an example, there are many feature requests to make Packer obviate the use of Make or other tools. Today you can use other tools like Make or CMake or whatever to build a project, and you can use other tools like buildbot or Jenkins to run Packer. Packer does not need to absorb all of these responsibilities to be useful. Further, the effort that goes into making Packer more like Make or Jenkins detracts from the core features that differentiate Packer from those tools, and those core features are what make Packer useful in the first place!

The question we should answer here is not whether this feature makes sense in isolation, but whether it makes sense in a holistic view of Packer. Does this feature add to Packer as a whole? Does this feature complement other Packer features? Does it behave in a consistent way with other Packer features? I personally don't think so.

I think the primary justification is an edge case on an edge case. IMO it will be very hard for users to get this feature to work, and even more difficult to use it correctly. It adds _marginal_ value but at a significant cost in complexity. In the big picture, there are other pieces where we could get much better ROI, like integrating Hyper-V. This is a lot of work but it is perfectly in line with Packer's core design.

Anyway, enough ranting on my part. Ultimately I am deferring this decision to @mwhooker who is our primary maintainer, but I wanted to explain why I have resisted adding this type of thing thus far.

**Comment by bhcleek** [comment]
I completely agree. I wasn't trying to make the argument that we should do this. My only objective in pointing out the counter argument was to make sure it was considered....

**Comment by rickard-von-essen** [comment]
> The question we should answer here is not whether this feature makes sense in isolation, but whether it makes sense in a holistic view of Packer...

Definitely agree, that is why it's important share the holistic view of Packer.

> [shell-local] But I don't think we should use this as justification to make that mistake again!

This is a good point. If we see `shell-local` as a provisioner not in line with Packers philosophy we can say no to feature requests for it which moves it further from this philosophy. (And maybe over time deprecate it or discourage it's usage)

> Now that the `ansible` provisioner can use scp, it makes sense to me to extract the SSH adapter to its own package so that it's available to other plugins.

@bhcleek That would be fine, or we can defer if until requested.

**Comment by rickard-von-essen** [comment]
@mwhooker anything to add? Otherwise just close it and we can conclude something like:
- We don't wont to expose this to the users (`shell-local`). 
- We could if needed extract the ssh adaptor from the `ansible` provisioner into a module that can be reused in another provisioner when the need arises.

A sidenote: is `shell-local` such a big step from what packer should be doing should be have a plan for deprecating it and eventually remove it? @cbednarski

**Comment by mwhooker** [comment]
I've mostly withheld comment because I don't have the context to weigh in meaningfully.

I'm not sure this buys us big enough gains to justify implementing. I'd be happy tabling this until after 1.0, when I can spend some more time thinking about it. Also fine closing it since there doesn't seem to be too much demand

**Comment by mwhooker** [comment]
A solution I think I'd prefer for the git push example is to have the user themselves set up the server on their guest. Perhaps the shell-local provisioner would have to be modified to have a guest host variable.

Still something I'd like to revisit after 1.0, but I want to rely on as few assumptions about the guest OS as possible.
