### ISSUE TITLE
apply ami_users to original region before processing ami_regions

### ISSUE THREAD

**Issue by glasser** [mitchellh/packer#4009]
packer version v0.10.0

Let's say I am running Packer to make an AMI with account A1 in region R1, and I also set `ami_regions` to R2 and `ami_users` to A2.

Packer will do operations in the following order:
1. Make AMI with A1 in R1.
2. Wait for it to be ready.
3. Copy AMI from R1 to R2.
4. Allow A2 to use it in R1.
5. Allow A2 to use it in R2.

Step 3 is a slow step, and there's no inherent reason that step 4 needs to come after step 3.  In my current setup A1 is our prod account and A2 is our dev account; I always want to try to test my AMI as soon as possible in our dev account in R1, so it's annoying to have to wait for the copy to finish for that to happen.

As a workaround I can make A1 be the dev account and A2 the prod account, of course, but it would be nice if this just worked.

**Comment by mwhooker** [comment]
yeah I agree this would be useful.

The way packer works right now, though, makes this type of thing very difficult.

One idea is to use the shell post-processor to do steps 3 and 5. That way you could use the AMI from A2 as soon as it's built.

As a matter of course, though, I would recommend doing all development work on the dev account, and copy to prod. Could save yourself some headaches.

However, this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. Not trying to shut you down or say your opinions don't matter or are bad. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
