### ISSUE TITLE
Add option to fail shell provisioner if remote disconnects

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#4011]
see context here https://github.com/mitchellh/packer/issues/4006#issuecomment-253862616

ideally add an option like `fail_on_disconnect` which would cause the provisioner to fail if the remote host disconnects us. The default behavior should be not failing, to preserve BC.

a more idiomatic option would be something like `expect_disconnect`, but we'd need to figure out how to get the default value to be `true`. We could make the config value a `*bool` type, and if it's nil, set to `true`, but we don't follow that pattern anywhere else in packer afaik. Here's a [consul example](https://github.com/hashicorp/consul/pull/2320/files) of that pattern in action.

**Comment by rickard-von-essen** [comment]
I think **_correctness_** is more important than _backwards compatibility_ . And the correct thing to do if the ssh connection drops is to treat it as an error. If would like to tolerate disconnenctions that should be _explicit_ not _implied_. 

And yes this will bite some people that do reboot in their scripts and there is no way a migration for them (i.e. `packer fix`) since we can't reliably parse all there scripts and determine which must allow disconnect.

So I'm voting for `expect_disconnect` but with default value of `false`.

**Comment by mwhooker** [comment]
I tend to like correctness too, but I have a hard time justifying breaking BC for it. What if we added the option, but made it default to true (don't fail on disconnect), and then after 1.0 next year we change the default to false? I think we can get away with breaking BC when moving from 1.0 to 1.1.

I'd like to get some more input on this. cc @cbednarski

**Comment by cbednarski** [comment]
> So I'm voting for `expect_disconnect` but with default value of false.

Semantically I like this. However, I expect this change will break a large percentage of currently working packer templates (25-75%). There may be a way to upgrade this cleanly but we will need to be creative.

I think we should take a step back and consider the following: What problem are we trying to solve? In some **rare** cases an SSH connection disconnects unexpectedly and the build fails. We are proposing making a change that we know will make **many** currently working builds fail unexpectedly (when rebooting or shutting down the machine).

The pragmatic approach here is to not break things, or to break fewer things. So IMO in this situation if you want semantics to win you must figure out a clever way to make this work correctly without breaking everyone's stuff.

If we dig a bit more into the weeds I think the proposed change does not really even help us that much. Most provisioners are going to do a ton of work and end with a restart or shutdown. The thing is, even if we say "we expect this build to disconnect **at the end**" we don't actually know when "the end" is supposed to happen. If, in the case of a bug or a weird error, ssh disconnects at the wrong time, we still are not going to know that it was an accident! We will be expecting the script to reboot and we will assume that happened and continue on as normal, even though we got disconnected early.

So in essence, we haven't fixed anything. We've just added a new config option that made things more complicated. If you look at the docs there is a [section about reboots and edge cases](https://www.packer.io/docs/provisioners/shell.html) and the bottom line is that this is probably going to be broken in some way no matter what decision we make, so in that case I am inclined to say "just leave it alone".

I have a few ideas about how we could maybe fix this:

1. Scan the provisioner script for reboot, restart, poweroff, shutdown, etc. and hint that the user should supply a new option, or _just make packer do the right thing automatically_ and add an escape hatch to control this manually.

2. Add a config version to the packer template. This will allow us to automatically run packer fix and insert default values as a one-time thing, based on whether the rule is set to run when upgrading from nil to 0.11 or from 0.11 to something else.

3. In conjunction with the proposed `expect_disconnect` change, also update the docs to say that best practice is to run reboots alone in their own specially-marked provisioner so we can correctly detect disconnect problems at other times.

4. Add some kind of checkpointing to the provisioner so we can see whether it ever successfully completed, like writing an empty file with a random filename that packer knows at the very end of the provisioner.

Again, all of this is a lot of work and takes time to think about, implement, test, see whether it is horrible or not in practice. In subtle cases like these you have to combine a good understanding of the problem with a clever solution, and I have neither. My strong inclination is to say "just leave it alone" unless you have both of those, because otherwise there will be a long, sad thread about how people upgraded to packer 0.11 and everything broke. Sometimes that's OK. But we should have a good reason to do it. Maybe this is a good reason. I'm not convinced, but you have to convince @mwhooker, not me. ;)

----

Slightly related:

We had a long convo in chat about how to differentiate between default false and explicit false. This is currently impossible in packer but it would make solving this type of problem significantly less kludgey.

This is the kind of thing we would like to tackle post-1.0 by adding a new / alternate config syntax that has cleaner semantics and provides other config-related features people have been asking for, so if that would help here maybe we should defer this until later when we can make a cleaner fix.

**Comment by berney** [comment]
How about you break backwards compatibility by leaving the new functionality of a disconnect being treated as a failure, add a template option `fail_on_disconnect` but also add a command line option to treat disconnects the old way (exit code 0 / success). That way people using old templates that are now broken can easily add the command line switch to get the old behaviour back, and people with newer templates can surgically apply old behaviour to provisioners expected to disconnect.

**Comment by cbednarski** [comment]
@berney Thanks for the suggestion. In the past we have done this lower-level twiddling via environment variables. I think these are best used sparingly, though, because you may later end up with a bunch of weird configuration that is required for a build but is not codified in the template, so it is hard to get your environment setup correctly.

To be clear, I am not opposed to changing the template syntax to do the right thing here, but I want to emphasize that 1. we will break many (majority, probably) of builds and 2. we should have a clear way to fix this (preferably automatically).

I've dug into the code here and the problem lies in the SSH code in the go std lib which returns a `ExitMissingError`.

> ExitMissingError is returned if a session is torn down cleanly, but the server sends no confirmation of the exit status.

This is inherently ambiguous and up until this point we have made the assumption that this type of error means a box was restarted or shutdown. This is obviously not the only case where we could get this error (network problem, unexpected VM failure, etc.) but it is impossible to differentiate between those types of exit scenarios without additional information which we currently don't have.

We can certainly be stricter about how we handle the reboot case. I think, for example, that for the sake of correctness, it is reasonable to make this change, from:

```
  "provisioners": [
    {
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -E -S bash '{{.Path}}'",
      "script": "scripts/packages.sh",
      "type": "shell"
    }
  ],
```

to:

```
  "provisioners": [
    {
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -E -S bash '{{.Path}}'",
      "script": "scripts/packages.sh",
      "type": "shell"
    },
    {
      "inline": "echo 'vagrant' | {{.Vars}} sudo reboot",
      "type": "shell",
      "expect_disconnect": true
    },
  ],
```

But this also requires a change to [packages.sh](https://github.com/cbednarski/packer-ubuntu/blob/master/scripts/packages.sh) and is somewhat discongruous in terms of composing a script because it is awkwardly split into separate parts. If this reboot is buried e.g. in a chef provisioner it's going to be even harder to tease out or specify `expect_disconnect` with the appropriate granularity.

On the other hand we could do something like this. changing from:

```
  "provisioners": [
    {
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -E -S bash '{{.Path}}'",
      "script": "scripts/packages.sh",
      "type": "shell"
    }
  ],
```

To:

```
  "config_version": "0.11",
  "provisioners": [
    {
      "execute_command": "echo 'vagrant' | {{.Vars}} sudo -E -S bash '{{.Path}}'",
      "script": "scripts/packages.sh",
      "type": "shell",
      "expect_disconnect": true
    }
  ],
```

Where we can automatically fill in `expect_disconnect` _and_ `config_version` at the same time. If `config_version` is already there we don't need to do anything. The user also doesn't need to do anything to get their config working with the new version of packer, but they are given a clean upgrade path. When they ask "Why does packer 0.11 add `expect_disconnect` to my config?" we can have the conversation about correctness and they can opt in to the better approach, without causing their builds to break.

As I said these are not reasons not to fix the problem, but I do think they must inform the solution because a naive solution will make it very tedious for users to update their configs.
