### ISSUE TITLE
builder/amazon-ebs: Packer key pair not cleaned from image upon completion

### ISSUE THREAD

**Issue by vancluever** [mitchellh/packer#4045]
- Packer version from `packer version`: `0.11.0`
- Host platform: `darwin`

Just noticed this on one of our instances tonight: Looks like the public key is not being deleted from the built instance before the AMI is created:

```
root@ip-1-2-3-4:/home/ubuntu# cat .ssh/authorized_keys 
ssh-rsa KEY_HERE packer_uuid-here
...
```

Not that this is completely 100% risky since the key is deleted, but still, would be prudent to make sure that all traces of it were gone from built artifacts.

**Comment by rickard-von-essen** [comment]
Packer doesn't doesn't modify the content of you image. You have to handle whatever cleanup you need your self.

If you care you can put something like this last among your provisioners:
```json
        {
            "type": "shell",
            "inline": [
                "rm /home/ubuntu/.ssh/authorized_keys"
            ]
        }
```

**Comment by vancluever** [comment]
Although it might seem a bit tough to do this at the point in time it may need to happen, may I ask why the wontfix? amazon-ebs deletes the key pair on cleanup via API, so why can't it SSH in to remove its key entry from authorized keys at the same time?

At the very least, it should be documented so that people don't leave keys hanging around. Again, the likelihood of there being an actual security issue because of this is low, but it just looks kind of sloppy.

**Comment by rickard-von-essen** [comment]
There are a number of reasons for not building this into the builder.

1) Builders are OS agnostic, creating and destroying the temp keypair is a AWS feature which is the concern of the `amazon-ebs` builder.
2) `$HOME/.ssh/authorized_keys` is a implementation/configuration detail of OpenSSH. We don't know anything.
3) There is no security issue since the private key is ephemeral. 

I'm open for reviewing a PR with some more info about AWS and keypairs.
