### ISSUE TITLE
Feature request: use image families as source_image in GCP

### ISSUE THREAD

**Issue by dvianello** [mitchellh/packer#4100]
As a logical follow-up of #3503, it would be extremely helpful if packer could use an image family as the `source_image` of a build.

This makes particular sense when using as `source_image` an image from projects like CentOS, which ships out updated images every so often. This will allow to automatically pick the latest version of the image, without changing the image id manually every time.

(More details / initial discussion in #3503)

**Comment by vbatoufflet** [comment]
Hi All,

Will you be interested by a PR for this support?

If yes, WDYT of testing for the existence of the image by family name as a fallback if the basic method failed?

Regards,
Vincent

**Comment by pschultz** [comment]
So, I was just trying to use image families with docker-machine. They also don't have an explicit parameter for families, but accept the image URL. Turns out that the URL can be changed so that it works as an image *name* [1]:

    https://www.googleapis.com/compute/v1/projects/my-project/global/images/family/my-family

Notice the additional /family/ segment. This is a wild guess, but maybe this already works in packer?

```
{
  "builders": [
    {
      "type": "googlecompute",
      "source_image": "family/centos-7",
      ...
    }
  ]
}
```

I'm not in a position to try it right now. Just wanted to write it down before I forget.

[1]: https://godoc.org/google.golang.org/api/compute/v1#AttachedDiskInitializeParams

**Comment by dvianello** [comment]
@vbatoufflet, I'm not the biggest expert around, but your approach makes sense! 👍
