### ISSUE TITLE
Feature Request: Multi AZ selection with Spot Instances (AWS) using Spot Fleet of Target Size 1

### ISSUE THREAD

**Issue by CpuID** [mitchellh/packer#4146]
Currently you can only specify a single AZ/Subnet when doing spot instance builders (using amazon-*) in a VPC. There seems to be the ability to specify multiple Subnet IDs and AZs using the AWS console to launch instances in any AZ within a single VPC, on a single request.

This would be another workaround for https://github.com/mitchellh/packer/issues/4145 where some AZs have spot prices of 5-10x the current on-demand pricing, whereas other AZs have prices well below the on-demand price.

You could then retain a static `spot_price` value of less than the on-demand price (eg. for a c4.large in us-east-1 with on-demand at 0.105, you might set 0.08), and increase the chances of a successful fulfilment without getting a price-too-low due to static AZ selection picking an overpriced AZ.

Example request submitted via the console:

![capture2](https://cloud.githubusercontent.com/assets/916201/20162889/e06e1104-a743-11e6-94e6-3f9df8cac476.PNG)

To achieve this, I think the logic [here](https://github.com/mitchellh/packer/blob/master/builder/amazon/common/step_run_source_instance.go#L196-L263) would need to change from using `RequestSpotInstances` to `RequestSpotFleet` with a `TargetCapacity` of 1 instance.

Thoughts...?

**Comment by CpuID** [comment]
This would probably require input parameter changes to the builder for `subnet_id` and `availability_zone` (probably needs a map of AZs and subnets respectively to feed in to [SpotFleetRequestConfigData](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html))

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. Not trying to shut you down or say your opinions don't matter or are bad. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
