### ISSUE TITLE
Copied AMIs Missing Tags

### ISSUE THREAD

**Issue by bnied** [mitchellh/packer#4159]
- Packer version: v0.11.0
- Host platform: Ubuntu 14.04 x86_64 & macOS 10.12 x86_64
- Debug log output: https://gist.github.com/bnied/8c3bb4fc720a384c1212deb6fbe2c0dd

When creating new AMIs, and copying them to other regions, the tags don't get applied, even though Packer claims they were applied.

**Comment by rickard-von-essen** [comment]
I can't reproduce this.

Could you see if it works if you correct the syntax, so that you have:
```json
"ami_regions": [ "us-east-1", "us-west-1", "us-west-2" ],
```

**Comment by bnied** [comment]
Giving it a shot now. Weirdly enough, the copies complete successfully, it's just the tags that are missing.

**Comment by bnied** [comment]
@rickard-von-essen so, no dice. Changing the format didn't change the tags.

I'm trying a build that uses the proper format for the `ami_users` to see if that makes a difference.

**Comment by bnied** [comment]
Closing. The issue seems to be that the tags are only visible to the owner AWS account, rather than the shared accounts. Thanks @rickard-von-essen!

**Comment by bayendor** [comment]
Any chance this can be revisited?  We build numerous AMI's that are copied to other AWS accounts we own (separated for security reasons), and have to update the tags on the AMI's with a script after the fact.  Would be great if we could post-process these with Packer.

**Comment by xbglowx** [comment]
Would be nice to have an optional flag to enable copying of tags when `ami_users` is specified.

**Comment by rickard-von-essen** [comment]
Actually it's not possible to copy tags available for another account. You can tag an AMI you can use in that account. But since we don't want to handle multiple accounts from Packer it's not possible. 

For people that want this my recommendation is that you parse the AMI-id from a manifest file and use that in a script to tag the AMI in your other accounts.

**Comment by xbglowx** [comment]
@rickard-von-essen fair enough. I wrote a wrapper script that uses the awscli to copy the tags. Below is the meat of it.

```
ami_tags=$(aws ec2 --profile "$source_profile" --region "$ami_region" describe-images --image-ids "$ami_id" | jq -c '.Images[].Tags')

aws ec2 --profile "$destination_profile" --region $ami_region create-tags --resources $ami_id --tags $ami_tags
````

**Comment by szinck** [comment]
What if there were a way to specify a role to assume in the other AWS account so that tagging could be done there?

I have my own contraption built that copies the AMI to other accounts and tags them, but without tagging I cant really use this feature.  Having a native feature would be much nicer than having contraptions.

**Comment by mwhooker** [comment]
@szinck That sounds reasonable, but I think the only way to see that get added is to write it yourself. It depends how complicated it ends up being, but I probably wouldn't have any problems merging something like that
