### ISSUE TITLE
WIMRM File Uploads fail with 500/access denied error 

### ISSUE THREAD

**Issue by dan-rose** [mitchellh/packer#4203]
- Packer Version 0.11
 - Windows 10
 - VMWare Workstation 11
- gist files
[Packer.log](https://gist.github.com/dan-rose/2dd33f30ec1ec566d74381cba9812b6b)
[JSON File](https://gist.github.com/dan-rose/cb67e195e0b2a75c02b8d3320a3fcca5)
 - packer build -force -only=2012r2_vmware_NoUpload .\windows_2012_r2_vmware.json
 - Server WMI Settings configured in build process
```
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="2048"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/client/auth '@{Basic="true"}'
```

Issue: **Error uploading file to $env:TEMP\winrmcp-05e8c67c-90fc-4807-6ec8-1887032aef15.tmp: http error: 500**

I can run a successful packer build on my workstation once sometimes twice - but after that i get this error when trying to upload files via WINRM to the 2012R2 server. It starts uploading, but then dumps out after a period of time. 

I am assuming that their must be some local WINRM limit that i am hitting - but i don't know what it is.. Has anyone else seen this?

My current way to fix this is to log out and back into of my Windows session - which i guess resets any counter.. 

       ######################################

I also have non breaking issue when running this provisioner
```
{
        "type": "powershell",
        "inline": [
          "new-item c:\\windows\\packerfiles -itemtype Directory"
        ]
}
```

The command is run successfully, but the process produces some other errors 
Provisioning with shell script: C:\Users\drose\AppData\Local\Temp\packer-powershell-provisioner313265219
```
    2012r2_vmware_NoUpload: vmware-iso : The term 'vmware-iso' is not recognized as the name of a cmdlet,
    2012r2_vmware_NoUpload: function, script file, or operable program. Check the spelling of the name, or
    2012r2_vmware_NoUpload: if a path was included, verify that the path is correct and try again.
    2012r2_vmware_NoUpload: At line:1 char:30
    2012r2_vmware_NoUpload: + & { $env:PACKER_BUILDER_TYPE=vmware-iso;
    2012r2_vmware_NoUpload: **$env:PACKER_BUILD_NAME=2012r2_vmware_No** ...
    2012r2_vmware_NoUpload: +                              ~~~~~~~~~~
    2012r2_vmware_NoUpload: + CategoryInfo          : ObjectNotFound: (vmware-iso:String) [], CommandN
    2012r2_vmware_NoUpload: otFoundException
    2012r2_vmware_NoUpload: + FullyQualifiedErrorId : CommandNotFoundException
    2012r2_vmware_NoUpload:
    2012r2_vmware_NoUpload: 2012r2_vmware_NoUpload : The term '2012r2_vmware_NoUpload' is not recognized
    2012r2_vmware_NoUpload: as the name of a cmdlet, function, script file, or operable program. Check the
    2012r2_vmware_NoUpload: spelling of the name, or if a path was included, verify that the path is
    2012r2_vmware_NoUpload: correct and try again.
```

I have highlighted the issue - its being caused when the variable $env:PACKER_BUILD_NAME is being created. But its failing because the value is not being passed within a set of **" "**

Any assistance - especially with WINRM issue is gratefully received

Dan

**Comment by DanHam** [comment]
Hi Dan,

First things first. The 'non breaking error' you are seeing with the Powershell provisioner:

>2012r2_vmware_NoUpload: vmware-iso : The term 'vmware-iso' is not recognized...
 
This issue has now been fixed, so at least that's one thing out of the way.


On to the WinRM error:

> Has anyone else seen this?

Unfortunately, yes. Same as you - I sporadically see a 500 error when uploading the VMware tools ISO to the guest. Everything works fine the majority of times I run the build. However, every so often I run across the exact same issue you are describing. Like you I've only seen this building S2012r2; thankfully I haven't seen this with my S2016 build.

I have fairly similar WinRM settings. However, I'm not entirely convinced that the issues we are seeing are related to WinRM limits. The settings we both have configured are fairly generous and shouldn't be causing any issue.

Can I ask if you restart the WinRM service after changing the settings? If so I was wondering if it is possible we are coming across some sort of race condition where, having just restarted WinRM, we then immediately configure our firewall to allow access. Packer is then _sometimes_ able to make a connection _before_ the WinRM service is fully operational - hence the sporadic 500 Access Denied error we are seeing.

While I was looking into this I also noticed I was (stupidly) ['configuring UAC to allow privilege elevation in remote shells'](https://support.microsoft.com/en-us/kb/951016) _after_ I had enabled the firewall rule. I'm not sure if Packer automatically requests privilege elevation when uploading the VMware tools ISO; however, I figured that if it did, the required setting that allows this should be in place _before_ it could possiby do so. I've fixed this now and am going to test with that for a while to see if that has fixed this issue for me. 

If the above doesn't fix the issue, I think I will try and pause execution of the script briefly - just  before I allow Packer access - to try and ensure the WinRM service is fully operational.   
 
See the (corrected) script I use to set up WinRM [here](https://gist.github.com/DanHam/63cbb88ef98ea7bf90c28c334dbec014)

All told, I'm not especially convinced this is a Packer issue _per se_, but rather something to do with WinRM and/or the way we are handling the set up. I would be grateful to hear any thoughts you have on this and would be especially grateful to hear back on any fix or explanations that you may find.

Dan H

My info:

Packer version: v0.12.1.dev
Host platform: Mac OS X 10.11.6
Virtualbox: 5.0.26
VMware Fusion: Professional Version 8.5.2 (4635224)

**Comment by DanHam** [comment]
OK. So I was just taking a look at #4069 (the fix for your 'non breaking issue') and it looks like the VMware tools upload doesn't require an elevated shell. This means that the mistake I mentioned above probably isn't the culprit here.

As such I'm now going ahead with trying the pause I mentioned instead to see if that helps.

Dan H

**Comment by dan-rose** [comment]
Hello Dan,

Thank you very much for getting back to me with a detailed answer. 

> Can I ask if you restart the WinRM service after changing the settings?

I am indeed restarting the service.. I figured that it would be necessary to do so in order to make sure the configuration of the generous settings stuck.. 

I had read in some other posts about a possible race condition, and so already put a couple of "pause_before" options in the config json just as a precaution (also as an aside i disable all firewalls as part of my autounattend.xml) 

Perhaps I need to increase the amount of time I need to add in these pauses - or maybe, in the script that configures WIRM, a "While" loop that checks the status of the service.

Interestingly the upload of my files occur after I perform an additional act using the powershell provisoner, so I wonder whether it might not be a race condition causing this.....

I have just seen an email with your additional update re: the UAC - thanks! 

I was trying to test this today myself - but as of this morning my PC seems unable to use WINRM to connect at all to the windows build and times out! 
**2016/11/25 12:41:25 packer.exe: 2016/11/25 12:41:25 [DEBUG] connecting to remote shell using WinRM
2016/11/25 12:41:25 packer.exe: 2016/11/25 12:41:25 [ERROR] connection error: http response error: 401 - invalid content type
2016/11/25 12:41:25 packer.exe: 2016/11/25 12:41:25 [ERROR] WinRM connection err: http response error: 401 - invalid content type**

I have since updated my build of win 10 - in order to try an rule out any underlying OS issues. I will try again, with your win-rm script and see what happens

I agree that its likely to be a WINRM, issue, but also perhaps the way it is being "invoked"

Thanks again for you time - I will try and update soon

Dan

**Comment by dan-rose** [comment]
Just as a quick note - reviewing your WinRM setup - there are two thing that you do differently to me
1. deleting pre-existing WinRM listeners
2. Increasing the number shells / concurrent sessions.. 

Have these fixed previous issues??

Dan

**Comment by DanHam** [comment]
> Have these fixed previous issues??

No, but...

> deleting pre-existing WinRM listeners

This came about because I chose to create the listeners manually rather than using ```winrm quickconfig```. Deleting any existing listener simply means I start with a clean slate. 
I don't use ```winrm quickconfig``` as it automatically opens up the Windows Remote Management firewall ports for you at the same time. This is something I don't want here - Packer would be able to connect and would begin to upload the VMware tools. The later command to restart WinRM would then cause an error in the upload process.

 > Increasing the number shells / concurrent sessions..

I have no justification for this other than the default of 5 seemed a bit tight!! I've probably seen this in someone elses config and thought 'increasing the limit looks like a good idea' 😃. I may now take that out or at least reduce it down a bit. Looking at it now, 30 seems a bit high!

As an aside I have the MaxProcessesPerShell set to 30 as well. I've taken a look at [Packers WinRM communicator](https://github.com/mitchellh/packer/blob/master/communicator/winrm/communicator.go) and it _looks_ as though it sets a hard limit of 15 (the default) - see line 158. I could of course be wrong on that since my knowledge of Go isn't great! However, I may just go ahead and take that configuration change out too.

Dan H

**Comment by dan-rose** [comment]
The issue with  **http response error: 401 - invalid content type** is caused by VMware workstation being borked on my machine.. Can use virtualbox fine

However, with your settings and a 2 min pause after starting winRM, I am stiill getting the 500 error when uploading files.. It starts to upload - and after a while fails. I also note that the files i am uploading are pretty small the largest is 47mb. It starts with some small hardening files. which tiny (940K) and these take "**a long time"** to upload - after which it dies.. Everything else is fine.. If i remove this part of the config - I have no problem

I will attempt to log out of my machine and back in and try again.. - Should this make it work isn't this suggestive of an issue with GO winRM library ??

Thanks again 

have a great weekend

**Comment by dan-rose** [comment]
Definitely sorted by rebooting or logging out of my workstation. This would suggest there is a value locally created and then exceeded causing this 500 occur. My next test will be to see, whether once this occurs, i  am unable to packer build a machine with a ***different*** name. I will also try and use WinRM to connect to other servers on my domain to see what the result is once the 500 occurs - I might get a "nicer" error message

**Comment by DanHam** [comment]
Hi Dan,

I've just had this error bite me in the proverbial 3hrs into a Windows 2012 R2 build! As you've already found, the pause between restarting WinRM and enabling network access has made no difference. At least we can both rule that theory out.

Note that the builder I was using was the virtualbox-iso builder. In other words this is not VMware specific.

You're right about that error message - it's not exactly helpful! I wonder if there is anything the Packer devs can do to help out? e.g. adding some error handling into the WinRM communicator or adding some additional debugging output?

With regard to rebooting or logging back out and back in again sorting the issue - this doesn't seem to make a difference to me. I am using a Mac rather than Windows, so maybe the implementation is slightly different - but I can encounter the error during a build and then, without logging out or rebooting, run the build again immediately afterwards but this time have it complete successfully.

So far we seem to have ruled out the possibility of this being tied to a single platform e.g. Windows or Mac, or of it being tied to a single builder e.g. VMware or Virtualbox. Adding a pause between restarting WinRM and allowing Packer access had no affect - both of us are still seeing sporadic failures.

Note that I am unable to reproduce this with any regularity - even after I've experienced the failure whether or not I see it on the next attempt is seemingly random. Are you saying that your builds repeatedly fail _every time_ after you've seen the issue the first time?

**Comment by dan-rose** [comment]
> Are you saying that your builds repeatedly fail every time after you've seen the issue the first time?

Ummm now you're asking.. I'll need to be sure of that before being more definitive. Initially I seem to remember that I thought its was a problem with my shell, because a restart seemed to fix it. Then I started resorting to logging out and this did seem to solve it, however because it takes 10mins to fail, and that also I am trying to work on and actually deliver something (!)  - I haven't as yet been that scientific. :) 

I will try and break it again this afternoon then do some further testing - including some more generalized WINRM testing (although as you say its not platform specific, so this might not be worth it) - and report back.. 

I would like to add to others that might be listening, that this current "flakiness" concerns me at the moment, and although we could perhaps look at other work around processes for getting files onto boxes - e.g putting them on an HTTP server and pulling them down as needed -  it does reduce my overall confidence.

Thanks Dan for your continued interest

**Comment by dan-rose** [comment]
whoops!

**Comment by DanHam** [comment]
OK. Definitely confirmed from my end... there is no repeatability. I run once and the build breaks with the 500 error. I run the same build again immediately afterwards and it completes with out error.

I'll be interested to find out how you get on. Long and short though, I don't think this is related to any local shell limits or the like on the *hosting* machine - otherwise I think we'd be seeing differences in behaviour between platforms e.g. differences between Mac hosts and Windows hosts. Much more likely now is some weirdness going on with WinRM or, as you have previously suggested, something going on with the Go WinRM library or Packer WinRM communicator.

I'm starting to run out of ideas for what could be causing this. This is very frustrating. Additionally I can't believe that we're the only two people seeing this.

**Comment by trodemaster** [comment]
I had to give up on winrm file uploads a few months ago. Not only is the method flakey it's very slow for larger files. This is due to how the mechanism works in the upstream masterzen winrm library. Using an external http server and then a powershell download script is much more reliable and faster. Winrm file upload works well for moving some scripts or tiny files but not large files. 

That said I also filed this feature request to allow packer to serve up files from it's local http server which would be more elegant on virtualbox/qemu/VMware Fusion/workstation builds. Leave some comments on that issue if your supporting that approach. 

Thanks,
Blake

https://github.com/mitchellh/packer/issues/2869

**Comment by DanHam** [comment]
@trodemaster Thanks for the info with regard to the WinRM library and I've given your feature request a 👍. I can definitely see the utility in having that feature.

My problem is that it's not actually me uploading files via WinRM - it's Packer. Unfortunately, its when Packer uploads the tools ISO's (VMware tools and Virtualbox Guest additions) over WinRM that I see the failure. While I can avoid uploading the tools for Virtualbox by chosing the 'attach' method rather than 'upload', I can't do the same for VMware as there is no 'attach' method.

What is incredibly annoying is that for my build the upload of the tools ISO's occurs after the whole Windows Updates thing has taken place - namely several hours into the build!

**Comment by dan-rose** [comment]
Thanks too. I've given the built http server an upvote.. I can see this being useful - however we also intend to build directly onto ESXI and so i don't think this would solve it.. I will investigate using an separate accessible HTTP server from which to pull the files. 

Just regarding the WinRM issue itself - I have found that its related to the volume of files being uploaded - when its just some smaller files its fine, (slow, but fine) but as soon as the amount and size increases (like the guest additions) it fails,  I use the attach method for vbox too. 

It is a shame to have to design workarounds to this in built upload method and I know how annoying it is to have to start over again!

I did find this article about splitting off different stages of the build - am am planning on having a look at my own version of this for local builds -[ link here](https://hodgkins.io/best-practices-with-packer-and-windows#step-by-step )

**Comment by mwhooker** [comment]
One thing to note is that the error windows is giving us is that `Access is denied.` to the `$env:TEMP` directory.

**Comment by mwhooker** [comment]
@dan-rose there's been some significant update to packer/winrm. It would be really helpful if you could test with the latest packer (or packer v0.12.2 when it's released) and update with the debug log here if you still see error

**Comment by dan-rose** [comment]
Great stuff will do, thank you for keeping me updated

**Comment by dan-rose** [comment]
@mwhooker  Sadly, I have not any more success with this issue. I still get an error 500 when attempting to upload file - here is a [copy of the log](https://gist.github.com/dan-rose/69c48e9fc5450122c15e9d7cf4833710)

Am happy to assist in getting this working - please feel free to update and let me what else to try/do

**Comment by DanHam** [comment]
`2017/01/23 17:26:22 [INFO] Packer version: 0.12.1`

@dan-rose Hi Dan. From your log it looks as though you are using v0.12.1. Can you update to v0.12.2 and test again?

**Comment by dan-rose** [comment]
@DanHam  Hi Dan. Oh sorry that's weird, I downloaded it from packer.io yesterday.. hmm did wonder why also the the skip_export option was not recognized. Apologies, will try again

Dan

**Comment by dan-rose** [comment]
Some positive news.. first attempt successful - from the log it looks as though the upload was much faster than in previous builds too. I will try some more builds later today/tomorrow.. 

Thanks again

**Comment by DanHam** [comment]
@dan-rose Great news! 

Since the update to WinRM for v0.12.2, I've been unable to reproduce the 500 error I was seeing when uploading VMware tools. I'm not 100% certain yet, but I'm hopeful this has solved the issue...

**Comment by mwhooker** [comment]
great! It doesn't look like we can be completely certain it's fixed, but it's looking that way. going to close for now, but please reopen or comment here if you see it again
