### ISSUE TITLE
Allow custom SAS URL lifetime in Azure builder

### ISSUE THREAD

**Issue by elliottsam** [mitchellh/packer#4224]
In the Azure builder, allow custom lifetime for SAS URL, this is currently hard coded to one month

I need SAS URLs with a lifetime longer than one month, so currently am using the Azure CLI once I have built an image to create another longer lived SAS URL, would be good to have this configurable within Packer

**Comment by mwhooker** [comment]
Looks like this was fixed in https://github.com/mitchellh/packer/pull/4225 but something happened with the PR and it never got merged.

Going to close this since it's not something we're targeting for 1.0. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
