### ISSUE TITLE
Support for MFA with SSH

### ISSUE THREAD

**Issue by GavinPacini** [mitchellh/packer#4252]
I am trying to use packer to keep my AMIs up to date (might seem convoluted but we are PCI compliant so everything is convoluted).

However, our AMIs employ the [google-authenticator PAM module](https://github.com/google/google-authenticator-libpam). I would appreciate if packer could prompt the user if it detects that SSH login is looking for more information (i.e. a verification code from Google Authenticator).

Thank you!

**Comment by rickard-von-essen** [comment]
This is really tricky because:

1) Packer is a automation to and should not require manual interaction.
2) SSH auth: `KeyBoardInteractive` doesn't specify which input is required, it just prints a string and waits for a response. `ssh_password` will be used as a response so you could add your MFA as a `-var` but it will be expired before ssh is available. Since the string is made for a human to interpenetrate there is no way to detect if a MFA is needed.

My suggestion is that you:
1) Use a temporary ssh keypair since they are way more secure than MFA + password anyway.
2) Disable `pam_googleauth` for the packer ssh. It can be done in a user-script and re-enabled in end of provisioning.
3) Similar to 1) but using SSH Agent to allow using personal public key auth with passphrase protected ssh keys. (New in 0.12.0 see #4050)

PS. I too work in a PCI/DSS env.

**Comment by GavinPacini** [comment]
Hi @rickard-von-essen,

Thank you for the prompt and detailed reply. Just a note, we are using MFA comprising of google authenticator and SSH keys - no passwords involved. I agree that's more secure.

I like the idea of exempting a packer user from google authenticator with a user-script and re-enabling afterwards. I think that makes the most sense in our case.

Thanks again! Feel free to close this issue when you're ready.

**Comment by mwhooker** [comment]
Thanks for the input, that's not a case we had considered. It sounds like you have a workable solution, so closing this for now. Would be happy to review any PRs that would add support for MFAs in the future.
