### ISSUE TITLE
amazon-chroot should support instance store AMIs

### ISSUE THREAD

**Issue by willglynn** [mitchellh/packer#4264]
Packer currently has three EC2 AMI builders:

> `amazon-ebs` - Create EBS-backed AMIs by launching a source AMI and re-packaging it into a new AMI after provisioning. If in doubt, use this builder, which is the easiest to get started with.
>
> `amazon-instance` - Create instance-store AMIs by launching and provisioning a source instance, then rebundling it and uploading it to S3.
>
> `amazon-chroot` - Create EBS-backed AMIs from an existing EC2 instance by mounting the root device and using a Chroot environment to provision that device. This is an **advanced builder and should not be used by newcomers**. However, it is also the fastest way to build an EBS-backed AMI since no new EC2 instance needs to be launched.

`amazon-ebs` and `amazon-instance` both follow the "make a box, change the box, pack the box" process. `amazon-chroot` is the "make an image, pack the image" process, which is what I want, but at present it supports only EBS-backed images, which is not what I want.

The official Amazon AMI tools support both processes: self-packing via `ec2-bundle-vol` (which `amazon-isntance` uses) and packing an image by `ec2-bundle-image`. I'm thinking the `amazon-chroot` packer would make a filesystem on an EBS volume, `chroot` into it, do all the things, unmount it, snapshot the volume and register the snapshot as an EBS AMI like it does now – and then `ec2-bundle-image` the root partition, upload the bundle to S3, and register the bundle as an instance store AMI.

That said, it's my opinion that the official tools for instance store AMIs are a huge pain, so I made an alternative. There's an [`aws_bundle` Go library](https://github.com/willglynn/go_ami_tools/tree/master/aws_bundle) which handles all the bundle format details, and an [`ec2-bundle-and-upload-image` command line tool](https://github.com/willglynn/go_ami_tools/tree/master/cmd/ec2-bundle-and-upload-image) which takes a disk image as an input and bundles it straight to S3. There's no temporary files, no Java or Ruby dependencies, and no RSA keys or X.509 signing certificates. I dare to call it convenient 😀

I note also there's no particular reason that AMI creation has to be done inside EC2, though that's [true for EBS as well](http://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-import-snapshot.html). I'm asking to add this to `amazon-chroot` anyway since what I _actually_ want is to create both an EBS-backed and an instance-store AMI containing the same bits at the same time, and adding a second output to the `amazon-chroot` packer seems to make the most sense.

**Comment by rickard-von-essen** [comment]
> I note also there's no particular reason that AMI creation has to be done inside EC2

We have the `amazon-import` post-processor to handle importing AMI's from other builders. It's rather new and might need some additional features to suit your needs.

> it's my opinion that the official tools for instance store AMIs are a huge pain, so I made an alternative

Definitely agree! We would appreciate a PR that add info to the docs on how to use `ec2-bundle-and-upload-image` instead.

> adding a second output to the amazon-chroot packer seems to make the most sense

We would happily review a PR for this, also allowing the `amazon-chroot` to only EBS or instance store backed AMI's.

Would there be any big benefits of using your lib directly instead of using the  command line tool?

**Comment by willglynn** [comment]
> We have the `amazon-import` post-processor to handle importing AMI's from other builders. It's rather new and might need some additional features to suit your needs.

Interesting! I had not seen this.

> Would there be any big benefits of using your lib directly instead of using the command line tool?

Well, it would let Packer support more things without needing the user to install more things. Looking at the [current `amazon-inport` post-processor](https://github.com/mitchellh/packer/blob/master/post-processor/amazon-import/post-processor.go), I think it's a perfect fit for the library:

1. Currently, `amazon-import` copies an OVA to S3 verbatim. Instead, open the OVA, `io.Copy` the disk image it contains to an `aws_bundle.Writer`, and stream the `Writer`'s output to S3.
2. Currently, `amazon-import` calls [`ec2:ImportImage`](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportImage.html), asking Amazon to convert the uploaded OVA to an EBS snapshot and to register that snapshot as an EBS AMI. Instead, call [`ec2:RegisterImage`](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RegisterImage.html), asking Amazon to register the uploaded manifest as an instance store AMI.

That's it. With those changes, `amazon-import` could make both EBS and instance store AMIs.

I suppose this doesn't really apply for `amazon-chroot`, since in that scenario there's no Packer binary running on the builder host. Might as well just ask the user to install `ec2-bundle-and-upload-image` just like `amazon-instance` asks them to install `ec2-bundle-vol`. I think Packer should still do the `ec2:RegisterImage` call, though.

**Comment by mwhooker** [comment]
I think this makes sense, but it has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
