### ISSUE TITLE
Post-processors should be linked to builders when using the "--only" CLI option

### ISSUE THREAD

**Issue by ttrifonov** [mitchellh/packer#4270]
I am using the `--only` option to run a specific build (in my case `amazon-ebs`), but I have another builder with type `docker` and a post-processor `docker-tag` for it. Since the `--only` option doesn't run the Docker build, I can't limit the post-processor to not run and raise an error. I think post-processors should be able to be linked somehow (using a tag?) to builders, and the `--only` filter to apply to them as well.

- Packer version from `packer version` - `0.12`
- Host platform - Mac OS
- Debug log output from `PACKER_LOG=1 packer build template.json`.

```Build 'amazon-ebs' errored: 1 error(s) occurred:
* Post-processor failed: Unknown artifact type: mitchellh.amazonebs
Can only tag from Docker builder artifacts.
```

**Comment by mwhooker** [comment]
I agree it could be a little more intuitive, but it should be possible with this https://www.packer.io/docs/templates/post-processors.html#run-on-specific-builds

I'm not sure we can set up the `--only` flag to apply to the post-processors, too, since they may have different names than the builders.
