### ISSUE TITLE
progress for atlas upload

### ISSUE THREAD

**Issue by MansM** [mitchellh/packer#4364]
Feature request:

As Atlas & packer user I would like to see a progress percentage on uploading a box to atlas

During the upload process I cant see how for packer is with uploading the box.

**Comment by mwhooker** [comment]
Thanks for the feedback. This would indeed be handy.
I've successfully used https://github.com/cheggaaa/pb in the past, which I can recommend here.

If anyone wanted to take a swing at implementing this, you would want to look at command/push.go:348

instead of passing in r, you would do something like

```go
bar := &pb.New(r.Size).SetUnits(pb.U_BYTES)
bar.Start()
tee := io.TeeReader(r, bar)
// ...
err := c.client.UploadBuildConfigVersion(&version, opts.Metadata, buildVars, r, r.Size)
// ...
bar.Finish()
```


I haven't tested but I believe that will work.


I'd also want to see this behind a flag, so only show the progress bar if, say, `--show-progress` is passed to `packer push`

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.
