### ISSUE TITLE
Add VMware vCenter vSan

### ISSUE THREAD

**Issue by alejojo** [mitchellh/packer#4370]
We have been using packer with plain esxi and also with vSphere vCenter and works perfectly. However for a new project we have vSan and when trying to create the vmachine into the vSan datastore it gives error that is read-only.
We tried to provision with Foreman/vmware plugin and works fine

**Comment by rickard-von-essen** [comment]
We would appriciate a PR for this.

**Comment by lmayorga1980** [comment]
@alejojo Can you share how you connect to vCenter?. I am trying to pull this off with packer.

```
  ovftool /ovfs/my_vapp.ovf \
           vi://username:pass@my_vc_server/?ip=10.20.30.40
   (.ovf file to vCenter server using managed ESX host ip address)

   ovftool vi://username:pass@my_vc_server/my_datacenter?ds=\
           [Storage1] foo/foo.vmx c:\ovfs\
   (VM on ESX/vCenter server to OVF using datastore location query)

   ovftool /ovfs/my_vapp.ovf \
           vi://username:pass@my_vc_server/my_datacenter/host/my_host
   (.ovf file to vCenter server using vCenter inventory path)
```

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
