### ISSUE TITLE
builder/hyperv reboot also from ISO and not HDD

### ISSUE THREAD

**Issue by bla-kw** [mitchellh/packer#4417]
- Host platform: Windows 10
- Packer version: 0.12.1
- Hyper-V generation 1 VM

I want to create a CentOS7 image and after ks finished the first installation it reboots, but then it hangs and Packer times out because it tries to boot from CD again and not from HDD.

**Comment by DanHam** [comment]
I've taken a look at this but have not been able to reproduce this issue. For me, building a CentOS 7 image with Hyper-V works as expected. 

@bla-kw Some more information here would be helpful. Please provide Gists with the template, scripts, etc required to reproduce the issue. Please also provide a Gist containing debug logs from the failed build attempt.

My suspicion is that this is being caused by an error in your template or build scripts somewhere. If you like, feel free to take a look at my CentOS Hyper-V builder template and files [here](https://github.com/DanHam/packer-testing/tree/master/hyper-v/centos). The resultant box isn't of much use for anything, but it does build successfully.

**Comment by tonyskidmore** [comment]
I think the key thing is what can be seen in the example ks.cfg provided in the link provided above:

reboot **--eject**

I was having a similar issue in my first attempts before adding the --eject option.

**Comment by DanHam** [comment]
@tonyskidmore Yep, good one - that would be a likely culprit!

**Comment by bla-kw** [comment]
Thank you very much. Yes, the --eject is necessary for hyper-v.
