### ISSUE TITLE
builder/vmware: Error uploading VMware Tools

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#4434]
vmware building windows server 2012 randomly crashes with

```
2017/01/20 00:15:42 ui: ==> vmware-iso: Connected to WinRM!
2017/01/20 00:15:42 ui: ==> vmware-iso: Uploading the 'windows' VMware Tools
==> vmware-iso: Connected to WinRM!
2017/01/20 00:15:42 packer: 2017/01/20 00:15:42 Uploading file to 'C:/Windows/Temp/windows.iso'
==> vmware-iso: Uploading the 'windows' VMware Tools
2017/01/20 00:15:45 ui error: ==> vmware-iso: Error uploading VMware Tools: Error uploading file to $env:TEMP\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer
2017/01/20 00:15:45 packer: 2017/01/20 00:15:45 Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun [-T fusion list]
==> vmware-iso: Error uploading VMware Tools: Error uploading file to $env:TEMP\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer
2017/01/20 00:15:45 packer: 2017/01/20 00:15:45 stdout: Total running VMs: 2
2017/01/20 00:15:45 packer: /Users/mwhooker/dev/packertest/4134/packer_tmp-Windows-2016-vmware/tmp-Windows-2016.vmx
2017/01/20 00:15:45 packer: /Users/mwhooker/.docker/machine/machines/default/default.vmx
2017/01/20 00:15:45 packer: 2017/01/20 00:15:45 stderr:
2017/01/20 00:15:45 ui: ==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Stopping virtual machine...
2017/01/20 00:15:45 packer: 2017/01/20 00:15:45 Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun [-T fusion stop packer_tmp-Windows-2016-vmware/tmp-Windows-2016.vmx hard]
2017/01/20 00:15:48 packer: 2017/01/20 00:15:48 stdout:
2017/01/20 00:15:48 packer: 2017/01/20 00:15:48 stderr:
2017/01/20 00:15:48 packer: 2017/01/20 00:15:48 Deleting floppy disk: /var/folders/yy/ff0tkhr141xdxvxf5fz43kmw0000gn/T/packer485556434
2017/01/20 00:15:48 ui: ==> vmware-iso: Deleting output directory...
==> vmware-iso: Deleting output directory...
2017/01/20 00:15:48 ui error: Build 'vmware-iso' errored: Error uploading VMware Tools: Error uploading file to $env:TEMP\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer
2017/01/20 00:15:48 Builds completed. Waiting on interrupt barrier...
Build 'vmware-iso' errored: Error uploading VMware Tools: Error uploading file to $env:TEMP\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer
2017/01/20 00:15:48 machine readable: error-count []string{"1"}
2017/01/20 00:15:48 ui error:
==> Some builds didn't complete successfully and had errors:

2017/01/20 00:15:48 machine readable: vmware-iso,error []string{"Error uploading VMware Tools: Error uploading file to $env:TEMP\\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer"}
2017/01/20 00:15:48 ui error: --> vmware-iso: Error uploading VMware Tools: Error uploading file to $env:TEMP\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error uploading VMware Tools: Error uploading file to $env:TEMP\winrmcp-b1531d82-e8d8-42a0-6cb9-4744b7b4a197.tmp: unknown error Post http://172.16.167.165:5985/wsman: read tcp 172.16.167.1:52697->172.16.167.165:5985: read: connection reset by peer
```

Using this json https://github.com/mwhooker/packer-demo/tree/win-sysprep

I wonder if we need to try multiple times to upload the vmware tools

It happens almost exactly 1/3 of the time (sample size 9)

**Comment by DanHam** [comment]
@mwhooker Ultimately, I think this is due to the restart of WinRM [in this script](https://github.com/mwhooker/packer-demo/blob/win-sysprep/scripts/enable-WinRM.ps1#L22-L25). I don't think this is a WinRM or Packer issue.

1. The ```winrm quickconfig -q``` command [here](https://github.com/mwhooker/packer-demo/blob/win-sysprep/scripts/enable-WinRM.ps1#L9) configures *everything* required to allow Packer to connect over WinRM - e.g. the WinRM listener, firewall rules etc.
2. Packer can now connect and begins the upload of the VMware Tools
3. The rug is pulled from under Packers feet by the restart of WinRM - hence the ```connection reset by peer``` seen in the log

Note the error happens pretty quick after the upload begins.

This appears to happen sporadically (1/3 of the time as you are seeing it) because it depends on the timings of when Packer attempts to establish a connection. 
* If the timings on the connection attempt mean Packer connects right after the ```winrm quickconfig -q``` command we will see the error since WinRM will be restarted after Packer has connected. 
* If the timings on the connection attempt mean we connect after the script has completed (or at least after the WinRM restart) we won't see an error.

I was able to prevent this happening by manually setting up the WinRM connection rather than using the `quickconfig` method. See the script I use [here](https://github.com/DanHam/packer-templates/blob/master/windows2012r2/files/SetupWinRM.ps1)

As an aside, I'm surprised that more people haven't run in to this as the use of ```winrm quickconfig -q``` followed by the set up and then restart of WinRM is a common pattern in many of the scripts and answer files I've looked at. Perhaps people have just been blaming WinRM?

I think you would see the same thing if you ran that script for a Virtualbox build and used the `upload` method. However, most people use the ```attach``` method because it's faster and/or they've had problems with the upload of big files over WinRM (that 500 error)

**Comment by DanHam** [comment]
@mwhooker If you do have a go with [this script](https://github.com/DanHam/packer-templates/blob/master/windows2012r2/files/SetupWinRM.ps1) you'll probably need to paste [these lines](https://github.com/mwhooker/packer-demo/blob/win-sysprep/scripts/enable-WinRM.ps1#L1-L2) at the head of the script to disable UAC (I use a separate script for that).

**Comment by mwhooker** [comment]
@DanHam That makes a lot of sense, thanks.

Will close this, but hopefully people will find the reason if they search and come upon this issue.
