### ISSUE TITLE
breaking packer template to several ones

### ISSUE THREAD

**Issue by mushon4** [mitchellh/packer#4440]
Hi,

Let's say I want to fix some script I need to run the entire build over again in order to verify my fix.

So I have started by running sequential ova (virtual box) builds, importing from ova and exporting to ova 6 times.

I am doing so in order to be more efficient while developing, the packer template would takes about 1 hour to run, so I broke my template into 6 of them.

Now each time I fix something I need to run only the ones that got affected. 
The issue I want to solve is the useless export/import I am running each time. I have seen that the latest release has now skip_export but what about skip import or builder of type vdi, vbox file? 

Is somebody work on it? is there any nice solution which can solve my problem that I am not aware of?

Thanks,
Mushon.

**Comment by rickard-von-essen** [comment]
If you're spending a lot of time developing long running provision scripts I can only recommend that you use a base Vagrant box that you start and then use the `null` builder to run those provision scripts against this running box.

**Comment by mushon4** [comment]
I can also do that with just leaving the ova register in vbox by using the flag "keep_registered" but then I would still need to run the export when will run my closer template. In the end I want to deliver an ova file.

Thanks for your suggestion we would consider using this but we still need to export manually by vboxmanage utility.

**Comment by mwhooker** [comment]
Interesting idea. I agree that an iterative development story on vbox would be handy, however it's not something we're planning to implement for 1.0. We should keep discussing ideas in this thread, and maybe we can come up with how we could accomplish that.

For now, though, since this not something we're targeting for 1.0, I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.
