### ISSUE TITLE
Packer on CentOS 7.3 building remote vsphere builder

### ISSUE THREAD

**Issue by jk-shah** [mitchellh/packer#4504]
FOR BUGS:

Describe the problem and include the following information:

- Packer version from `packer version`
0.12.2

- Host platform
CentOS 7.3

EXS 6.0

Using VMware builder and building CentOS 7.3 OVA images. Noticed that kickstart file can no longer be read from VM being created. 
After digging I found that firewalld with CentOS 7.3 blocks the port which was not the issue on CentOS 7.3 with packer. 

Not sure if firewalld has changed with 7.3 which causes the exposed http/ks.cfg being not exposed out automatically anymore. As it uses a random port it is hard to pre-open that port. For the time being I had to shutoff firewalld on the CentOS 7.3 where I run packer  to make it work.

**Comment by rickard-von-essen** [comment]
Sorry I don't see that you are describing any issue with packer? Can you please clarify and reopen, unless this is a question then use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

_If you are describing a bug or a feature request please reopen and try to add some more details to make it clearer._

**Comment by dgoerger** [comment]
For anyone else experiencing this and not wanting to disable firewalld completely, you can work around this by adding the vmnet8 network to the "trusted" zone. Per [Fedora Project documentation](https://fedoraproject.org/wiki/Firewalld?rd=FirewallD#trusted),

> **trusted**
> All network connections are accepted.

... i.e., any port. Because this network is bound to the internal vmnet8 interface, this shouldn't open the firewall to traffic from other (external) devices on the network that may share the same space (and if there are networks with overlapping address space, you'll probably experience more pressing issues related to routing). The expectation is that we only open the firewall to traffic originating on the vmnet8 interface.

Assuming vmnet8 is bound to `192.168.245.0/24`, this should do the trick:

```firewall-cmd --zone=trusted --add-source=192.168.245.0/24 --permanent```
