### ISSUE TITLE
ansible-local provisioner should be able to specify directory as inventory

### ISSUE THREAD

**Issue by yukihiko-shinoda** [mitchellh/packer#4510]
In Ansible Official Doc, Best practice of directory layout is defined as follows.

[Best Practices — Ansible Documentation](http://docs.ansible.com/ansible/playbooks_best_practices.html#alternative-directory-layout)

And, although there are no clear descriptions in the official Doc,
in the following article, One of the Ansible developer says that
We can specify a directory by the -i option of the ansible-playbook command as inventory.

[Alternative Directory Structure requires complete file path with -i · Issue #18686 · ansible/ansible](https://github.com/ansible/ansible/issues/18686)

But, in Ansible Local provisioner of Packer (confirmed version: 0.12.2),
If specify a directory with the "inventory_file" configuration, an error occurs.

```
{
"type": "ansible-local",
"playbook_file": "playbook.yml",
"inventory_file": "inventories/test"
}
```

```
1 error(s) occurred:

* inventory_file: inventories/test must point to a file
```

And, even if we stop to use "inventory_file" option
and use "extra_arguments" with the -i option to specify a directory,
Packer automatically creates an inventory file and duplicates the -i option,
so Host_vars, group_vars, etc. in the inventory directory are not loaded properly.

```
"type": "ansible-local",
"playbook_file": "playbook_dummy.yml",
"extra_arguments": [
"-i",
"inventories/test"
]
}
```

```
cd /tmp/packer-provisioner-ansible-local &amp;&amp; ANSIBLE_FORCE_COLOR=1 PYTHONUNBUFFERED=1 ansible-playbook /tmp/packer-provisioner-ansible-local/playbook.yml -i inventories/test -c local -i /tmp/packer-provisioner-ansible-local/packer-provisioner-ansible-local138537763
```

If we specify "host_vars" or "group_vars" in the configuration of Ansible Local provisioner,
Packer copies the specified host_vars and group_vars directories into
/tmp/packer-provisioner-ansible-local

However, as you can see from the Best practice of the directory layout 
on the Ansible Official Doc,
"host_vars" or "group_vars" of playbook may already exists under Ansible's project directory,
so it's different behavior from the intention of the Ansible project developer.

[group_vars not recognised when under inventory directory using ansible remote · Issue #3863 · mitchellh/packer](https://github.com/mitchellh/packer/issues/3863)

In the official Doc of Ansible, the reading priority of the variable is clearly defined,
The directory structure of the Ansible project is the one what the developer designs intentionally.

[Variables — Ansible Documentation](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)

But Packer's Ansible Local provisioner is implemented to want to change the directory structure of Ansible project.

**Comment by mwhooker** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come.  We rely on the community to support this provisioner, so the best way to get this added would be to implement it.. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'm happy to do that too. 

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
