### ISSUE TITLE
Feature Request: Packer builder for SoftLayer

### ISSUE THREAD

**Issue by onmariano** [mitchellh/packer#4571]
It would be nice to have a packer builder for IBM SoftLayer.

**Comment by mwhooker** [comment]
Would be happy to take a look at any PR that comes in for this.

However, this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate for more years to come. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, feel free to reach out. I can help answer questions and do pre-reviews.

The reason we're more aggressively closing these issues at the moment is because we're pushing towards a 1.0 release, and reviewing all open issues as part of that process. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

Again, just want to say thank you for suggesting this and I DO think its a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
