### ISSUE TITLE
googlecompute: Doesn't work with cross project accounts anymore

### ISSUE THREAD

**Issue by assen-todorov** [mitchellh/packer#4608]
Since 0.11.0 Packer fails with:

```
The user does not have access to service account 'build@build-system.iam.gserviceaccount.com'.  User: 'build@build-system.iam.gserviceaccount.com'.  Ask a project owner to grant you the iam.serviceAccountActor role on the service account
```

Our setup
----------

We have 2 Google Projects - **Build-System** and **Production**
**Build-System** is our CI/CD environment and **Production** is our production environment. In the project **Build-System** we have a service account `build@build-system.iam.gserviceaccount.com`, which has _Owner_ and _Service account actor_ roles. This account is also added as user with role _Owner_ and _Service account actor_ in the project _Production_.

The build process (i.e. packer build) runs on GCE-Instance in the project **Build-System** authenticating with `build@build-system.iam.gserviceaccount.com` and try to build new GCE-Image in the project **Production**.
Before Packer version 0.11.0 all did work like a charm (there was even no need to add the role _Service account actor_) Since 0.11.0 packer fails with the above error message.

Packer version: 0.12.2 (issue appears since 0.11.0)
Host platform: GCE instance with Ubuntu 16 LTS
Packer template & debug output: https://gist.github.com/Mortanon/38c4aeade05d4b887287d3849458be63

EDIT: Cleaned up an reformatted. @rickard-von-essen

**Comment by rickard-von-essen** [comment]
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by Mortanon** [comment]
I did already provide all the requested information at the end of the issue. Here it is again:

Packer version: 0.12.2 (actually the issue appears since 0.11.0)
Host platform: Linux config 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Packer template & debug output: https://gist.github.com/Mortanon/38c4aeade05d4b887287d3849458be63

**Comment by Mortanon** [comment]
Could you open the issue please :-) it is closed now although I provide all the requested information.

**Comment by rickard-von-essen** [comment]
Sorry, a bit quick on the gun 🔫

**Comment by nohn** [comment]
Reproducible with 0.12.3

**Comment by Mortanon** [comment]
I was able to locate the cause for this in the source code.
This [commit](https://github.com/mitchellh/packer/commit/7190fbeed8a13f07ca8f008576a0c5d994158c6d) introduces the folowing change in **griver_gce.go**:
```
ServiceAccounts: []*compute.ServiceAccount{
  			&compute.ServiceAccount{
 -				Email: "default",
 +				Email: c.ServiceAccountEmail,
  				Scopes: []string{
  					"https://www.googleapis.com/auth/userinfo.email",
  					"https://www.googleapis.com/auth/compute",
```
Using `c.ServiceAccountEmail` instead of `"default"` breaks all GCE-builds where cross-project service account is used as resource and identity (as described here [Best Practices for Enterprise Organizations](https://cloud.google.com/docs/enterprise/best-practices-for-enterprise-organizations))

Any chance to fix it?

**Comment by rickard-von-essen** [comment]
@crunkleton Any comment to this?

Your commit has the following info:
> Changed the instance service account to use the same service account as the one provided in the Packer config template. It was the project default service account.

**Comment by crunk1** [comment]
Sorry for the hassle, everyone!
I think I made that change in effort to support "- Script log can be copied to a GCS location by setting the metadata field 'startup-script-log-dest'."
The thought was that the user has a better idea of what GCS permissions they have via their provided credentials vs what GCS permissions the project default service account has. 

Changing that back to default shouldn't be an issue otherwise.

**Comment by crunkleton** [comment]
Sorry for the hassle, everyone!
I think I made that change in effort to support "- Script log can be copied to a GCS location by setting the metadata field 'startup-script-log-dest'."
The thought was that the user has a better idea of what GCS permissions they have via their provided credentials vs what GCS permissions the project default service account has.

Changing that back to default shouldn't be an issue otherwise.

**Comment by rickard-von-essen** [comment]
@assen-todorov @nohn @crunkleton Can you please verify that the fix in #4749 solves your issue.

Is there _any_ drawback or problem with switching to `default`?

**Comment by assen-todorov** [comment]
Currently I do not see any drawbacks, but I must admit, it looks strange to me, that the Google API forces  to send "_default_" instead of real email address for cross project service accounts. At least it should be documented in the Google API (I was not able to find any documentation on this). 
Perhaps it is bug in the Google Compute API?

**Comment by crunkleton** [comment]
I'm pretty sure "default" will give the VM scopes under the project's
default service account credentials. If you create a VM in project "foo"
and you wanted to modify a project "bar," the default service account for
"foo" would need permissions to "bar" which is absolutely possible to do,
but can sometimes catch you off-guard.

That's why I made the change. If you provide credentials for a user, "x,"
you might have a better idea of what permissions are granted to "x" rather
than what permissions are granted to the default service account for
project "foo."

Another way to look at the case of running a VM in "foo" but modifying
"bar":
Using default:

   - You need to make sure the creds you give to Packer have access to "foo"
   - You need to make sure the default service account for "foo" has access
   to "bar"

Using the email from the account creating the VM:

   - You need to make sure the creds have access to "foo" and "bar"

**Comment by nohn** [comment]
Yes, this fixes the issue.

**Comment by mjcramer** [comment]
Yeah, but now this is broken for GCP projects which do not have a default service account. I need to be able to specify a service account to use as I'm controlling access to various resources. I kinda feel like cross-project building is a much more esoteric use case than wanting more granular control over service accounts.

**Comment by rickard-von-essen** [comment]
@mjcramer Please open a PR which solves both cases.

**Comment by mjcramer** [comment]
It's a fair demand, but unfortunately I do not know go and will have to make some time to absorb the learning curve. I will contribute but cannot give a time frame. Will keep you posted...

**Comment by rickard-von-essen** [comment]
@mjcramer you can also open a feature request and provide allot of details around how this could work and gather references.

**Comment by roman-cnd** [comment]
This is actually a problem with crappy google's IAM. Indeed, they made impossible to grant roles to instances from a project (by attaching service accounts from _another_ project). Which is what @assen-todorov run into. This actually wasn't a regression, its rather google's wonderful IAM design :( 

I'd like to get service accounts back. Maybe as a config option?

2 arguments for this: google itself saying that scopes are legacy way of assigning permissions to the instance - https://cloud.google.com/iam/docs/service-accounts.

And another argument is that the build scripts may rely on having SA attached to instance versus using SA keys or scopes.

Thanks!

**Comment by rickard-von-essen** [comment]
@roman-cnd could you open an issue (feature req) and describe in detail how this could work with an config option, or create a PR for it.
