### ISSUE TITLE
Feature request: Possibility to name the steps

### ISSUE THREAD

**Issue by marema31** [mitchellh/packer#4640]
In my day jobs some packer json contains several calls to shell (local and remote) provisionner and post-processor. And when an error occurs peoples tend to send me only partial copy-paste of the message like this:

```
==> vmware-iso (shell-local): Executing local script: /tmp/packer-shell010664673
Build 'vmware-iso' errored: 1 error(s) occurred:

* Post-processor failed: Erroneous exit code 1 while executing script: /tmp/packer-shell010664673

Please see output above for more information.
```

Even I try to educate them to send me complete logs, it will be a great helper for me to have the ability to add a `step_name`  to theses step to quickly view in which step they have trouble.
The idea will be to be able to have this in json:

```
{
  "step_name": "Register to update server"
  "type": "shell-local"
  "inline": "my_register_command ..."
}
```
And have the following ui log (step name decoration can be discussed):
```
==> vmware-iso (shell-local:Register to update server): Executing local script: /tmp/packer-shell010664673
```

My current workaround is to do `echo Register to update server` in my inlines, but it should be cleaner than that.
If this feature seems interresting to you I can try to look for doing a PR, but I'm not sure where to do this modification (any clues ?)

**Comment by rickard-von-essen** [comment]
IMHO its a to specific feature which is as you say easily done with `echo` to make it worth implementing/maintaing.

**Comment by mwhooker** [comment]
I could see how this could be useful for debugging, but I tend to agree with rickard. This isn't something that I think we will work on, but if you wanted to submit it as a PR we'll definitely consider it.

I think I would look at the `Provisioner` struct in `template/template.go`. You'll see the `Builder` struct also has a `Name` field, so you'd want to see how that's used to get an idea for how to get it into the provisioner.

Going to close since we're not planning on working on it. If you want to submit a PR and get stuck, feel free to reach out to me. I'm available on the packer channel in [hangops slack](https://signup.hangops.com/)
