### ISSUE TITLE
Backwards-incompatible change to local Ansible runner

### ISSUE THREAD

**Issue by mmdriley** [mitchellh/packer#4680]
In #4472 the default value for `staging_directory` was changed from `/tmp/packer-provisioner-ansible-local` (still the [documented value](https://github.com/mitchellh/packer/blob/a3e0748fec110a7496836e70a73eb9eebd6f2a21/website/source/docs/provisioners/ansible-local.html.md)) to `/tmp/packer-privisioner/ansible-local/<random uuid>`.

This breaks Packer templates like [this one](https://github.com/remind101/empire_ami/blob/308bfdb6b73b89f31c622e4b0e9def5c846b13a0/packer.json#L46) that have assumed the default value. Not defending that code, but there it is, and I know it's used by a few companies.

I would at least hope to see this in the release notes and documentation. Meanwhile, perhaps there's another solution to #2838 that doesn't break anything?

**Comment by mwhooker** [comment]
D'oh! you're right, that is a BC change, which I should have called out, and also documented. 

I think the fix as is is proper, since it's the fix that will "just work" for the most people. A solution to the above problem would be to explicitly set `staging_directory` to "/tmp/packer-provisioner-ansible-local".

**Comment by mmdriley** [comment]
Fair enough. PR out with the fix. Thank you for the quick triage!
