### ISSUE TITLE
add xenserver-iso and xenserver-xva to builders (from github.com/xenserver/packer-builder-xenserver)

### ISSUE THREAD

**Issue by gaserre** [mitchellh/packer#4733]
I would like to add xenserver-iso and xenserver-xva builders from http://github.com/xenserver/packer-builder-xenserver rather than maintaining a separate builder plugin.  I have opened a similar issue in the packer-builder-xenserver repo.  

Questions:
- Are there guidelines for this I should read (other than the guidelines for contributing)?
- Should I just submit a PR (after waiting for comments in packer-builder-xenserver)?

Aside, I am planning on also submitting a gcp-chroot builder once I have it working.

**Comment by mwhooker** [comment]
Unfortunately we don't have any clear guidelines for new plugin contributions, but you can look through [previous plugin PRs](https://github.com/mitchellh/packer/issues?q=label%3Anew-plugin-contribution+is%3Aclosed) and see what the conversation was like.

One thing I will note is that in order for the code to be merged into master, it must be licensed under the MPL 2.0 and cannot have copyright attribution to someone else (although this don't seem like it's an issue).

We will also probably not merge a plugin unless we can get someone from the community to volunteer to maintain it. I'd find that person before working on creating the PR.

We'll also want sufficient documentation in `website/source/docs`. You can take an existing builder's docs to work off of.

If the above sound doable, I'd say feel free to create the PR.

**Comment by timoc** [comment]
This is related to #4295.

**Comment by kirannhegde** [comment]
Hello @mwhooker I am currently working on improving the documentation for the XenServer plugin. The question i have is, in it's current form, the XenServer plugin for Packer is a standalone executable. At the time of opening a PR, can it still be a standalone executable or should it follow the same guidelines as has been done for other plugins ie. the code for each vendor plugin is now merged into the Packer code base. Kindly advice.

**Comment by SwampDragons** [comment]
Hi, @kirannhegde. Things have changed a bit in the two years since Matt's answer above. We've decided that moving forward, we are not going to merge more third party builders with the Packer core. The reason for this is simply that we have several third party builders which are unmaintained, and we think it's confusing and unfair to our users to have some parts of the main Packer binary maintained and some not; we want to try to make that less of a problem moving forward. 

In order to make things easier for people using third party plugins in the future, we're hoping to make a kind of Packer registry with an "init" command that will automatically download and install the plugins you request in your Packer config. We will probably start working in earnest on that registry in the second half of this year.

However, I'd love it if you would make a PR adding the xenserver plugin to our community listing at https://github.com/hashicorp/packer/blob/master/website/source/partials/builders/_community_builders.html.md
