### ISSUE TITLE
Template validation & push fails with "A source_ami or source_ami_filter must be specified"

### ISSUE THREAD

**Issue by brian-sw** [mitchellh/packer#4743]
Using Packer 0.12.3 to build an AMI on Atlas using an Atlas Artifact as the base AMI. Packer validate always fails locally with the following error:

`A source_ami or source_ami_filter must be specified`

Here is what my ami.json is composed of:

```
{
	"variables": {
		"base_ami": "{{env `ATLAS_BASE_ARTIFACT_AMAZON_IMAGE_ID`}}"
  },
  "builders": [{
    "type": "amazon-ebs",
		"region": "us-east-1",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "my-ami-name_{{timestamp}}",
		"source_ami": "{{ user `base_ami` }}"
  }]
}

```
I have tried all of the Amazon-related image types located [here](https://atlas.hashicorp.com/help/packer/builds/build-environment) and they all produce the same error.

My Packer debug log can be found [here](https://gist.github.com/brian-sw/1e1e4e7a952bf418f2ed8ebed88a9b99)

**Comment by mwhooker** [comment]
To clarify, this happens when you're running on atlas, or when you're running locally?

**Comment by brian-sw** [comment]
Both. If you run ``Packer validate ami.json``, that error occurs. If you do a ``Packer push ami.json``, the logs in Atlas will fail and display that error.

**Comment by mwhooker** [comment]
What's happening is that since the environment variable `ATLAS_BASE_ARTIFACT_AMAZON_IMAGE_ID` is empty, the validation is failing since it doesn't think you have a `source_ami`.

This should work on atlas. I would make sure that the project is configured to have the correct setting under `Inject artifact ID during build`.

To run this locally, set `ATLAS_BASE_ARTIFACT_AMAZON_IMAGE_ID` to an AMI that exists.

Let me know if those don't work for you

**Comment by brian-sw** [comment]
Setting the variable locally at runtime worked. However pushing to Atlas still results in that error.

In the settings of my Packer configuration, I have an Atlas artifact set to be injected during the Packer build in Atlas. I followed [this ](https://atlas.hashicorp.com/help/packer/builds/build-environment#base-artifact-variable-injection)documentation. It acts as if the Atlas ID is not being injected.

**Comment by mwhooker** [comment]
Do you have a base artifact pushed up? You should have a post processor in your base AMI like

```
  "post-processors": [
    {
      "type": "atlas",
      "artifact": "{{user `atlas_username`}}/{{user `name`}}",
      "artifact_type": "amazon.image",
      "metadata": {
        "created_at": "{{timestamp}}"
      }
    }
  ],
```

https://atlas.hashicorp.com/help/packer/artifacts

**Comment by brian-sw** [comment]
Yup you bet. I have a post-processor and a push section:

```
"push": {
		"name": "org_name/build_name",
    "include": [
      "assets/*",
			"scripts/*"
    ]
	},
	"post-processors": [
	{
		"type": "atlas",
		"artifact": "org_name/artifact_name",
		"artifact_type": "amazon.image",
		"metadata": {
			"created_at": "{{timestamp}}"
		}
	}]
```

**Comment by mwhooker** [comment]
@brian-sw It's not clear to me that this is a packer bug. I would contact support for help on this: https://atlas.hashicorp.com/help/support

If it turns out to be a packer bug, we'll get an issue opened for it.

In the mean time, I would double check the docs to make sure you've got everything set up correctly.
