### ISSUE TITLE
Add Supported Builder to Post-processor API [RFC]

### ISSUE THREAD

**Issue by jasonberanek** [mitchellh/packer#484]
Post-processors are applied to each build within a given Packer template, unless the `only` or `except` options are configured on the post-processor. If those options are not set, this can lead to errors late in the Packer build run when a given post-processor finds it cannot handle the produced artifacts. 

It would good to provide a way for a post-processor to identify which builders it supports, allowing Packer to validate early whether a template defines a post-processor with an incompatible builder. When Packer sees this error during validation, it can alert the user to add the appropriate `only` and/or `except` options to resolve the issue.

I don't have a strong feeling on the best API implementation at this point, though it could be as simple as adding a `CheckBuilderSupport` function to the `PostProcessor` interface like the below:

```go
type PostProcessor interface {
    CheckBuilderSupport(Builder)(supported bool, err error)
    Configure(interface{}) error
    PostProcess(Ui, Artifact) (a Artifact, keep bool, err error)
}
```

@mitchellh Thoughts?

**Comment by mitchellh** [comment]
This would still be useful for validation reasons but I think otherwise there isn't a strong case for it now. If you want to continue the work, I'd welcome it. There are more post-processors but the implementation should still be straightforward and I'd be happy to help.

Otherwise, closing as we have no short term plans to do this.
