### ISSUE TITLE
Make paths in templates relative to the template

### ISSUE THREAD

**Issue by markjaquith** [mitchellh/packer#54]
I used this to convert a Veewee template to Packer: https://github.com/mitchellh/veewee-to-packer

The result went into an `output` subdirectory.

```
$ packer validate output/template.json 
Template validation failed. Errors are shown below.

Errors validating build 'virtualbox'. 1 error(s) occurred:

* Bad script 'scripts/postinstall.sh': stat scripts/postinstall.sh: no such file or directory

Errors validating build 'vmware'. 1 error(s) occurred:

* Bad script 'scripts/postinstall.sh': stat scripts/postinstall.sh: no such file or directory
```

But then:

```
$ cd output && packer validate template.json
Template validated successfully.
```

Shouldn't those paths be resolved as relative to the template path?

**Comment by gpakosz** [comment]
Has something be decided already? To me it's logical relative paths are relative to the `.json` template. That's the only sane behavior since `packer` can be launched from virtually anywhere.

@rasa I'm sorry it doesn't look daunting and likely your current expectation is the error prone one. Requiring the `packer` tool being launched from the proper directory is fragile at best.

**Comment by gpakosz** [comment]
@mitchellh instead of introducing something like, `{{template_path}}`, can't `packer fix` add calls to `{{pwd}}` and relative paths become relative to the template file?

So far this function doesn't seem to be much used (I suspect this is because there are few use cases where behavior has to depend on CWD)

**Comment by mitchellh** [comment]
@gpakosz Packer fix doesn't have semantic knowledge to know what fields represent paths. I think at this point it might be a bit too painful to break backwards compatiblity. I think we can start by introducing _both_ a `path-pwd` and `path-template` function. We can talk about deprecation later...
