### ISSUE TITLE
Add a "shell" post-processor

### ISSUE THREAD

**Issue by danielpetisme** [mitchellh/packer#644]
When there is not post-processor which fits the need, the ```shell``` post-processor would let the user to run custom scripts as post actions.

*NB1: ```shell``` isn't the best name. What about Windows...*
*NB2: giving the opportunity to users to run custom script is dangerous (not standard) but you can then gather those scripted behaviors and wrap them into a high-level post-processor*

**Comment by gamename** [comment]
Was this ever integrated?

**Comment by mitchellh** [comment]
We integrated a shell provisioner, which is one step forward here.

**Comment by vtolstov** [comment]
does this issue needs to be open? as i understand current shell-local already can do needed things.

**Comment by mitchellh** [comment]
Well, this issue is asking for a post-processor.

**Comment by gamename** [comment]
Which is still a good idea, IMHO.  With a shell post-processor, I can for example:
- Send a notification to a CI server or a user
- Gather the input artifacts (if saved) to upload them for archival data or maybe further processing
- Start another packer build which will use the boxes just completed.

**Comment by renaudguerin** [comment]
Gathering the artifacts (AMI ids in my case) for further processing was indeed my need.
Instead, I had to flip the logic on its head and run packer as a subprocess from a Python wrapper script, in order to parse its output in machine readable mode.
Being able to pass relevant artifact details to an external post-processor would have been *much* cleaner

**Comment by gamename** [comment]
Yup. Been there. Done that.  We could do so much if we could find a way to
'chain' builds so that output of one is input to another. Very powerful
opportunities in that.

$0.02

**Comment by gamename** [comment]
One real world example of this model is TeamCity.  Artifacts of one build
are dependent on another.
https://confluence.jetbrains.com/display/TCD9/Patterns+For+Accessing+Build+Artifacts

**Comment by vtolstov** [comment]
I have very simple post processor,I can try to create pull request...
23 июня 2015 г. 18:24 пользователь "Mitchell Hashimoto" <
notifications@github.com> написал:

**Comment by gamename** [comment]
Slow down.  Are you saying issues which could involve
packer/vagrant/terrraform/etc would be a different email address?

-T

**Comment by mitchellh** [comment]
@gamename Agreed (with this issue). I think you're crossing streams a bit into the public issue, which is fine but we lack context here. :)

**Comment by vtolstov** [comment]
@mitchellh may be something like this (uses old template, so need to modify to latest master)
https://github.com/vtolstov/packer-post-processor-shell

**Comment by StFS** [comment]
I need this to compress a qcow2 image. So +1.

**Comment by vtolstov** [comment]
You can use compress post processor.
10 сент. 2015 г. 2:16 пользователь "Stefán Freyr Stefánsson" <
notifications@github.com> написал:

**Comment by StFS** [comment]
@vtolstov no, that will give me a tar.gz file (or some other format of zip file). I want to run the generated qcow2 file through qemu-image in order to compress the image file (reclaim space of deleted files) and still get a qcow2 file out of that. The compress  post processor would give me a tar.gz file containing a qcow2 file.

**Comment by vtolstov** [comment]
@StFS yes, now i'm understand

**Comment by StFS** [comment]
@vtolstov would you consider forking the whole packer project and integrating your shell post processor into that and making a pull request? That might move things along maybe?

It seems weird that this, almost 2 years old, feature request hasn't been implemented yet as it is so very clearly something that would be extremely beneficial.

@mitchellh did this just fall through the cracks or is there some reason for this not being implemented? It doesn't seem like it would be all that hard to do, especially since there already seems to be an implementation available.

**Comment by vtolstov** [comment]
Me and another person already create pr to integrate this feature. You can
find it in pulls.
22 сент. 2015 г. 4:34 пользователь "Stefán Freyr Stefánsson" <
notifications@github.com> написал:

**Comment by tmartinx** [comment]
+100 for this feature!

**Comment by lerouxju** [comment]
+1. Need it to generate a SquashFS image.

**Comment by cbednarski** [comment]
For reference the PR that implements this is here: https://github.com/mitchellh/packer/pull/2706

**Comment by tlevi** [comment]
Really unfortunate, the author on that PR seems to have given up waiting.

**Comment by vtolstov** [comment]
I can take this and update pr, technicaly im already have uptodate pkugin
because use it internally.
31 янв. 2016 г. 13:57 пользователь "Tony Levi" <notifications@github.com>
написал:

**Comment by tylert** [comment]
Is this issue eligible to be closed now?  https://www.packer.io/docs/post-processors/shell-local.html is available in Packer 0.10.0.

**Comment by vtolstov** [comment]
yes, @cbednarski or @rickard-von-essen please close this.

**Comment by cbednarski** [comment]
Yep, thanks! This is part of packer now.
