### ISSUE TITLE
Resumable builds [RFC]

### ISSUE THREAD

**Issue by mwhooker** [mitchellh/packer#725]
The most disheartening thing for us is when a build fails at the very end because of any number of API errors.

It would be great if packer could save state on a failed build, and resume later.

Does anyone have any ideas on how this might work, or if there's a better idea?

**Comment by dragon788** [comment]
With some of the snapshotting plugins available (for Virtualbox and VMware providers at least) it would be interesting to see if there can be more progress on this.

**Comment by Kounavi** [comment]
Well, me and a teammate have had a though on building this for a long time since it would assist us a LOT in the development cycle (from speed to prototyping to fixing this etc). Thing is ... we are totally ignorant with the Go language. We've had a lot of ideas like setting a variable in JSON where when it's set to freeze it will not re-run the building step if it has successfully completed and the whole building process hasn't ended. Maybe we'll learn Go in the end! :P

**Comment by dragon788** [comment]
It is already possible to keep build artifacts, but this only works if all
the build steps actually complete successfully.

I think it would be interesting if failed build steps at the provisioning
or later stages would only work on copies or snapshots of the successful
install stage so that if one fails you don't lose all the progress, the
problem is that managing those snapshots and merging them is outside the
scope of most virtualization software.
